.gitignore
Gruntfile.js
package.json
plugin.json
web_client/js/imageViewerWidget/geojs.js

This uses GIrder's plugin build hooks to get geojs from npm and generate a custom bundle with necessary dependencies.  To the uninitiated, the magic components here are as follows:
* The [`grunt`](https://github.com/DigitalSlideArchive/image_viewer/compare/build-geojs-npm?expand=1#diff-b3568fa08e53a00f66841ed9ca2c53d4R6) keyword in `plugin.json` tells girder to load a javascript file before executing tasks.
* The [`default`](https://github.com/DigitalSlideArchive/image_viewer/compare/build-geojs-npm?expand=1#diff-35b4a816e0441e6a375cd925af50752cR58) keyword in `grunt.config` adds a task to the "default" target
* The existence `package.json` tells Girder to do `npm install` in the plugin directory during `grunt init`.
Something similar should probably be done for the resources loaded for …

Use geojs from npm

---

Gruntfile.js
package.json
web_client/js/imageViewerWidget/geojs.js

For files that have non 256-pixel square tiles, this still needs to be adjusted.

Update to geojs 0.6.0-rc1.

---

server/rest.py
server/tilesource/base.py
server/tilesource/dummy.py
server/tilesource/test.py
server/tilesource/tiff_reader.py
web_client/js/imageViewerWidget/base.js
web_client/js/imageViewerWidget/geojs.js
web_client/js/imageViewerWidget/leaflet.js
web_client/js/imageViewerWidget/openlayers.js
web_client/js/imageViewerWidget/openseadragon.js
web_client/js/imageViewerWidget/slideatlas.js

Confirmed that this works with non-square tiles (and tiles of any size).
The test tile server now can take a variety of query parameters:
-  min: minimum tile level (default 0)
-  max: maximum tile level (default levels parameter - 1)
-  fractal: if 'true', draw a simple fractal on the tiles (only on square power-of-two tiles)
-  w: tile width in pixels (default tileSize parameter)
-  h: tile height in pixels (default tileSize parameter)
-  sizex: image width in pixels at maximum level.
-  sizey: image height in pixels at maximum level.
The tile size is percolated through to the viewer javascript as tileWidth and tileHeight, if available.  If additional viewers are extended to handle non-square tiles, they should check if these values are set and fall back to tileSize if not.
The …

Added additional tile test options.

---

server/rest.py
server/tilesource/test.py
server/tilesource/tiff.py
server/tilesource/tiff_reader.py
web_client/js/imageViewerWidget/geojs.js

* Validate TestTileSource parameters in the REST API layer
* Internal APIs should mostly assume that they are being called with
the correct types.
* Necessary type conversion that's required due the limitations of HTTP
parameters is really an additional part of HTTP deserialization, and
should be performed by the REST API layer.
* Make TIFFTileSource use tileWidth and tileLength, instead of tileSize
* This fixes a bug where the TileSource.getMetadata was returning "null"
for the tileWidth and tileHeight.
* Since non-square tiles are now supported, this is simpler than trying to
also sometimes still use tileSize.
*  Use a BytesIO to store image data

Fix issues with tileSize

---

requirements.txt
server/tilesource/cache.py
web_client/js/imageViewerSelectWidget.js

The lru cache doesn't work with @staticmethod without some additional checks.
The element name was changed to an erroneous value.
Also, made the version for numpy >= rather than strictly == to avoid conflict with another plugin.

Fix a few bugs.

---

.travis.yml
Gruntfile.js
plugin.cmake
plugin.json
requirements.txt

* Rename steps in Grunt process to match plugin name
* Fix incorrect syntax in plugin.json
* Use Numpy 1.10.2, as 1.10.4 segfaults with Pylibtiff
* Add style testing to Python test directory

Build fixes

---

plugin_tests/tiles_test.py
server/__init__.py
server/models/image_item.py
server/tilesource/base.py
server/tilesource/svs.py
server/tilesource/tiff.py
web_client/js/imageViewerSelectWidget.js

* Make the 'largeImage' field into a dict, holding all related values
* ``item['largeImage']`` now potentially contains the fields:
* ``'fileId'``
* ``'sourceName'``
* ``'jobId'``
* ``'expected'``
* Remove the entire 'largeImage' dict field when a large image is deleted

Make the 'largeImage' field into a dict, holding all related values

---

plugin_tests/tiles_test.py
server/models/image_item.py
server/rest.py

If we have scheduled a conversion job, don't schedule another one.
Also, make fileId optional in POST image/{id}/tiles when there is exactly one file.

Only allow one job per item; make fileId optional.

---

plugin_tests/tiles_test.py
server/__init__.py
server/models/image_item.py
server/rest.py
web_client/js/imageViewerSelectWidget.js

This allows us to use the ``@loadmodel`` decorator in several places, and removes some special-case code.
It does remove the ability to permanently mark a specific item as a "test" largeImage. This functionality could be re-added if it turns out to be useful.

Refactor how the "test" tile source is handled

---

plugin_tests/tiles_test.py
server/models/image_item.py
server/rest.py
server/tilesource/base.py
server/tilesource/dummy.py
server/tilesource/svs.py
server/tilesource/tiff.py

Regions can optionally be scaled as part of the output.
This even works on sparse PTIF files at all resolutions.
There is currently no explicit guard on over-using memory.  We allocate memory for the PIL image in Python as a single block, which will gracefully fail if we ask for more memory than is in the system.  However, there are cases where python will fail to reuse memory after it has been used.  The memory is freed, but this still occurs.
We might want to use something like psutil to query how much memory the system has and not allow regions that use more than some factor of that (say 1/8th).  We could implement a lock so that a maximum of such a quantity of regions can be generated at a time, Otherwise, concurrent requests could OOM-kill the system.

Region endpoint.

---

plugin_tests/tiles_test.py
server/__init__.py
server/constants.py
web_client/js/configView.js
web_client/js/fileList.js
web_client/js/imageViewerSelectWidget.js
web_client/js/imageViewerWidget/geojs.js
web_client/js/itemList.js
web_client/stylesheets/fileList.styl
web_client/stylesheets/imageViewerSelectWidget.styl
web_client/stylesheets/itemList.styl
web_client/templates/largeImageConfig.jade
web_client/templates/largeImage_fileAction.jade

This currently has the region endpoints PR in the commit history; it can be separated from that, though it would be easier if that PR is resolved first instead.
This add a plugin settings page that allows turning on and off the image viewer on item pages, thumbnails in item lists, and setting the default viewer.  It adds thumbnails on item lists.  It adds additional actions on file lists: if a large image file is set, it can be removed.  If not set, it can be added to any file in the item.  If expected, the large image action icon is shown with some transparency to indicate that it is in progress.
There aren't any client tests yet.
Resolves issues #39 (client settings), #40 (thumbnails), and #41 (button to mark large image).

 Settings and thumbnails list

---

plugin_tests/tiles_test.py
server/rest.py
web_client/js/configView.js

Otherwise, unless you are logged in as an admin, the client can't read them.
I think Girder ultimately needs access control on individual settings, but that is a bigger issue.

Allow public access of large image settings.

---

plugin.cmake
plugin_tests/import_test.py
plugin_tests/tiles_test.py
server/models/image_item.py
server/tilesource/__init__.py
server/tilesource/base.py
server/tilesource/dummy.py
server/tilesource/svs.py
server/tilesource/test.py
server/tilesource/tiff.py
server/tilesource/tiff_reader.py

When we installed the large_image plugin in an environment that had openslide-python but not the libtiff module, the DummyTileSource replaced the tiff tile source (as intended), but then this "processed" SVS files and prevented them from working.  This change will allow the file to be properly handed off to the SVS tile source.
Improve the error messages for import failures.
Added some tests for import failures.

Better handling of exceptions when loading tile soruces

---

.gitignore
large_image.py
large_image/__init__.py
plugin.cmake
plugin_tests/girderless_test.py
plugin_tests/tiles_test.py
requirements.txt
server/__init__.py
server/base.py
server/models/image_item.py
server/tilesource/__init__.py
server/tilesource/base.py
server/tilesource/svs.py
server/tilesource/test.py
server/tilesource/tiff.py
server/tilesource/tiff_reader.py
setup.py

Assuming you have the prerequisites, the tilesource can be used without girder.  To facilitate importing it from the source tree, when server is imported without girder, it will still work (though, naturally, you can't import server.models or server.rest).
The plugin_tests/girderless_test.py file shows some access of file sources without girder.

Refactor the tile sources so that they can be used without Girder.

---

plugin.cmake

This commit fixes an error when configuring Girder tests due to EXTERNAL_DATA
referencing nonexistent files. For example:
vagrant@isic-archive:~/girder-build$ cmake --version
cmake version 2.8.12.2
vagrant@isic-archive:~/girder-build$ cmake ../girder
...
-- Including plugin.cmake from "large_image"
CMake Error at /usr/share/cmake-2.8/Modules/ExternalData.cmake:434 (message):
Data file referenced by argument
DATA{/home/vagrant/girder-build/data_src/sample_image.ptif}
corresponds to source tree path
sample_image.ptif
that does not exist as a file (with or without an extension)!
Call Stack (most recent call first):
/usr/share/cmake-2.8/Modules/ExternalData.cmake:255 (_ExternalData_arg)
tests/TestData.cmake:105 (ExternalData_Expand_Arguments)
tests/PythonTests.cmake:153 …

Fix test configuration error

---

plugin_tests/tiles_test.py
server/base.py
server/loadmodelcache.py
server/rest/tiles.py

This reduces fetches by around 6 ms per tile (including cached tiles) in my test environment by eliminating 3 database accesses.  Additionally, an Expires header has been added to encourage short-term browser caching.

Cache loadmodel for token/itemId combinations of getTile.

---

.travis.yml
server/cache_util/cachefactory.py
server/cache_util/memcache.py
server/rest/tiles.py
server/tilesource/__init__.py

Only log 1 out of 250 tile messages.
Also, switch to the new logprint function for print statements.
Resolves issue #66.

Filter cherrypy access logs.

---

.travis.yml
plugin_tests/cached_tiles_test.py
plugin_tests/largeImageSpec.js
plugin_tests/tiles_test.py
server/base.py
server/constants.py
server/models/image_item.py
server/rest/tiles.py
web_client/js/configView.js
web_client/stylesheets/largeImageConfig.styl
web_client/templates/largeImageConfig.jade

Any file that has a TIFF mime type or a file extension that is one of ptif, tif, tiff, svs is checked.  If it can be used as a large_image without a conversion job, it is so marked.
This resolves issue #65.

Automatically import svs and ptif files.

---

.travis.yml
plugin_tests/cached_tiles_test.py
plugin_tests/test_files/girder_worker.cfg
plugin_tests/tiles_test.py
server/base.py
server/models/image_item.py
server/rest/tiles.py
web_client/js/fileList.js

Send a file to the processing job rather than an item.  This allows processing an image from an item that has more than one file.
This change was prompted by trying to convert a file with a name that differed from its containing item in a non-filesystem assetstore.

When a job fails or is canceled, update the large image item to reflect that.

---

plugin_tests/largeImageSpec.js
plugin_tests/tiles_test.py
server/base.py
server/constants.py
server/models/image_item.py
server/rest/tiles.py
server/tilesource/base.py
web_client/js/configView.js
web_client/templates/largeImageConfig.jade

There is a configurable cap on the number of files stored.
We will want to add something to automatically thumbnails as a background job (as a separate PR) when new large images are added.

Store thumbnails in files

---

README.rst
examples/average_color.py
large_image/__init__.py
plugin.cmake
plugin_tests/examples_test.py
plugin_tests/girderless_test.py
setup.py

Show the example as part of the README.  Test the example.
Add a missing module to setup.py.
This has basic information on how to install large_image as a python module (issue #79).

Add an example to show using large_image.

---

.travis.yml
requirements.txt
server/cache_util/__init__.py
server/cache_util/cache.py
server/cache_util/cachefactory.py
server/cache_util/memcache.py
server/models/image_item.py
server/rest/tiles.py
setup.py

This should allow easier deployment to Windows.
This doesn't install pylibmc on Windows (if it happens to be installed, it will be used).
This changes requirements to >= instead of ==, which reduces install thrashing.
Assuming that you've installed OpenSlide and libtiff on Windows, examples/average_color.py now works on Windows.

Don't require memcache. 

---

plugin_tests/common.py
server/tilesource/tiff.py

Before, some file that could be read as svs files would log a warning when the tif reader reported that it wouldn't handle them.

Shift an info message to a debug message so the logs don't contain needless warnings.

---

plugin_tests/cache_test.py
server/cache_util/memcache.py

If memcached had the wrong server address, it would fail.  Now, log the error (throttled) and don't use the cache.  Improve the retry options for the memcached client.  Add a test for the failure conditions.
Allow specifying a list of memcached servers in the config file.

Add guards against memcached failures.

---

server/base.py
server/tilesource/svs.py

When importing via an entrypoint for use in Girder, defer importing fellow plugin values.

---

web_client/js/itemList.js
web_client/stylesheets/itemList.styl

Chrome limits the maximum connectors to a domain to 6.  Girder uses one for getting events, leaving five.  This uses no more than 3 for thumbnails, which leaves some overhead for navigation.  If you navigate between item lists quickly, the connections can still be saturated, as Chrome doesn't cancel the image requests.  We would have to load the image to a hidden element first, and then load it to the visible element to work around that, so that the hidden elements don't vanish on page transitions.
This resolves issue #89.

Limit the number of simultaneous thumbnails that are requested in the itemList.

---

plugin_tests/sources_test.py
server/tilesource/base.py

`convertRegionScale` converts a region from its current units to a different set of units.
`getRegionAtAnotherScale` and `tileIteratorAtAnotherScale` use that function to provide their core features at an alternate scale.
This resolves issue #95.

Added several region scale utility functions.

---

.travis.yml
server/models/image_item.py

This fixes a bug that occurs with the provenance plugin (see Girder PR #1591).

Attach thumbnail files during the upload process.

---

requirements.txt

Restricting cachetools to a version <2.0.0 to resolve the error `ImportError: cannot import name hashkey` while importing or loading the large_image as a girder plugin.
See this [comment](https://github.com/DigitalSlideArchive/HistomicsTK/pull/209#issuecomment-251398686) for more details.

Restrict cachetools to a version <2.0.0

---

plugin_tests/tiles_test.py
server/cache_util/cache.py
server/tilesource/base.py
server/tilesource/pil.py
server/tilesource/svs.py
server/tilesource/test.py
server/tilesource/tiff.py
web_client/js/imageViewerWidget/base.js
web_client/js/imageViewerWidget/leaflet.js
web_client/js/imageViewerWidget/openlayers.js
web_client/js/imageViewerWidget/openseadragon.js

Tiles at the right and bottom edges of images can now be cropped or have unused areas converted all to a specific color.  With appropriate query strings, this allows all viewers to show the edges of images in correct manner.
Some of the tile output code has been moved into the base class to avoid repetition.  As a benefit, the TIFF tilesource can output tiles as PNGs if so desired.
Removed some vestigial code related to class cache keys.

Add edge options for tiles.

---

.travis.yml
plugin_tests/cached_tiles_test.py
server/cache_util/__init__.py
server/cache_util/cache.py
server/cache_util/cachefactory.py
server/tilesource/base.py
server/tilesource/pil.py
server/tilesource/svs.py
server/tilesource/test.py
server/tilesource/tiff.py
server/tilesource/tiff_reader.py

The LRU cache was using the wrong key.
The metaclass cache was using some of the query parameters for the keys, resulting in few cache hits for certain functions (like `getRegion`).  This fixes the cache keys.
Fix some caching issues.
Because of how the `cached` function from cachetools was being applied to class methods, those instantiated classes would never be garbage collected.  This led to leaving files open and exhausting resources.  A new decorator was added called `methodcache` which behaves akin to the `cachetools.cached` decorator, except that it uses class caches, locks, and, optionally, key functions.
This still needs tests.

Fix some caching issues

---

plugin_tests/large_image_test.py
server/rest/large_image.py

If a large image job fails to complete (for instance, because Girder is restarted during the process, or the worker is not running), the item is marked as having a large image in progress, which prevents easily restarting the job.  This endpoint cleans up these states, cancelling any large_image job that is in progress or stuck.

Add an endpoint to clean up items with unfinished large_image jobs.

---

plugin_tests/cached_tiles_test.py
server/cache_util/cache.py
server/cache_util/cachefactory.py
server/tilesource/base.py
server/tilesource/pil.py
server/tilesource/svs.py
server/tilesource/test.py
server/tilesource/tiff.py

Prior to this, each tile source class used a separate cache.  This makes memory use difficult to manage intelligently.  The cache size needs to be set based on available file handles, as that is typically the limiting factor.  TIFF tile sources tend to have one open file handle per level of tiles, so the maximum number of tile sources that can be cached is now set based on that resource if it can be queried.  Moreover, ask to use more file handles if possible (it may not be).
Resolves issue #108.

Better tile source caching.

---

plugin_tests/common.py
plugin_tests/largeImageSpec.js
plugin_tests/large_image_test.py
plugin_tests/tiles_test.py
server/base.py
server/rest/large_image.py
server/rest/tiles.py
web_client/js/configView.js

Move GET system/setting/large_image to GET large_image/settings to keep the namespace cleaner.

Move the settings endpoint.

---

server/tilesource/tiff_reader.py

iOS 10.1 won't load a JPEGs without a JFIF record, even though it should be optional and ignored.

Add JFIF to jpegs from ptifs

---

.travis.yml
requirements.txt
server/tilesource/tiff_reader.py

If we use OpenJPEG 2.1.1 or later, it pulls in libtiff 4.0.6, in which case pylibtiff 0.4 no longer fully works.
Add support for pylibtiff's master branch.  This requires being case-agnostic for certain tiff file methods.

Support libtiff 4.0.6.

---

server/rest/large_image.py
server/tilesource/svs.py

On bad svs images, throw an exception on trying to open them rather then when tiles are read. This helps prevent out-of-memory issues.
Stop running a thumbnail job on errors.

Better error handling on SVS images and on jobs

---

server/tilesource/tiff.py
server/tilesource/tiff_reader.py

Some tif files have multiple images before the tiled data.
Guard against excessively large svs regions.

Be more flexible in the order of tiff directories.

---

server/__init__.py
server/tilesource/base.py
server/tilesource/svs.py
server/tilesource/tiff.py
server/tilesource/tiff_reader.py

For some unknown field [self._tiffFile.GetField(field)](https://github.com/DigitalSlideArchive/large_image/blob/94db0233a21e2a9d466f6d413ece830392c4c0e2/server/tilesource/tiff_reader.py#L228) was throwing a TypeError when run in a distributed fashion on a cluster using Dask.

Add try-except around metadata field load in tiff_reader

---

.travis.yml
plugin_tests/common.py
plugin_tests/girderless_test.py
plugin_tests/tiles_test.py
server/create_tiff.py
server/rest/tiles.py
server/tilesource/base.py
server/tilesource/tiff_reader.py

JFIF headers are now conditional.
See if an iOS is requesting a tile.  If so and we don't have a JFIF header, convert the JPEG to a PIL image and then to a new JPEG rather than adding a JFIF header.
It turns out that the colorspace of a JPEG is complicated, and adding a JFIF header changes it in unexpected ways.  See the comments.  vips (especially latest stable) often generates RGB jpegs (not YCbCr).  If you add a JFIF header to this, the colorspace is implied to be YCbCr, which is wrong.  Therefore, if we want to add a JFIF header, we *must* convert the colorspace, too.
Increase output from the create_tif script to make it easier to debug.   This print the actual command used and always prints non-empty stdout and stderr.

Fix a JPEG vips issue

---

web_client/views/imageViewerWidget/base.js

This is necessary to allow large_image to work in a proxied setting.

Fix a hard-coded api root in the image viewer.

---

web_client/views/imageViewerWidget/base.js
web_client/views/imageViewerWidget/geojs.js
web_client/views/imageViewerWidget/leaflet.js
web_client/views/imageViewerWidget/openlayers.js
web_client/views/imageViewerWidget/openseadragon.js
web_client/views/imageViewerWidget/slideatlas.js

I moved the `g:imageRendered` event into the `render` method of each class.  This is necessary for applications to be able to bind to events on the viewer object itself.  This is used by this commit on HistomicsTK https://github.com/DigitalSlideArchive/HistomicsTK/pull/235/commits/23dee917f43fb98abb97f7e10c12d996c9164098.

Trigger g:imageRendered on every render

---

server/tilesource/base.py

If tile_position is given as a float, the x ranges could also be floats, which doesn't work with range iterators.

Make sure tile ranges are integers.

---

plugin.json
web_client/annotations/convert.js
web_client/annotations/geometry/index.js
web_client/annotations/geometry/rectangle.js
web_client/annotations/index.js
web_client/annotations/rotate.js
web_client/annotations/style.js
web_client/collections/AnnotationCollection.js
web_client/collections/index.js
web_client/index.js
web_client/models/AnnotationModel.js
web_client/models/index.js
web_client/views/imageViewerWidget/base.js
web_client/views/imageViewerWidget/geojs.js

This adds an annotation model and collection.  The model contains a method to convert from our own annotation spec to geojson.  As noted in the code, this can't be done for all annotation element types.  For the moment, it **only** handles rectangle types to support the nuclei segmentation end-to-end demo.
A cleaner solution might be to do the conversion to geojson on the server, but ultimately, we will need to write custom code to render annotations directly as given.  This is just a stop gap solution to render basic types using existing functionality in geojs.

Add code to display annotations as geojson

---

web_client/views/imageViewerWidget/geojs.js

When calling `render` multiple times on a geojs image viewer, the previous `map` object was not getting destroyed.  This resulted in duplicate layers inside the map node.

Remove the geojs viewer before creating a new one

---

server/cache_util/cache.py
server/cache_util/memcache.py

cachetools.hashkey changes between subsequent imports of cachetools.  This means that within a single run of the program we were caching, but between runs the cache was functionally useless.
Also, rename the internal variable for the memcached client to `_client`.  I found `_Cache__data` peculiar with the capitalization and underscores.

Compute the hashkey for tile caches ourselves.

---

.travis.yml
plugin.cmake
plugin_tests/client/annotationSpec.js
plugin_tests/client/geojsAnnotationSpec.js
server/models/annotation.py
web_client/annotations/defaults/index.js
web_client/annotations/defaults/point.js
web_client/annotations/defaults/rectangle.js
web_client/annotations/geojs/common.js
web_client/annotations/geojs/convert.js
web_client/annotations/geojs/coordinates/array.js
web_client/annotations/geojs/coordinates/index.js
web_client/annotations/geojs/coordinates/point.js
web_client/annotations/geojs/index.js
web_client/annotations/geojs/types/index.js
web_client/annotations/geojs/types/point.js
web_client/annotations/geojs/types/polygon.js
web_client/annotations/geojs/types/rectangle.js
web_client/annotations/geometry/index.js
web_client/annotations/geometry/point.js
web_client/annotations/index.js
web_client/annotations/style.js
web_client/collections/ElementCollection.js
web_client/models/AnnotationModel.js
web_client/models/ElementModel.js
web_client/views/imageViewerWidget/base.js
web_client/views/imageViewerWidget/geojs.js

This supports an upcoming PR in HistomicsTK to draw annotation on top of large_image viewers.  This adds a components:
1. New models and collections representing both "annotations" and "elements".  The annotation types are real models that can be sync'ed to the server, but elements are ephemeral objects for storing the individual primitive elements.
2. Modules in `web_client/annotations/geojs` that generate large_image annotations from native geojs annotation objects.
3. A couple of methods and events added to the viewer class itself to trigger "drawing mode".
The CI is current failing at `server_large_image.tiles`.  I assume the failure is also in master because I didn't make any relevant server side changes.

Support drawing annotations with geojs

---

.travis.yml
plugin.cmake
plugin_tests/annotations_test.py
server/models/annotation.py

Use the jsonschema.validate for large annotations is prohibitively slow.  However, since large annotations are largely similar, use that similarity to do some of the validation.  One a test of 338,695 rectangles this changed the validation time from 460 seconds to 5 seconds.
Add some tests for the annotation model.

Speed up annotation validation.

---

.travis.yml
plugin_tests/tiles_test.py
server/rest/tiles.py

The JPEG color-space issue in Mobile Safari now is also present in Safari.  We having nothing better than user-agent scraping to determine if we need to convert to a limited set of color spaces with JFIF headers.  Test against recent Safari and Chrome user agent strings.

Fix JPEG color-space issues in Safari

---

.travis.yml
examples/average_color.py
plugin_tests/cache_test.py
server/cache_util/__init__.py
server/cache_util/cache.py
server/cache_util/cachefactory.py
server/tilesource/base.py

This also delays when the cache is selected, so that the configuration can be altered after large_image is imported.  The average_color example demonstrates how this can be done.

Change how the large_image config settings are accessed.

---

examples/average_color.py
server/cache_util/cachefactory.py

By default, we had been using memcached.  When Girder isn't available, we are likely running in Dask or another environment where memcached is probably not configured properly.  As such, use the python caching backend as the default in those circumstances.  This can always be overridden.
Added a comment on the example showing how to specify the caching method explicitly.

Use python as the default cache when girder isn't available.

---

.travis.yml

This mainly just installs girder_worker in production mode to avoid pip package conflicts.  Eventually, we will probably need to move girder_worker to its own virtualenv.

Update travis to handle recent Girder changes.

---

plugin_tests/cache_test.py
server/cache_util/cache.py
server/cache_util/cachefactory.py

cachetools LRU cache is not thread safe.  If two threads each cause an eviction, it would throw a KeyError and never recover.  Our cache would then fail, functionally breaking large_image until the server was restarted.
This does two things: (1) use a threading lock for the LRU cache, just as we do for memcached.  This should prevent the problem from ever occuring, and (2) guard against such a KeyError, and, if it occurs, return the cache miss value in any case.  If the LRU cache is used in a multithreaded environment without a lock, this guards against the catastrophic failure.
Tests have been added to ensure that multithreaded use works both with and without a cache lock.

Guard against LRU cache issues.

---

plugin_tests/client/annotationSpec.js
plugin_tests/client/geojsSpec.js
web_client/annotations/convert.js
web_client/models/AnnotationModel.js
web_client/views/imageViewerWidget/geojs.js

This propagates geojs mouse events to the large_image viewer widget as custom events
* `g:mouseOverAnnotation`
* `g:mouseOutAnnotation`
* `g:mouseClickAnnotation`
I also added the source annotation model id to the `ElementModel` to disambiguate between different annotations for listeners of the events.
This is missing tests because it coupling with geojs is too strong to permit reasonable mocking.  We need to add infrastructure for integration tests including mocking webgl to get them to run in phantomjs.  I think we should look into doing this in a separate PR.

Add mouse events to geojs drawn annotations

---

.travis.yml
plugin_tests/tiles_test.py
requirements.txt
server/tilesource/tiff_reader.py

This was fixed in the pylibtiff module, but changes to that required some additional changed to our code.

Fix direct access of ptif files with non-ASCII filenames.

---

server/tilesource/base.py

As of PILLOW 4.2.0, JPEG output fails when given an RGBA image.  Before
it saved just the RGB channels.  This works around the issue.

Fix JPEG output for PILLOW 4.2.0.

---

plugin_tests/common.py
plugin_tests/sources_test.py
plugin_tests/tiles_test.py
server/models/image_item.py
server/rest/tiles.py
server/tilesource/base.py
server/tilesource/test.py

For the endpoints that generate images (tiles, thumbnails, regions, associated images), we had supported JPEG and PNG.  This adds TIFF support (only small tiffs as encoded by PIL) and generalizes some of the encoding format testing.  TIFFs can have a compression set, which is one of PIL's string constants.

Add support for TIFF output.

---

plugin_tests/tiles_test.py
server/models/image_item.py
server/rest/tiles.py

On the region, associated image, and thumbnail endpoints, support requesting a content disposition.  The contentDisposition query parameter can be left blank for the existing behavior, or set to 'inline' or 'attachment'.  The filename is absed on the item name with the word 'region', 'thumbnail', or the associated image label appended to it and the appropriate suffix for the mimetype, except that cached thumbnails yield a generate '_largeImageThumbnail' filename.  The filename is encoded in a safe ASCII manner and a UTF-8 manner such that it should work on most clients.
This is based on the small-tif-output branch to leverage some of the testing infrastructure there.

Support content disposition on some endpoints.

---

plugin_tests/large_image_test.py
plugin_tests/tiles_test.py
server/models/image_item.py
server/rest/tiles.py
server/tilesource/base.py

If this option is set and a width and height is specified, then the output image is padded on either the left and right or the top and bottom to make it the specified width and height.  The letterbox or pillarbox color is specified in the fill parameter.

Add fill option for thumbnails and regions.

---

.travis.yml
plugin_tests/client/geojsSpec.js
plugin_tests/common.py
plugin_tests/import_test.py
plugin_tests/large_image_test.py
plugin_tests/tiles_test.py
requirements.txt
scripts/tile_benchmark/benchmark.py
scripts/tile_benchmark/plot_time.py
server/__init__.py
server/cache_util/memcache.py
server/rest/annotation.py
server/rest/tiles.py
server/tilesource/base.py
server/tilesource/test.py
server/tilesource/tiff.py
server/tilesource/tiff_reader.py
setup.py

Make changes necessary to be Python 3 compatible and test on Python 3.
Simplistically, changes are to (a) how some exceptions are handled, (b) to some utility scripts that may not be used, (c) to the test tile source, (d) to some tests.  Prior to this, the plugin was manually tested with Python 3 where it worked in common use cases.  Since this adds CI testing, it is more certain to stay working.

Python 3 support

---

docs/annotations.md
plugin_tests/annotations_test.py
server/models/annotation.py

The group tag is intended to be used for display as a method to perform bulk operations on a subset of related elements contained in an annotation.
Alternatively, this could be called a "layer".  I have a mild preference to group because I don't intend for it to have anything to do with display order, but I could be convinced otherwise.

Add an optional "group" tag to annotation elements

---

server/tilesource/__init__.py

This prevents an unnecessary stack trace from being included in the log message, and keeps stdout cleaner when loading the plugin.

Log a less-severe message if optional tilesources cannot be imported

---

plugin_tests/cached_tiles_test.py
server/cache_util/cache.py

Without this, there is a still the possibility that two threads will attempt to evict the same cache entry, which results in the lru cache breaking.

Always use the cache lock for the class cache.

---

plugin_tests/client/geojsSpec.js
web_client/views/imageViewerWidget/geojs.js

This prevents exhausting webGL contexts.

Show multiple annotations as multiple features instead of multiple layers.

---

server/rest/annotation.py

If an annotation is on an item in a private folder, then browsers fail at downloading the annotation, since the download doesn't pass the authentication token.  If cookies are allowed, the authentication can be gleaned from the cookie and therefore works.

Allow the annotation download endpoint to use cookie authentication.

---

server/tilesource/__init__.py

When a tile source fails to import due to an OSError, treat it much like an ImportError.  This is the error we get when a library is missing but the python module is present.

Handle OSError exceptions on tile sources.

---

plugin_tests/annotations_test.py
plugin_tests/common.py
server/rest/annotation.py

If a recent annotation is on an item that the current user doesn't have permission to read, an `AccessException` was thrown rather than just not including that item.  The ignore-exceptions flag for loading models only applies to `ValidationException`, not `AccessException`.

Fix annotation image access.

---

plugin_tests/client/annotationSpec.js
plugin_tests/client/annotationSpec.yml
web_client/models/AnnotationModel.js

This will be used to simplify some of the logic in HistomicsTK related to managing annotations connected to images.

Add save and destroy methods to AnnotationModel

---

plugin.json

This allows the large_image plugin to work better with other Girder plugins that use geojs.

Unpin geojs verison.

---

plugin_tests/client/annotationSpec.js
web_client/models/AnnotationModel.js

The annotation REST calls don't return the elements of the annotation, so the elements collection was being reset on every save.  This sets the elements property in the response before updating the model.

Fix annotation model save resetting elements

---

plugin_tests/client/annotationSpec.js
web_client/models/AnnotationModel.js

The backbone API for destroying models also removes all event listeners. To avoid regenerating an annotation model (and updating all views that listen to it), this adds a new public that performs the rest request but does not destroy the model object itself.  Very little code is changed here; it is mostly an additional test for the new public method.

Add a method to delete an annotation without unbinding listeners

---

server/tilesource/svs.py

If we have a scale but no magnification, estimate the magnification.

Estimate missing magnification for svs sources.

---

plugin_tests/sources_test.py
server/tilesource/base.py

When the resample option was True (or one of the PIL.Image.NEAREST, LANCZOS, BILINEAR, or BICUBIC), there were some instances where resampling would fail due to a float/integer requirement mismatch.  Further, before, we would resample and scale AFTER the tile was computed and generated, which yielded tiles that were not the requested size.  For instance, asking for a tile of 1024 pixels square and a magnification that is 0.625 of a value of an existing level would result in tiles that were 640 square.  Now, there are fewer tiles but they are the requested size.  This also changes when no tile size is explicitly requested -- the tiles are now the size of the tiles at an native magnification.
This addresses issue #226.

Fix resample option for the tile iterator.

---

.travis.yml
plugin_tests/annotations_test.py
plugin_tests/client/annotationSpec.js
server/models/annotation.py
server/rest/annotation.py
web_client/models/AnnotationModel.js

For annotations with a large number of elements, it shouldn't be necessary to pass the elements just to change the annotation name or move it to another id.  This fixes the javascript model to allow updating the name of an annotation without requiring that all of the elements are loaded (also allowing changing the name of an annotation with paged elements).
Added tests for creating updating annotations.  Also, refactored the annotation tests to avoid uploading images in most cases; this speeds up the tests by 15 seconds or so on my local machine.

Allow updating annotations without passing elements.

---

.travis.yml

Use the cache better for our build-on-demand libraries.  This avoids redownloading and much of the rebuilding process for our custom built libraries.
Update codecov reporting based on recent girder build changes.

Improve travis cache use and fix coverage reporting.

---

plugin_tests/client/geojsSpec.js
web_client/views/imageViewerWidget/geojs.js

This is meant to be used for reactive applications to make a single annotation (or element) prominent on the display.  I don't know if "highlight" is the word, but I couldn't think of anything better.
There are performance issues when dealing with a large number of elements, so the opacity toggling behavior is disabled for large annotations.  I'm sure there are a number of performance enhancements we could make if it becomes an issue.

Add a method to the geojs viewer to highlight drawn annotations

---

server/tilesource/__init__.py

With updates to flake8, the dynamically generated `__all__` reference can pass style tests if it is restructured so that the partial function is defined before `__all__`.

Fix style involving __all__.

---

plugin_tests/annotations_test.py
server/models/annotation.py
server/rest/annotation.py

This changes the super class of the annotation model from `Model` to `AccessControlledModel`.  It will allow us to use all of the access control functionality of Girder's permission model for annotations instead of coding ad hoc implementations as needed.  The main backwards incompatible change here is that the `load` method now does permission checking.
There is a schema migration that occurs on load.  It will generate an access control list identical to the folder containing the item the annotation is attached to plus it will give the annotation creator admin access.  I believe this will allow a smooth migration for annotations that currently exist (in HistomicsTK at least).

Add access control lists to the annotation model

---

plugin_tests/tiles_test.py
server/base.py

When an item is copied, the `item['largeImage']['fileId']` reference still referred to the file in the original item.
Fixes #245.

Adjust file references when copying a large image.

---

.travis.yml
README.rst
plugin_tests/annotations_test.py
plugin_tests/client/annotationSpec.js
server/base.py
server/constants.py
server/models/annotation.py
server/models/annotationelement.py
server/rest/annotation.py
web_client/templates/largeImageConfig.pug
web_client/views/configView.js

This exposes a setting on the plugin settings page to toggle whether history is saved.  It defaults to on.
If history is turned on, old versions of annotations are maintained in the annotation and annotationelement mongo collections.  There is a strictly monotonic version number for all annotations. 
When an annotation is updated, the old elements are retained, and the old version of the annotation is saved with an _active=false marker.  These old versions have an _annotationId to reference the original annotation.
Historic versions can be listed via a new endpoint.  Historic versions can be fetched via the original annotation id and version number or via the historic record _id (all with appropriate user level authentication).  A revert endpoint allows switching to previous versions of …

Add annotation history.

---

plugin_tests/import_test.py
server/tilesource/tiff.py
server/tilesource/tiff_reader.py

When the version of libtiff doesn't match a known version in the python libtiff module and large_image is in a virtual environment, the tiff tile source throws a ValueError instead of an ImportError.  Switch to an ImportError and log a message to help resolve the problem.

Add a better failure condition for libtiff.

---

plugin_tests/source_mapnik_test.py
plugin_tests/sources_test.py
plugin_tests/tiles_test.py
server/cache_util/cache.py
server/models/image_item.py
server/rest/tiles.py
server/tilesource/base.py
server/tilesource/mapniksource.py

Internally, `getRegion` can now specify width and height in different units than the edges of a region.  This allows a 1-pixel square region to be specified with the left and top specified via non-pixel units. 
`getPixel` gets a 1x1 pixel region and returns a tuple of the channel values as an object.  Subclasses of the tile source can augment this with additional information (such as band data).
For the mapnik source, this also returns band information at the pixel.
Also, the generated hash key for methods in cached classes now includes the class hash key.  Without this change, either the methodcache decorators need more parameters or a change in the source may use a cached tile (for instance, just changing the mapnik/gdal style).

Add a getPixel method and rest endpoint.

---

server/rest/large_image.py
web_client/views/configView.js

We use `ConfigView.getSettings` in a few places to get settings.  Allow all of the settings to be fetched from the large_image/settings endpoint.  If we really need an admin-only setting, we will need to add a second method to get those settings.
This fixes a bug introduced in PR #250 where a non-admin user can't view a large image in Girder because we fail to obtain the setting for which viewer should be shown.

Allow all settings to be fetched.

---

.circleci/config.yml
devops/mapnik_py35/Dockerfile

Something in the environment changed such that we must explicitly set the locale.
Also, parallelize downloading test files.

Fix circle docker test.

---

plugin_tests/source_mapnik_test.py
server/tilesource/mapniksource.py
server/tilesource/pil.py

The projection parameter is the projection of the tiles.  It can be useful to have a different projection for the units, so allow the units to include a few enumerated values ('wgs84', '4326') or any string that starts with 'epsg:' or 'proj4:' (all case insensitive).  In these cases, convert from the specified units to pixels or the specified tile projection.
This also changes `toNativePixelCoordinates` to round to the nearest coordinates by default.  This resolves some differences in pixel values that were showing in tests.
There is a change in computing the class cache hashing string.  Before `MapnikTileSource(file, projection)` got different results than `MapnikTileSource(file, projection=projection)`, whereas it should not.  The change affects the mapnik and pil tile sources.

Allow units to specify any proj4 projection.

---

web_client/views/imageViewerWidget/geojs.js

Calling `viewer.draw()` results in updating the drawing information.  Frequently when highlighting annotations, multiple such calls are made in a row.  Ideally, only one `draw()` call should be made per combined set of updates.  These can be aggregated by scheduling the draw for the next animation frame using the geojs scheduler for that (which prevents duplicates).
Also, allocate arrays in a single step as they are created.

Reduce number of draw calls when highlighting annotations.

---

plugin_tests/common.py
plugin_tests/tiles_test.py
server/loadmodelcache.py

In Girder PR #2274, instead of using `getCurrentToken` to cache that cookies are being used, the cherrypy.request attr `girderAllowCookie` is used.  We cache loading models to avoid one or more database lookups per tile request, and this change broke that caching.

Track girder cache changes.

---

plugin.json

The latest version has much faster line updates, which is useful for annotation rendering.

Upgrade geojs.

---

plugin_tests/sources_test.py
server/tilesource/base.py
server/tilesource/tiff.py

Before, if this returned the base level, no scale value was included (the scale is 1 in this case).
Also, reframe how magnification is calculated for the tiff tile source so if it is set but 0 we still replace it with a calculated value.

Always report a scale when getting a level magnification.

---

plugin_tests/client/geojsSpec.js
web_client/views/imageViewerWidget/geojs.js

This commit provides a more efficient mechanism for setting the opacity
globally for all annotations than the "highlightAnnotation" code path
which requires looping through each feature.  This will be used to
implement the following feature request on HistomicsTK:
https://github.com/DigitalSlideArchive/HistomicsTK/issues/458

Add a method to set the opacity of the annotation layer

---

server/__init__.py

If girder is installed but requirements of large_image are not, the plugin would report as enabled but not be functional.  This checks if girder is available, and, if so, allows girder to report errors.
Eventually, it will be nice to separate large_image without girder from the necessary girder parts to make this easier to manage.  For now, this should make diagnosis easier.
As a simple test, when everything works under girder, uninstall a required module (cachetools, for instance), and restart girder.  Before, no error was reported.  With this change, the missing module is reported.

Allow girder to show load errors in more cases.

---

server/tilesource/tiff_reader.py

GeoTIFFs always print warning messages like "TIFFReadDirectory: Warning, Unknown field with tag 34736 (0x87b0) encountered.".  These are expected, and therefore not useful, so suppress them.

Suppress TIFF warnings.

---

plugin.json
plugin_tests/client/geojsSpec.js
web_client/views/imageViewerWidget/geojs.js

This also works around a potential issue destroying a geojs map.
If the remote worker is not enabled, we need to explicitly include d3.  It is probably best to do this anyway, since the remove worker only has d3 as a side effect of including vega.

Add an option to have a scale widget.

---

server/tilesource/svs.py

This change allows a few more files to be opened by the svs tilesource.  For instance, if you import the .mrxs named file from a group of mrxs files, this will allow them to be displayed.

Handle KeyError when trying to get openslide properties.

---

plugin_tests/annotations_test.py
server/models/annotation.py
server/models/annotationelement.py
server/rest/annotation.py

To support the use case of grouping annotations when listing them on the client, this maintains a denormalized list of "groups" on the annotation object inside the database.  This property is calculated on demand for annotations that existed before this change; otherwise, it is added/modified automatically on `annotation.save(...)`.
I would have preferred to keep this code entirely on the model layer, but the only place to inject the migration behavior for the listing endpoint is in the `find` method.  This however returns a mongo cursor rather than a normal iterator and would be difficult to override.

Return a list of element groups with annotation endpoints

---

plugin_tests/girderless_test.py
server/tilesource/svs.py

For SVS tile sources, we check if each level is a power of two of the base level.  Using `abs(modf(log2ratio)[0])` to get the mantissa, this could sometimes return a failure (such as with 45808 and 11456), since the mantissa was near to 1 rather than near to zero.  Using `round` to get the mantissa is better.

Improve level power-of-two detection.

---

server/models/annotation.py

Before, we wrote (inserted) an `annotation` to the mongo collection, then wrote the set of `annotationelement`s.  If an item's annotations were listed before this finished, the new annotation would be included in the list.  Requesting the annotation could return partial results for the annotation elements.  By saving the annotation after the annotation elements, this problem is avoided.

Change the order a new annotation and its element are stored.

---

plugin.cmake
plugin_tests/client/annotationListSpec.js
web_client/collections/AnnotationCollection.js
web_client/collections/ElementCollection.js
web_client/models/AnnotationModel.js
web_client/stylesheets/annotationListWidget.styl
web_client/templates/annotationListWidget.pug
web_client/templates/imageViewerSelectWidget.pug
web_client/views/annotationListWidget.js
web_client/views/imageViewerSelectWidget.js
web_client/views/imageViewerWidget/base.js
web_client/views/imageViewerWidget/geojs.js

This adds a simple table displaying annotations attached to the current item.  The user can click on them to view them if using the GeoJS viewer (the only one capable of rendering annotations at the moment).  The delete and access buttons are only visible if the user has the necessary permissions.

Add an annotation list widget to the item page

---

plugin_tests/annotations_test.py
server/rest/annotation.py

This parameter is required for compatibility with Girder's AccessWidget.

Add a public param to PUT /annotations/:id/access

---

plugin_tests/client/annotationSpec.js
web_client/models/AnnotationModel.js

Girder uses this method in several places to inject document names into generic widgets.

Add a name method to AnnotationModel

---

plugin_tests/cached_tiles_test.py
plugin_tests/common.py
server/cache_util/__init__.py
server/cache_util/cache.py
server/rest/large_image.py

Tweak the calculation of the tile source cache size based on actual experience.

Add tools for reporting on and clearing the cache.

---

server/base.py

If a file with this extension is imported it will automatically be tested to see if it can be used as a large image.

Add mrxs to the list of extensions.

---

.travis.yml
plugin.cmake
plugin_tests/common.py
plugin_tests/fuse_off_test.py
plugin_tests/fuse_on_test.py
server/base.py
server/tilesource/base.py

The direct path will be used on the filesystem assetstore unless the Girder item has a file besides the large_item file and an originating file.

Use the Girder FUSE mount.

---

plugin_tests/source_mapnik_test.py
server/tilesource/mapniksource.py

If a stereographic projection is used, the method of calculating the level 0 size was flawed.  This prevents an exception from being thrown, but isn't particularly general.
Short of known the range and domain of each projection, there probably isn't a general solution.  When this proves to be insufficient, we'll need to allow passing in the valid range.

Add a unitsPerPixel option.

---

.travis.yml
plugin_tests/client/geojsAnnotationSpec.js
web_client/annotations/geojs/types/rectangle.js

If, for instance, in HistomicsTK, you select a region by clicking and dragging, it works fine.  But if you select the same region by clicking opposite corners of the rectangle, the rectangle is deformed.  Specifically, this computes center, width, and height of a rectangle, and made two assumptions: that the first point was always a specific corner, and that the points always were in the same winding order.  Neither of these assumptions are always correct.  This avoids making assumptions, but otherwise maintains the same process.

Fix an issue when drawing selection rectangles.

---

server/cache_util/cachefactory.py

If config is not set, then we aren't running in Girder, in which case use a smaller memory portion for caches.  A common use case is Dask with multiple workers, and the ordinary default would ideally be divided by the maximum number of workers on any given machine.
Also, double the expected memory per image tile by default.

Change a few cache defaults.

---

web_client/views/imageViewerWidget/geojs.js

This will allow downstream code to detect event modifiers (shift, ctrl, right click, etc.) in their handlers.

Pass the geojs event object to annotation events

---

server/tilesource/svs.py

If there is a bad image inside of a svs or tiff file, it can throw an error and prevent reading the entire file.  This guards against this problem withing the openslide reader.
Pylibtiff also needs a guard, but that has been committed to that repo.

Guard against exceptions when fetching associated images.

---

server/models/annotationelement.py
server/rest/annotation.py
setup.py
web_client/models/AnnotationModel.js

Instead of returning annotations as a monolithic response, yield from the database as the elements are read.  This reduces memory and speeds up the response.  For a large annotation set (~0.3 million polygons), this reduced output time by a factor of 3.
Use the ujson library for serializing annotation elements.  This takes 2/3 the time of the default json library for polygons.
Strip trailing .0 from floats that have integer values to reduce output size when it can be done trivially.  Javascript treats the results the same.

Return annotations via yielding elements

---

plugin_tests/client/geojsSpec.js
web_client/models/AnnotationModel.js
web_client/views/imageViewerWidget/geojs.js

If the refresh flag is set, annotations will be fetched even if present.  This is intended to resolve an issue with reloading annotations in HistomicsTK.
Also, added a flag to `setView` to update the bounds without fetching.

Add a refresh flag to the annotation model.

---

plugin_tests/source_mapnik_test.py
server/tilesource/mapniksource.py

When styling a mapnik tile source, `palette` is the name of a palettable class.  It can now also be an array of colors, for instance `["#0000ff", "white", "#ff0000"]`.

Allow a color array to be passed in place of a palette name.

---

plugin_tests/annotations_test.py
server/rest/annotation.py

We avoid loading annotation elements into memory when we don't need to work with them, but we were saving the entire annotation document when changing access permissions.  This functionally deleted the elements.  Rather, update the annotation record to update the acl.  This is both more efficient and avoids the problem.
This fixes https://github.com/DigitalSlideArchive/HistomicsTK/issues/537

Fix clobbering annotation elements when changing access.

---

plugin_tests/annotations_test.py
server/rest/annotation.py

Add an endpoint get all annotations on an item and an endpoint to add a list of annotations to an item.  This help transfer annotations between girder instances.

Add item annotation endpoints.

---

.travis.yml
devops/mapnik_py35/Dockerfile

The path we had been using no longer works.  This should be the more canonical path.
Also, update the Dockerfile used by the circle-ci tests to use the Girder 2.x-maintenance branch.

Change the download path to vips.

---

plugin_tests/source_mapnik_test.py
server/cache_util/cache.py
server/tilesource/mapniksource.py
server/tilesource/pil.py

The default for bands has changed.  This fixes rendering palettized gdal sources, as transparency is now supported for palettized data.  For data with red, green, blue, or gray channels, render them using the band metadata maximum and minimum metadata if either the maximum or minimum are out of the range [0, 255], otherwise use [0, 255] as the range.  If rendering default red, green, blue, gray, or palettized channel(s) and an alpha band exists, render that as well.
The original rendering can be obtained by specifying `style={"band":-1}`.  Bands can be specified by index or color interpretation.  `nodata` is supported.  Multiple bands can be composited by giving a list of bands to the style, e.g., `style={"bands":[{"band":"red", "nodata":0, "palette":["#000000","#ff0000"], …

Allow multiband styles for gdal sources.

---

server/tilesource/pil.py

mrxs files can look like very low res JPEG files, but opening them that way isn't useful.  This excludes them from being opened via the PIL tile source.

Don't open mrxs files via PIL.

---

server/tilesource/tiff_reader.py

When trying to parse a file with the tiff reader, if it parses somewhat but reports no samples per pixel, the reader was raising a `TypeError`.  This caused Girder to fail to move to the next possible tile source.

Harden the tiff reader.

---

plugin_tests/client/imageViewerSpec.js
server/base.py
server/models/image_item.py
web_client/views/fileList.js

If you deleted a largeImage file from the item, the large image would still be displayed.  When the file is deleted, this appropriately removes the large image information.  On the web client, it will rerender the page to remove the viewer, too.

Handle deleting a file from a largeImage item.

---

plugin_tests/fuse_off_test.py
plugin_tests/fuse_on_test.py
server/loadmodelcache.py
server/tilesource/base.py

Also fix a comparison that checked if a string was equal to an objectId (which would fail).

Use the loadModel cache on anonymous accesses, too.

---

server/tilesource/base.py

This always uses the fuse path to access mrxs files if possible, as mrxs files always have adjacent files.  Fixes https://github.com/DigitalSlideArchive/HistomicsTK/issues/579.

Mirax files always have adjacent files.

---

plugin_tests/large_image_test.py
plugin_tests/tiles_test.py
server/models/image_item.py
server/rest/large_image.py

This uses the same caching methods as thumbnails.  Deleting all cached thumbnails will delete cached associated images, though the spec parameter can also be used to target more specific cached images.  There are new endpoints `GET large_image/associated_images` and `DELETE large_image/associated_images` to efficiently report and delete just cached associated images.

Cache associated image retrieval.

---

server/rest/tiles.py

The history here is that we deploy large_image into some environments
in which the access.public decorator has its behavior changed to be
equivalent to access.token, and the optimization used to facilitate
cookie-based access to the tile endpoint does not work in that condition.
By also removing access.public and explicitly disabling the access
level checking, we can make this optimization work in that environment.

More robust access optimization for tile download route

---

plugin_tests/sources_test.py
server/tilesource/base.py

Prior to this, `resample` in the `tileIterator` defaulted to `False`.  This led to surprising results when a magnification was asked for that was not a native tile level in a source image, such as svs files where not all levels are present.
When tiles need to be resampled, make the `tile['magnification']` value reflect the output magnification and the the `tile['tile_magnification']` value be the magnification before resampling.
Improve some documentation for the `resample` parameter.

Change the tileIterator resample default to True.

---

plugin.json
plugin_tests/client/annotationListSpec.js
plugin_tests/client/geojsSpec.js
plugin_tests/client/imageViewerSpec.js

GeoJS 0.19.1 changed the name of some mocking utility functions.

Update to work with geojs 0.19.1.

---

web_client/annotations/style.js

A significant fraction of the time preparing annotation with many elements is spent calling tinycolor.  Since most elements will share colors, memoizing this speeds it up substantially.

Memoize annotation style color.

---

large_image/__init__.py

By doing this, other code that sets config in this manner and doesn't use girder should be able to switch to the pypi releases or use from current master.
For instance, instead of doing 
```
large_image.cache_util.cachefactory.defaultConfig['cache_backend'] = 'memcached'
```
code can do
```
large_image.config.setConfig('cache_backend', 'memcached')
```
This will now work on both the master branch and the pypi deployments made by the girder-3 branch.

Expose setConfig at large_image.config.setConfig.

---

.travis.yml
plugin_tests/source_mapnik_test.py
server/tilesource/mapniksource.py

Girder Worker 0.6 will break our usage, so pin to v0.5.1.
Note that the girder-3 branch doesn't have this issue.
Also, update to pyproj 2.0 (we either have to update or pin or CI is broken).

Pin girder worker

---

server/models/image_item.py
server/rest/large_image.py
server/tilesource/svs.py
setup.py

This also allows caching associated images as part of the thumbnail generation job.
Before, when more than one thumbnail specification was given, each specification was processed in turn.  Now, all specifications for each image are processed to avoid having to load the image multiple times.

Thread parallelize thumbnail generation.

---

plugin_tests/client/largeImageSpec.js
plugin_tests/large_image_test.py
server/base.py
server/constants.py
server/rest/large_image.py
setup.py
web_client/templates/largeImageConfig.pug
web_client/views/configView.js
web_client/views/itemList.js

This allows, for instance, only showing label images to logged in users.

Add a setting to show different associated images to anonymous users.

---

web_client/views/imageViewerWidget/geojs.js

Debounce render events by aligning to animation frames.  Don't update selections if they haven't changed.

Speed up rendering annotations.

---

server/cache_util/cache.py
server/tilesource/mapniksource.py

We had been using Python's hash() function to reduce a long key to a shorter key for the cache keys in memcached.  However, Python 2 can be optionally set to use a random or non-standard seed for hash(), and Python 3 uses a random seed for hash() by default.  This means that subsequent runs of a program would not utilize the memcached tile cache from previous runs.
Also, improve the default class key for the mapnik tile source, as this allows easier programmatic reuse of tiles.

Use a consistent hash function for long keys and memcached.

---

server/models/annotation.py

When we find annotations, we default to sorting by most recently updated.  This needs an index when there are enough annotations.

Add the updated field to those that should be indexed in mongo.

---

server/tilesource/tiff.py
server/tilesource/tiff_reader.py

This allows us to read some additional tiffs that are not read by the openslider reader.  For instance, an uncompressed OME Tiff's first frame can be read with this change.

Support some uncompressed tiled tiffs via the tiff reader.

---

.circleci/config.yml
.travis.yml
server/rest/tiles.py
server/tilesource/base.py
web_client/views/annotationListWidget.js

When using the Girder viewer, turning on an annotation would always try to page the results by detail level, even when it should not have.

Annotation small details

---

plugin_tests/annotations_test.py
plugin_tests/client/annotationListSpec.js
plugin_tests/client/sample_annotation.json
plugin_tests/source_mapnik_test.py
server/rest/annotation.py
web_client/templates/annotationListWidget.pug
web_client/views/annotationListWidget.js

This adds four controls on the Annotations section title bar: delete, upload, download, and set access level.

Add some annotation controls to items

---

sources/mapnik/setup.py

We use the `always_xy` flag to ensure consist transforms, and this was added in pyproj 2.2.0.

Correct the pyproj minimum version.

---

server/base.py

Since we use a resource path to some large images, renaming a collection or user will change that path.  As such, we need to invalidate the loadmodel cache when that happens.

Invalidate the loadmodel cache when collections or users are changed.

---

server/models/annotationelement.py
server/rest/annotation.py
web_client/models/AnnotationModel.js
web_client/views/imageViewerWidget/geojs.js

When there are too many elements to load all of them due to complexity, this loads all element centroids (actually the center of their bounding boxes) along with the element size (the diagonal of the bounding box).  If an element has not been loaded, a circle is shown at the centroid with an adjusted diameter that is related to the bounding box size.
This doesn't actually load *all* element centroids, just the first 2,000,000.  This number should be empirically determined based on GPU memory (something like half the memory divided by (16 or 17) * 4 * vpf would be appropriate).
Other improvements would be to (a) add hover events for centroid elements -- we know the ID and the center position, but not much else, (b) determine if any point's radius would be bigger than the webgl maximum …

Add an option to get centroids.

---

requirements-dev.txt
setup.cfg

The format for how source files are mentioned changed between version 2.5.x and 2.6; follow along.

Unpin pytest-cov.

---

sources/mapnik/large_image_source_mapnik/__init__.py

gdal reports "not recognized as a supported file format", but this is done by raising a RuntimeError.

Guard against GDAL throwing a runtime error on open.

---

server/rest/annotation.py

When the database is slow, getting and putting annotations can time out.  This increase the time limit.  It would be better to speed up the database, but until that is done, this at least allows it to function.

Increase the response time limit.

---

sources/tiff/large_image_source_tiff/__init__.py

Before, if there are multiple tiled images (each possibly with a pyramid of smaller images), the image with the largest tiles was selected.  Now, the image with the largest tiles that are not the whole image are selected.
Also, this adds parsing for Optrascan metadata stored as xml within the pixel space of an uncompressed image.

Improve handling tiff files with multiple tiled images

---

.travis.yml
server/tilesource/tiff.py
server/tilesource/tiff_reader.py

For a Tiled TIFF that is not in the standard top-left orientation, this uses a less-efficient code path that may composite up to four tiles to get a conceptual tile at the location desired.
This is a backport of #390.  Tests are done on the master branch.

Handle different tiff orientations.

---

.gitignore
girder/girder_large_image/__init__.py
girder/setup.py
girder/test_girder/girder_utilities.py
girder/test_girder/test_large_image.py
girder/test_girder/test_tiles_rest.py
girder/test_girder/test_web_client.py
girder_annotation/test_annotation/girder_utilities.py
girder_annotation/test_annotation/test_annotations.py
girder_annotation/test_annotation/test_annotations_rest.py
girder_annotation/test_annotation/test_web_client.py
requirements-dev.txt

Because the Girder pytest plugin fixture reinstantiates singletons, it is necessary to unbind and rebind events from models.

Follow girder 3.0.4 testing changes.

---

sources/mapnik/large_image_source_mapnik/__init__.py
test/test_source_mapnik.py

When a band is specified without a scheme or a palette, use linear and greyscale.
Closes #376.

Change the mapnik style defaults.

---

sources/openslide/large_image_source_openslide/__init__.py

Fix sorting so it can't use a dictionary in the comparison.

---

server/tilesource/base.py
server/tilesource/test.py

Otherwise, PIL 7 fails.
This only applies to the 2.x-maintenance branch.

Remove PIL version check.

---

plugin_tests/sources_test.py
server/constants.py
server/models/image_item.py
server/rest/tiles.py
server/tilesource/base.py
server/tilesource/mapniksource.py
server/tilesource/ometiff.py
server/tilesource/openjpeg.py
server/tilesource/pil.py
server/tilesource/svs.py
server/tilesource/test.py
server/tilesource/tiff.py
server/tilesource/tiff_reader.py
setup.py

Style option 2.x

---

girder/girder_large_image/models/image_item.py

Since the output directory is removed, removing the file can result in a failure in girder_worker_utils.

Don't delete the task output file.

---

girder/girder_large_image/girder_tilesource.py
girder/test_girder/test_large_image.py

When handling paths of file formats with adjacent files that have been imported, use the local path in preference to the mounted path.

Improve handling imported formats with adjacent files.

---

girder/girder_large_image/web_client/views/imageViewerWidget/geojs.js
girder/girder_large_image/web_client/views/imageViewerWidget/slideatlas.js

On the Girder plugin, we need to use the webroot public path to reference packages stored alongside the girder plugin javascript.

Use the web root public path where appropriate.

---

.circleci/config.yml
.dockerignore
.travis.yml
Dockerfile
girder/setup.py
girder_annotation/setup.py
requirements-dev.txt
setup.py
sources/dummy/setup.py
sources/gdal/setup.py
sources/mapnik/setup.py
sources/nd2/setup.py
sources/ometiff/setup.py
sources/openjpeg/setup.py
sources/openslide/setup.py
sources/pil/setup.py
sources/test/setup.py
sources/tiff/setup.py
tasks/setup.py
tox.ini

This also publishes the tox-and-node docker image.

Test with Python 3.8.

---

girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/test_annotation/test_annotations.py

If a user or group has been removed from the system such that it still exists in an access control list, when the access list is read, Girder prunes the missing users and groups and writes back the access list. 
However, for annotations, this could cause a save with an empty array of elements, effectively removing the elements from the annotation.  This, instead, updates the annotation's access list.

Fix an issue with annotation permissions.

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/__init__.py
girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/girder_large_image_annotation/rest/annotation.py
girder_annotation/girder_large_image_annotation/web_client/views/itemList.js
girder_annotation/test_annotation/test_annotations.py
girder_annotation/test_annotation/test_annotations_rest.py

We were doing on-demand migrations to have ACLs and groups in annotation models, since originally we didn't have these.  Not having them prevents certain optimizations, like getting count of total number of annotations as a header when listing annotations.  Although there could be a slow one-time response to this, and, without appropriate indices, the initial start-up will be slower, the benefits outweigh this cost.
As a benefit of this, for instance, the query to display the number of annotations in the image list can return much less data, since it can get the number of annotations from the header.

Do a migration of database values on start.

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/girder_large_image_annotation/models/annotationelement.py
girder_annotation/girder_large_image_annotation/rest/annotation.py
girder_annotation/test_annotation/test_annotations_rest.py

If you are tracking history, annotations can build up excessively.  This provides an informational endpoint and a delete endpoint to show how many old annotations there are and to remove them and compact the database.

Add functions and endpoints to remove old annotations.

---

large_image/tilesource/base.py
sources/nd2/large_image_source_nd2/__init__.py
sources/ometiff/large_image_source_ometiff/__init__.py
test/test_source_nd2.py
test/test_source_ometiff.py

Any tile source that exposes frames will have a frames list.  This list now will always contain Frame and Index values, and, where appropriate IndexC, IndexT, IndexZ, IndexXY values.  The top-level metadata will always have IndexRange and IndexStride entries.  When known, the top-level metadata will have channels and channelmap entries with channel names.

Standardize frame metadata.

---

CHANGELOG.md
setup.py

Github security claims there is a security issue with Pillow before 6.2.2.

Require a newer version of Pillow.

---

girder/setup.py

Girder master will soon only support Python >= 3.6.  As such, for < 3.6 testing, use an appropriate version of Girder.  This may fail when we require newer features, at which point new support for Girder on old python version will cease.

Handle changes to Girder master.

---

large_image/tilesource/base.py
test/test_source_gdal.py

Due to a typo, if multiple styled tiles were requested concurrently, the wrong tile could be obtained from cache.

Fix a threading issue with multiple styled tiles

---

large_image/tilesource/base.py
test/test_source_tiff.py

Set tile_mm_x/y to the unscaled values and mm_x/y to the scaled values.
Fixes #439.

When scaling, adjust reported mm_x/y.

---

girder/girder_large_image/models/image_item.py
girder/girder_large_image/rest/tiles.py
girder/test_girder/test_tiles_rest.py
large_image/tilesource/base.py
sources/gdal/large_image_source_gdal/__init__.py
sources/nd2/large_image_source_nd2/__init__.py
sources/ometiff/large_image_source_ometiff/__init__.py
sources/openjpeg/large_image_source_openjpeg/__init__.py
sources/openslide/large_image_source_openslide/__init__.py
sources/pil/large_image_source_pil/__init__.py
sources/test/large_image_source_test/__init__.py
sources/tiff/large_image_source_tiff/__init__.py
test/test_source_gdal.py
test/test_source_nd2.py
test/test_source_ometiff.py
test/test_source_openjpeg.py
test/test_source_openslide.py
test/test_source_pil.py
test/test_source_tiff.py

This also shifts some extraneous source-specific metadata to that location (for instance, nd2 files reported a lot of nd2 specific information in the general metadata).

Report internal metadata as a separate method and endpoint.

---

sources/ometiff/large_image_source_ometiff/__init__.py
sources/tiff/large_image_source_tiff/__init__.py
test/test_source_ometiff.py

Some OME Tiff files have one main record any everything else as a Plane.
Also, for TIFFs with mostly missing directories (such as OME Tiffs with only a tiled maximal resolution layer), synthesize intermediate empty directories to avoid excessive memory use.

Read more OME Tiff files.

---

sources/nd2/large_image_source_nd2/__init__.py
test/test_source_nd2.py

All of the example nd2 files that I've seen don't actually store the data in a pyramidal format.  As such, larger tiles are more efficient.

Change the default tile size.

---

girder_annotation/girder_large_image_annotation/rest/annotation.py
girder_annotation/girder_large_image_annotation/web_client/views/itemList.js

When we show an item list in Girder with annotations, we show a badge on each thumbnail indicating how many annotations are on that large image.  Before, this made one REST request per call without any sort of throttling, which could effectively block navigation until enough of the calls were resolved.  This gets all needed values in a single REST request.

Speed up item list annotation counts.

---

large_image/cache_util/cache.py

There is an issue that was introduced in 8.1.0 that throws an error when file descriptor numbers are large (see https://github.com/cherrypy/cheroot/issues/249).  We can't pin cheroot to an older version, as that breaks support for modern python versions.

Work around a file descriptor issue in cheroot.

---

setup.py
sources/dummy/setup.py
sources/gdal/setup.py
sources/mapnik/setup.py
sources/nd2/setup.py
sources/ometiff/setup.py
sources/openjpeg/setup.py
sources/openslide/setup.py
sources/pil/setup.py
sources/test/setup.py
sources/tiff/setup.py
tasks/setup.py

This will be needed when support of specific python versions is dropped.

Ensure all packages have python_requires.

---

sources/bioformats/large_image_source_bioformats/__init__.py

Don't use bioformats on jpegs.

Catch additional java errors.

---

Dockerfile
sources/openslide/large_image_source_openslide/__init__.py
sources/openslide/setup.py

Openslide only exposes associated images from Aperio if they have an ImageDescription with their name.  For Python>3.6, if you also have appropriate tiff libraries installed (for instance, from the tiff tile source), this will expose label and macro images based on other indicators.
For Hamamatsu files, only the macro image is exposed.  There is another image that can be present, but this is the non-empty region map.

Show additional associated image for some openslides.

---

.circleci/config.yml
tox.ini

This might reduce the memory footprint in Circle-CI.

Run pytest in forked mode in Circle-ci.

---

girder/test_girder/test_large_image.py

There is a condition where a file can be added to a test assetstore while it is being removed that causes a failure.  This should reduce that chance.

Attempt to harden tests.

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/web_client/annotations/convert.js
girder_annotation/girder_large_image_annotation/web_client/annotations/geometry/point.js
girder_annotation/girder_large_image_annotation/web_client/annotations/geometry/polyline.js
girder_annotation/girder_large_image_annotation/web_client/annotations/geometry/rectangle.js
girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js
girder_annotation/test_annotation/web_client_specs/annotationSpec.js
girder_annotation/test_annotation/web_client_specs/geojsAnnotationSpec.js
girder_annotation/test_annotation/web_client_specs/geojsSpec.js

This adds the annotationType to the result so it can be directly passed to the annotation layer's geojson method.
Add hideAnnotation function.  This hides a single annotation efficiently.  It useful when editing annotations.

Improve annotation conversion

---

sources/bioformats/large_image_source_bioformats/__init__.py
tox.ini

If a file cannot be read by bioformats, only log to debug level.

Reduce severity of bioformats warnings.

---

CHANGELOG.md
sources/bioformats/large_image_source_bioformats/__init__.py

Before this change, from the repl, issuing commands like:
```
import large_image
ts = large_image.getTileSource('/some/bioformats/file')
```
and then exiting would hang because the local reference to the tile source would still contain a reference to the unclosed bioformats resource.

Better release bioformats resources.

---

CHANGELOG.md
girder/girder_large_image/web_client/views/imageViewerSelectWidget.js
girder/test_girder/web_client_specs/imageViewerSpec.js

This is one of the causes of transient test failures, but shows a user interface bug.  Occasionally, when making a large image that requires converting via a job, the page would update after the job completed but before the image was marked as updated.  This would result in the page refreshing and still showing that the job was pending.
This substantially reduces transient test failures in one test environment.

Harden updating the item view after making a large image.

---

sources/ometiff/large_image_source_ometiff/__init__.py
sources/openslide/large_image_source_openslide/__init__.py
sources/tiff/large_image_source_tiff/__init__.py

This should very slightly reduce database access in Girder.

Store the large image path to avoid rerequesting it.

---

girder/girder_large_image/__init__.py

There was a condition where the image conversion job sent a completion message before the upload was finalized.

Harden updating after making a large image

---

.circleci/config.yml

This can help debug build failures.

Store build artifacts.

---

sources/bioformats/large_image_source_bioformats/__init__.py

As of version 4.0.0, log4j isn't bundled in the jar, so attempting to configure logging always results in warnings.  For now, don't try to configure logging.

Reduce bioformats warnings.

---

.circleci/config.yml

This will detect help upstream changes during periods of slow development.

Set up weekly CI.

---

CHANGELOG.md
test/test_converter.py
utilities/converter/large_image_converter/__init__.py

Allow conversion from files that can be read by large image but not by vips.  This permits reencoding inefficient files to a preferred format.

Convert from large_image sources.

---

large_image/tilesource/base.py

Tile size can be erroneously rounded to the integer value, while it needs to be rounded up. This would resolve #440.

After resampling the tile size needs to be rounded up in tileiterator

---

girder/test_girder/conftest.py
setup.cfg
sources/gdal/large_image_source_gdal/__init__.py
test/test_source_bioformats.py
test/test_source_pil.py
tox.ini

This reduces warnings on
- celery backend
- pytest strict mode
- pyproj transform
This also hardens test order to some degree.  Ideally, we could run tests in a random order, but when that is done, sometimes java doesn't stop and restart as cleanly as it should.
Also, stop writing GDAL PAM (aux.xml) files when running tox.

Reduce warnings.

---

utilities/converter/large_image_converter/__init__.py
utilities/converter/large_image_converter/__main__.py

Delete partially generated files when creating a geotiff fails.

Improve help text.

---

test/test_converter.py
utilities/converter/large_image_converter/__init__.py
utilities/converter/large_image_converter/__main__.py

When encoding multiple images via vips, allow them to be encoded in parallel.  Allow specifying the concurrency on the command line.

Provide some concurrency support.

---

utilities/converter/large_image_converter/__main__.py

We should always use the tiff tile source when doing the comparison.

Sometimes the statistics weren't computed correctly.

---

CHANGELOG.md
large_image/__init__.py
large_image/tilesource/__init__.py
sources/bioformats/large_image_source_bioformats/__init__.py
sources/dummy/large_image_source_dummy/__init__.py
sources/gdal/large_image_source_gdal/__init__.py
sources/mapnik/large_image_source_mapnik/__init__.py
sources/nd2/large_image_source_nd2/__init__.py
sources/ometiff/large_image_source_ometiff/__init__.py
sources/openjpeg/large_image_source_openjpeg/__init__.py
sources/openslide/large_image_source_openslide/__init__.py
sources/pil/large_image_source_pil/__init__.py
sources/test/large_image_source_test/__init__.py
sources/tiff/large_image_source_tiff/__init__.py
test/test_converter.py
test/test_source_bioformats.py
test/test_source_dummy.py
test/test_source_gdal.py
test/test_source_mapnik.py
test/test_source_nd2.py
test/test_source_ometiff.py
test/test_source_openjpeg.py
test/test_source_openslide.py
test/test_source_pil.py
test/test_source_tiff.py
utilities/converter/large_image_converter/__main__.py

This also adds a canRead method to each source module and an open method to the primary module.
Before, to open a file with a specific file source, you needed to do something like ``large_image_source_tiff.TiffFileTileSource(path)``, where the name of the tile source's class had to be used.  Now, you can do ``large_image_source_tiff.open(path)``, which maps to the same thing.  The old way still works.  Similarly, ``canRead`` required something like ``large_image_source_tiff.TiffFileTileSource.canRead(path)`` and now ``large_image_source_tiff.canRead(path)`` works as well.
``open`` is now also a synonym for ``getTileSource``, so generically, ``large_image.getTileSource(path)`` can be written as ``large_image.open(path)``. 
There is no requirement that tile source modules expose the …

Add an open method to each source module.

---

CHANGELOG.md
docs/source/tilesource_options.rst
large_image/tilesource/base.py
test/test_source_ometiff.py

The style option band parameter can specify a frame value to combine multiple frames into a single output.

Support compositing multiple frames together.

---

CHANGELOG.md
large_image/constants.py
sources/bioformats/large_image_source_bioformats/__init__.py
sources/pil/large_image_source_pil/__init__.py

The PIL tilesource was a fallback source, but sources with the same priority level are used in an arbitrary order, and it was desired to make it higher priority than the bioformats source for small tiff files.  This introduces more resolution into the fallback priority ordering.

Increase the priority level of the PIL tile source.

---

girder/girder_large_image/__init__.py
girder/girder_large_image/constants.py
girder/girder_large_image/web_client/templates/largeImageConfig.pug
girder/girder_large_image/web_client/views/configView.js

The existing setting had two states: use items with likely names and mime types, or don't use anything.  This adds a third setting to try to use all items as large images.  It will slow down generic item ingestion but reduce the need to mark jpeg and png as large images.

Add an option to try using all items as large images.

---

CHANGELOG.md
girder/girder_large_image/girder_tilesource.py

Apply the same logic to prefer geospatial sources in Girder as we do in core.

Prefer geospatial sources for geospatial data.

---

CHANGELOG.md
sources/gdal/large_image_source_gdal/__init__.py

If a GDAL source had non-integer data, the band maxim/min calculation would fail.  Specifically, we were adding the maximum range of the integer type as a value at the end of the list of data for that frame's bands.  If the dtype is not an integer type, this fails.

Fix an issue with non-integer GDAL sources.

---

utilities/converter/large_image_converter/__init__.py

Without this, vips tries to hold all of the tiles in memory, which can exhaust it on large data sets.

When converting from tiles sources, have vips use disk

---

utilities/converter/large_image_converter/__init__.py

There is no need to format strings; the log call will do that if needed and not if log levels are low enough it isn't needed.

Refactor log statements.

---

docs/source/tilesource_options.rst
large_image/tilesource/base.py

This adds words users are likely to search for to the clamp option description.

Improve documentation on style.

---

.gitignore
CHANGELOG.md
docs/make_docs.sh
docs/source/image_conversion.rst
docs/source/index.rst
docs/source/tilesource_options.rst
girder/girder_large_image/rest/tiles.py
large_image/tilesource/__init__.py
sources/openslide/large_image_source_openslide/__init__.py
sources/tiff/large_image_source_tiff/__init__.py
test/test_converter.py
utilities/converter/large_image_converter/__init__.py
utilities/converter/large_image_converter/__main__.py
utilities/converter/large_image_converter/format_aperio.py
utilities/converter/setup.py
utilities/tasks/large_image_tasks/tasks.py

This can be accessed either via the command line (`large_image_converter`) or via the `POST item/{itemId}/tiles/convert` endpoint and selecting the `format` `aperio` option.
It has some basic integration tests and manually has been checked to work with ImageScope.
If the source image does not have a label image, a thumbnail with a restricted aspect ratio (no more than a factor of 1.5 between the larger and smaller dimension) is used.   ImageScope essentially requires there to be some image for the label; in the future we may want options to place a different image there.
For multi-frame images that have distinct z values for each frame, the z value is store so ImageScope will show the appropriate focus slider with units in microns.  For other multi-frame images, the z value is just the …

Convert to svs

---

CHANGELOG.md
large_image/cache_util/cache.py

When an exception occurs when trying to fetch an item that could be cached, the exception was reported in the cache KeyError context which made debugging harder.  By changing the flow pattern, the exception is now reported in its expected context.

Improve the cache miss exception context.

---

CHANGELOG.md
sources/ometiff/large_image_source_ometiff/__init__.py

Have files where where lower levels report a tile size equal to the image size instead of the regular tile size.

Handle OME Tiff files with odd tile sizes.

---

girder/test_girder/test_tiles_rest.py
large_image/tilesource/base.py
sources/gdal/large_image_source_gdal/__init__.py

There has been two code paths, but one was essentially a lower quality option that was not enough faster to be worth maintaining.  Remove the low-quality option.

Simplify thumbnail generation.

---

CHANGELOG.md
girder/girder_large_image/models/image_item.py
girder/girder_large_image/rest/large_image_resource.py
girder/test_girder/test_large_image.py
girder/test_girder/test_tiles_rest.py
large_image/tilesource/base.py
tox.ini

This caches them in memory in the core library and to attached files in Girder.

Cache histograms.

---

CHANGELOG.md
large_image/cache_util/cache.py
large_image/cache_util/cachefactory.py
large_image/config.py

Added `cache_tilesource_memory_portion` and `cache_tilesource_maximum` config options.  The number of tile sources that are caches is the smallest of (a) the number of available file handles divided by a factor and reduced by a constant, (b) the available memory divided by the portion (default 8) and the expected size of the largest tile source, (c) the cache maximum value.  Before, the portion was always 8 and there was no way to specify a maximum value.
This can be applied in girder, for instance via the `[large_image]` section of the config file with something like::
```
cache_tilesource_memory_portion = 16
cache_tilesource_maximum = 64
```

Add more cache configuration options.

---

CHANGELOG.md
docs/source/config_options.rst
docs/source/index.rst
sources/bioformats/large_image_source_bioformats/__init__.py

Improve documenting configuration options.

Allow configuring extensions used in bioformats.

---

CHANGELOG.md
girder/girder_large_image/rest/tiles.py
girder/test_girder/girder_utilities.py
girder/test_girder/test_tiles_rest.py
large_image/constants.py
large_image/tilesource/base.py
sources/gdal/large_image_source_gdal/__init__.py
test/test_source_gdal.py
test/test_source_tiff.py
test/utilities.py
utilities/converter/large_image_converter/__init__.py

This also will geotag geospatial outputs.
Specifically, when calling the getRegion function or endpoint, if an encoding of `TILED` is used (previously this could have been one of `JPEG`, `PNG`, or `TIFF`), a tiled tiff is output.  For non-geospatial sources, this is tiled using vips.  For geospatial sources, this is tiled using gdal.
When using the `TILED` option, a variety of parameters that can be used in conversions can be used: `compression`, `quality`.  For compatibility, these can also be `tiffCompression` and `jpegQuality`.

Provide an option to output large regions as tiled tiffs

---

girder/girder_large_image/web_client/views/imageViewerWidget/base.js

This allows a custom client to override parameters without subclassing the tile url generator.  For instance, in a wrapped `ItemView` `initialize` function, you could add `this.once('h:viewerWidgetCreated', viewerWidget => viewerWidget.tileQueryDefaults = {encoding: 'PNG'});`.

Support tile query default parameters for the image viewer widget

---

CHANGELOG.md
girder/girder_large_image/rest/large_image_resource.py
large_image/cache_util/__init__.py
large_image/cache_util/memcache.py
test/test_cache.py
utilities/converter/large_image_converter/__init__.py

To get stats from memcached, no_block must be off.
This now reports memcached items and usage and clears it when clearing the cache.

Better report on memcached cache.

---

CHANGELOG.md
girder/girder_large_image/models/image_item.py
girder/girder_large_image/rest/tiles.py
girder/test_girder/test_tiles_rest.py

This only affects the Girder endpoint.

Fix getting band information on frames.

---

large_image/tilesource/tiledict.py
sources/tiff/large_image_source_tiff/__init__.py
sources/tiff/large_image_source_tiff/tiff_reader.py
test/datastore.py
test/test_converter.py
test/test_source_tiff.py
utilities/converter/large_image_converter/__init__.py

This handles files with jpeg compression and some tiles with zero length that are functionally just missing.

Handle tiff tiles with zero length.

---

CHANGELOG.md
girder/girder_large_image/rest/tiles.py
sources/test/large_image_source_test/__init__.py
test/test_converter.py
utilities/converter/large_image_converter/__init__.py
utilities/converter/large_image_converter/__main__.py

Allow using the test tile source as an input to the converter to make it easier to test some behavior and to generate test files.

Support frame options for the test tile source.

---

CHANGELOG.md
girder/girder_large_image/web_client/views/imageViewerWidget/geojs.js
girder/girder_large_image/web_client/views/imageViewerWidget/setFrameQuad.js

This requires a version of GeoJS newer than v1.2.0 to have any effect.

Use tile-frames for better frame browsing.

---

CHANGELOG.md
girder/girder_large_image/models/image_item.py
girder/girder_large_image/rest/large_image_resource.py
girder/test_girder/test_large_image.py

Before, the per-image cache count was for all images (thumbnails, thumbnails of associated images, etc).  Now it is by type.  Further, a specific imageKey can be queried or deleted independently of the others (e.g., just macro).

Better associated image cache control.

---

CHANGELOG.md
sources/gdal/large_image_source_gdal/__init__.py
test/test_source_gdal.py
test/test_source_mapnik.py

When some files that wrap around the globe had their bounds calculated, instead of it being the entire span of longitude, it was a singular longitude value.

Improve geospatial bounds in some projections.

---

.circleci/make_wheels.sh
.circleci/release_pypi.sh
CHANGELOG.md
README.rst
docs/make_docs.sh
docs/source/index.rst
girder/test_girder/test_large_image.py
girder/test_girder/test_tiles_rest.py
girder/test_girder/test_web_client.py
requirements-dev.txt
requirements-worker.txt
sources/deepzoom/large_image_source_deepzoom/__init__.py
sources/deepzoom/large_image_source_deepzoom/girder_source.py
sources/deepzoom/setup.py
test/test_source_deepzoom.py
tox.ini

This works with the dzi files as output by vips in both onetile and onepixel modes and with both png and jpeg compression.  It should allow for any tile size and overlap as generated by vips.
A future expansion would be to read property files and handle center and other options in dzsave.
Closes #31.

Add a deepzoom tile source

---

CHANGELOG.md
large_image/tilesource/__init__.py
large_image/tilesource/utilities.py
sources/bioformats/large_image_source_bioformats/__init__.py
sources/gdal/large_image_source_gdal/__init__.py
utilities/converter/large_image_converter/__init__.py

Detecting geospatial files was brittler than intended.  Bioformats throws poor errors.

Harden tile source detection.

---

CHANGELOG.md
large_image/tilesource/base.py

If there were more than four bands and the band interpretation is not known, an error was thrown instead of returning `unknown`.

Band interpretation for high bands errored.

---

girder/test_girder/test_tiles_rest.py
sources/gdal/large_image_source_gdal/__init__.py
sources/openjpeg/large_image_source_openjpeg/__init__.py

This will be lower priority than non-geospatial sources.
Closes #652.  GDAL should support ENVI format.

Allow GDAL to read non-geospatial files.

---

girder/girder_large_image/girder_tilesource.py
girder/girder_large_image/models/image_item.py
girder/girder_large_image/rest/large_image_resource.py
girder/girder_large_image/rest/tiles.py
girder/test_girder/test_web_client.py
large_image/exceptions.py
large_image/tilesource/__init__.py
large_image/tilesource/base.py
large_image/tilesource/tiledict.py
sources/bioformats/large_image_source_bioformats/__init__.py
sources/deepzoom/large_image_source_deepzoom/__init__.py
sources/gdal/large_image_source_gdal/__init__.py
sources/mapnik/large_image_source_mapnik/__init__.py
sources/nd2/large_image_source_nd2/__init__.py
sources/ometiff/large_image_source_ometiff/__init__.py
sources/openjpeg/large_image_source_openjpeg/__init__.py
sources/openslide/large_image_source_openslide/__init__.py
sources/pil/large_image_source_pil/__init__.py
sources/pil/large_image_source_pil/girder_source.py
sources/test/large_image_source_test/__init__.py
sources/tiff/large_image_source_tiff/__init__.py
test/test_source_base.py
test/test_source_gdal.py
test/test_source_mapnik.py

Add `TileSourceFileNotFoundError` when a file is attempted to be opened that doesn't exist.  This is a subclass of both `TileSourceError` and `FileNotFoundError`.
Rename exceptions to errors follows standard Python naming conventions.  Old names are still available for compatibility.
This closes #656.

Rename Exceptions to Errors.

---

sources/bioformats/large_image_source_bioformats/__init__.py
test/test_source_base.py

This allows better identification where `canRead` and actually reading are at odds.

Increase source tests.

---

CHANGELOG.md
girder/test_girder/test_tiles_rest.py
large_image/tilesource/base.py
test/test_source_base.py
test/test_source_pil.py

This is in active use for the GDAL tile source; other tile sources should conform.

Always have band number start at 1.

---

sources/ometiff/large_image_source_ometiff/__init__.py

Some files raise a `TypeError` in the current parsing; the parsing should be improved, but this at least allows graceful failure until that is done.

Guard against an OME tiff exception.

---

CHANGELOG.md
sources/openslide/large_image_source_openslide/__init__.py

Specifically, after a low level error, reopen the openslide file as the existing process may be in a state that will not work.

Harden on openslide errors.

---

CHANGELOG.md
setup.py

If you pip install large-image[converter] or large-image[all], this will be included.

Add the image converter to the extra requires.

---

CHANGELOG.md
sources/bioformats/large_image_source_bioformats/__init__.py
sources/gdal/large_image_source_gdal/__init__.py
sources/mapnik/large_image_source_mapnik/__init__.py
sources/nd2/large_image_source_nd2/__init__.py
sources/ometiff/large_image_source_ometiff/__init__.py
sources/openjpeg/large_image_source_openjpeg/__init__.py
sources/openslide/large_image_source_openslide/__init__.py
sources/tiff/large_image_source_tiff/__init__.py
test/test_source_base.py

This also makes some of the internal variables a little more consistent.
Closes #679.

Ensure that all file tile sources can handle Path and str arguments.

---

girder/girder_large_image/models/image_item.py

This should fail to store to the cache rather than fail.

Guard caching on read-only assetstores.

---

CHANGELOG.md
large_image/tilesource/__init__.py
sources/gdal/large_image_source_gdal/__init__.py
test/datastore.py
test/test_source_base.py
test/test_source_gdal.py

There are files that have coordinates in lat/lon but no listed projection.
Closes #676.

Support more geospatial files.

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/girder_large_image_annotation/models/annotationelement.py

This fixes a bug when emitting annotations where centroids are used for rendering and the annotation element doesn't specify color.

Have appropriate default properties when emitting centroids.

---

large_image/cache_util/cache.py

This little log message shows up anytime you import `large_image` which can be quite unsightly in a Jupyter notebook:
Ref https://github.com/banesullivan/localtileserver/issues/17#issuecomment-980487066

Change pesky logger message to debug level

---

.circleci/config.yml
Dockerfile
girder/setup.py
girder_annotation/setup.py
setup.py
sources/bioformats/setup.py
sources/deepzoom/setup.py
sources/dummy/setup.py
sources/gdal/setup.py
sources/mapnik/setup.py
sources/nd2/large_image_source_nd2/__init__.py
sources/nd2/setup.py
sources/ometiff/setup.py
sources/openjpeg/setup.py
sources/openslide/setup.py
sources/pil/setup.py
sources/test/setup.py
sources/tiff/setup.py
tox.ini
utilities/converter/setup.py
utilities/tasks/setup.py

Currently, this has to build scikit-image for Python 3.10.  Since this takes a long time, it is not enabled on circle-ci.

Test on Python 3.10.

---

.circleci/config.yml
girder/setup.py
requirements-dev.txt
tox.ini
utilities/tasks/setup.py

Now that scikit-image has a 3.10 wheel, this can run in a sensible amount of time.
Remove some older cruft from earlier python versions.
Reduce dependencies for the girder plugin if tasks aren't used.

Enable python 3.10 testing on CI

---

large_image/tilesource/__init__.py
test/test_source_base.py

This handles some difference in the conda and pip installations of gdal.
Closes #656.

Harden detecting file-not-found.

---

CHANGELOG.md
README.rst
docs/tilesource_options.rst
large_image/tilesource/base.py
large_image/tilesource/utilities.py
requirements-dev-core.txt
requirements-dev.txt
setup.py
sources/gdal/large_image_source_gdal/__init__.py
sources/gdal/setup.py
sources/mapnik/large_image_source_mapnik/__init__.py
test/test_source_base.py
test/test_source_gdal.py
test/test_source_mapnik.py

This also increase the ability to handle css and named colors.
This generalized and supercedes #714.  This closes #716.

Allow named color palettes to be used by all sources.

---

tox.ini
utilities/converter/large_image_converter/__main__.py
utilities/converter/setup.py

Ideally, warnings should indicate actual, actionable problems.

Reduce pytest warnings.

---

CHANGELOG.md
large_image/tilesource/utilities.py
test/test_source_base.py

Add a getAvailableNamedPalettes function.

---

girder_annotation/test_annotation/girder_utilities.py
girder_annotation/test_annotation/test_annotations_rest.py
sources/gdal/large_image_source_gdal/__init__.py
sources/nd2/large_image_source_nd2/__init__.py
sources/openslide/large_image_source_openslide/__init__.py
sources/tiff/large_image_source_tiff/__init__.py
sources/tiff/large_image_source_tiff/tiff_reader.py

This just simplifies the code slightly.

Don't specify the default encoding for encode/decode.

---

CHANGELOG.md
large_image/tilesource/__init__.py
setup.py

Use importlib.metadata instead of pkg_resources.

---

girder_annotation/docs/annotations.rst
girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/girder_large_image_annotation/models/annotationelement.py
girder_annotation/test_annotation/test_annotations.py

This PR addresses server-side changes for #678 
Changes include:
- Modification of existing annotation schema to allow for specification of an image overlay
An image overlay is specified on the annotation itself, and not as an element. At a minimum, an image overlay requires a girder large image item ID. Opacity and location can also be specified. Location is specified with properties for position of the top-left corner of the image to overlay, as well as ta height and width. By default the overlaid image has opacity 1 and is aligned in the upper left in its native resolution.
The reason I went with adding the overlay as a direct child to the annotation schema, and not as a type of annotation element, is that I am trying to avoid a major refactor of what an annotation element is. It seems …

Add image overlays to annotation schema

---

girder_annotation/docs/annotations.rst
girder_annotation/girder_large_image_annotation/models/annotation.py

This also makes the spacing in the annotation schema docs more consistent.

Include user, group, and label in the imageoverlay schema.

---

girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/girder_large_image_annotation/web_client/annotations/convertFeatures.js
girder_annotation/girder_large_image_annotation/web_client/models/AnnotationModel.js
girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js
girder_annotation/test_annotation/web_client_specs/geojsSpec.js

Implement client support for image overlay annotation elements.
Changes include:
(opening as draft PR to kick start discussion about implementation details)
Closes #678

Display image overlay annotations

---

CHANGELOG.md
large_image/tilesource/utilities.py
test/test_source_base.py

Work with more more matplotlib palettes.

---

girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js

This PR rounds out some functionality for image overlays that make them more reactive in applications like [HistomicsUI](https://github.com/DigitalSlideArchive/HistomicsUI).
Specifically, this PR introduces the following changes:
- Image overlay layers now properly respond to the `globalAnnotationOpacity` of the image viewer. As a result, image overlays now change opacity based on the slider in HistomicsUI.
- Image overlays now respect the currently highlighted annotation. Image overlay elements of non-highlighted annotations will reduce their opacity by 75% like other element types. This can be demonstrated in HUI by selecting "Interactive" in the annotations widget and hovering over different annotations in the list.
- Schema for image overlays now allows for additional properties. This …

Add additional behaviors to image overlays

---

girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/test_annotation/test_annotations.py

Update and make the annotation schema more uniform.

---

CHANGELOG.md
large_image/tilesource/base.py
test/test_source_base.py

The repr now returns the state string, which includes the specific information that makes the class unique.

Change the repr of the TileSource class.

---

.circleci/make_wheels.sh
.circleci/release_pypi.sh
CHANGELOG.md
README.rst
docs/index.rst
docs/make_docs.sh
docs/multi_source_specification.rst
large_image/tilesource/base.py
large_image/tilesource/utilities.py
requirements-dev-core.txt
requirements-dev.txt
requirements-worker.txt
setup.py
sources/multi/docs/specification.rst
sources/multi/large_image_source_multi/__init__.py
sources/multi/large_image_source_multi/girder_source.py
sources/multi/setup.py
test/datastore.py
test/test_files/multi1.yml
test/test_files/multi2.yml
test/test_files/multi3.yml
test/test_files/multi_channels.yml
test/test_files/multi_composite.yml
test/test_files/multi_simple_scaling.yml
test/test_source_base.py
test/test_source_multi.py

This adds a source that can be composited from other sources.
This is still a work-in-progress, needing some features and tests.  It *should* work except for crop and any transforms where s12 or 21 is non-zero or s11 or s22 is less than zero.
There are several ways that the same set of files can be specified.  For instance, given a set of eight files named `test_orient1.tif`, `test_orient2.tif`, ..., `test_orient8.tif`, to make a source that uses all of these files, the following yaml files are equivalent:
- (1) explicitly specify each frame and a z value
```
sources:
- path: ./test_orient1.tif
z: 0
- path: ./test_orient2.tif
z: 1
- path: ./test_orient3.tif
z: 2
- path: ./test_orient4.tif
z: 3
- path: ./test_orient5.tif
z: 4
- path: ./test_orient6.tif
z: 5
- path: ./test_orient7.tif
z: 6 …
```

Add multi-source source

---

sources/bioformats/setup.py

This prevents PIMS from throwing warnings.

A scikit-image as a requirement for the bioformats source.

---

CHANGELOG.md
large_image/tilesource/utilities.py
utilities/converter/large_image_converter/__main__.py

Before, sub-resolution images could be interpolated.  Now, they use nearest neighbor rather than mean when scaling, so all pixel values in sub-resolution images also exist in full-resolution images.

Adjust scaling when generating lossless pyramidal files.

---

CHANGELOG.md
large_image/tilesource/base.py
test/test_source_base.py

This fixes a bug where, when overlap was specified, some smaller tiles could be returned at the right/bottom edges that were not necessary.  Since the overlap was documented, this probably only resulted in inefficiency, not and breakage.  This change now conforms to the tileIterator documentation and adds a test to ensure this is the case.

The tile iterator could return excess tiles with overlap.

---

setup.py

This is needed when generating tiled output regions.

Add a tiledoutput extra_requires entry.

---

CHANGELOG.md
large_image/cache_util/memcache.py
large_image/tilesource/utilities.py

Some libraries: palettable and pylibmc account for a substantial import time.  Loaded them as needed rather than on first import.

Improve the import time.

---

girder_annotation/girder_large_image_annotation/web_client/models/AnnotationModel.js
girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js
girder_annotation/test_annotation/web_client_specs/geojsSpec.js

This PR updates the `large_image` plugin to support drawing `pixelmap` annotations (see #767).

Support pixelmap annotations

---

CHANGELOG.md
large_image/tilesource/tiledict.py
test/test_source_base.py
tox.ini

This allows keeping a tile's properties in memory without its actual data, which might be useful if one processes the data and then collects it using subprocessing.

Add a convenience function to release tile resources.

---

CHANGELOG.md
large_image/tilesource/base.py
test/test_source_base.py

Fix an issue with reported tile overlap values when a region is a subset of the whole image (not at top-left).  Before the top and left tiles, if partial, reported the wrong right and bottom overlaps.

Tile overlaps on subset regions.

---

girder/test_girder/web_client_specs/imageViewerSpec.js

Reduce a size used internally that affects how long tests in a non webgl context take to execute.

Reduce time spend in some image tests.

---

setup.py
sources/nd2/large_image_source_nd2/__init__.py
sources/nd2/setup.py
test/test_source_base.py
test/test_source_multi.py
test/test_source_nd2.py

This should be more consistent than the nd2reader library.
The only downside of this is that the nd2 module is Python 3.7 or later.
Closes #796.

Refactor the nd2 source to use the nd2 library.

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/rest/annotation.py
girder_annotation/setup.py

orjson is faster and is supposed to use less memory.
It is measurably faster on large annotations (by about 30% on ingest on one sample).

Use orjson instead of ujson for annotations.

---

CHANGELOG.md
README.rst
girder/girder_large_image/models/image_item.py
large_image/tilesource/base.py
large_image/tilesource/utilities.py
requirements-dev.txt
setup.py

This shaves more than 5 ms off of typical tile generation.  In one test, average tile generation time dropped from 17.4 ms to 12.1 ms.  This was with concurrent rest requests to Girder; the time was roughly twice this without concurrent requests.
This can be included with `pip install large_image[performance]` (or, of course `large_image[all]`).

Use simplejpeg for jpeg encoding rather than PIL.

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/test_annotation/test_annotations.py

Harden annotation ACL migration code.

---

sources/tiff/setup.py

This PR updates the package name for [pearu/pylibtiff](https://github.com/pearu/pylibtiff).
It seems the official PyPI project name for [pearu/pylibtiff](https://github.com/pearu/pylibtiff) changed from [`libtiff`](https://pypi.org/project/libtiff) to [`pylibtiff`](https://pypi.org/project/pylibtiff) as of October 21, 2021.

Change `libtiff` dependency to `pylibtiff`

---

CHANGELOG.md
girder/girder_large_image/models/image_item.py
girder/girder_large_image/web_client/package.json
girder_annotation/girder_large_image_annotation/web_client/package.json
large_image/cache_util/cache.py
utilities/converter/large_image_converter/__init__.py

In Girder, when we have an imported file that has been moved or deleted, the error messages were misleading.  This improves them to hopefully making it more obvious why a conversion or opening an image has failed.
Resolves #132.

Improve handling when a file vanishes.

---

CHANGELOG.md
girder/girder_large_image/rest/tiles.py
girder/test_girder/test_tiles_rest.py

The region, thumbnail, and tile_frames endpoints can returned pickled numpy arrays.
This facilitates getting numpy data from a tile source through Girder Client.  For instance, `numpyarray = pickle.loads(gc.get('item/5c3e0590e45e326a5e2fb252/tiles/region', parameters={'encoding': 'pickle:' + str(pickle.HIGHEST_PROTOCOL), 'width': 2000}, jsonResp=False).content)` would fetch a numpy array as efficiently as possible.  The protocol will be the lower of that specified in the request and the maximum for the python version of the server.  Just using 'pickle' will use protocol 4, which will work with any supported version of Python 3 -- specifying an explicit number is more efficient and adapts to clients using a Python version not otherwise supported.

Support pickle output of numpy arrays for endpoints.

---

girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js

Move some repeated code outside of a function loop.
Ensure the annotation layer remains on top.

Fix a range check.

---

sources/gdal/large_image_source_gdal/__init__.py
test/test_source_gdal.py

Handle file URLs with GDAL

---

.circleci/make_wheels.sh
.circleci/release_pypi.sh
CHANGELOG.md
README.rst
docs/config_options.rst
docs/index.rst
docs/make_docs.sh
large_image/constants.py
requirements-dev-core.txt
requirements-dev.txt
requirements-worker.txt
sources/vips/large_image_source_vips/__init__.py
sources/vips/large_image_source_vips/girder_source.py
sources/vips/setup.py
test/test_source_base.py
test/test_source_vips.py

This class can be used to write files as well.  This is a new capability and should be regarded as somewhat in flux.  Specifically, you can do
```
import large_image_source_vips
newsrc = large_image_source_vips.new()
for chunk, x, y in chunk_generator: # some process that generates numpy arrays or images
newsrc.addTile(chunk, x, y)
newsrc.write('output.tiff')
```

Add a vips tilesource

---

CHANGELOG.md
girder_annotation/docs/annotations.rst
girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js

This dictates whether the default renderer uses jpegs or pngs and whether lower level tiles are rendered.

Support a hasAlpha flag on image annotations.

---

large_image/tilesource/base.py
test/test_source_gdal.py
test/test_source_ometiff.py
test/test_source_tiff.py

Resolves #730
I changed a few tests at random to use a dict instead of doing `json.dumps` to make sure this is tested

Support style dictionary

---

sources/gdal/large_image_source_gdal/__init__.py

There is an import order that isort shouldn't sort.  This makes that more explicit.

Fix comments so that running tox -e format works.

---

girder/setup.py
girder_annotation/setup.py
setup.py
sources/bioformats/setup.py
sources/deepzoom/setup.py
sources/dummy/setup.py
sources/gdal/setup.py
sources/mapnik/setup.py
sources/multi/setup.py
sources/nd2/setup.py
sources/ometiff/setup.py
sources/openjpeg/setup.py
sources/openslide/setup.py
sources/pil/setup.py
sources/test/setup.py
sources/tiff/setup.py
sources/vips/setup.py
utilities/converter/setup.py
utilities/tasks/setup.py

If setuptools_scm is installed and a local deploy is made that isn't a github repo, then packages fail to install unless there is a fallback version.

Add scm version fallback.

---

sources/vips/large_image_source_vips/__init__.py

By default pyvips.black can't be copied to a different format, but must be cast.

Improve handling for vips format.

---

large_image/config.py

This is more in line with other libraries.
With this, PR #819 should be changed to just convert a few entries to errors and leave the other log messages as is.

Switch the default logger to the null handler.

---

girder_annotation/docs/annotations.rst
girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/girder_large_image_annotation/web_client/annotations/geometry/polyline.js

This will *render* polygons with holes, but doesn't yet support editing them.
Some scalability tests are needed.

Allow polygons with holes to be specified.

---

girder_annotation/girder_large_image_annotation/__init__.py
girder_annotation/girder_large_image_annotation/handlers.py
girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/girder_large_image_annotation/web_client/views/annotationListWidget.js

This had been using an endpoint where the entire annotation has to be sent as a single request.  This now uses the common upload widget, uploads it as a regular file, and then ingests it.

Change how annotations are uploaded from the UI.

---

girder/setup.py
girder_annotation/setup.py
setup.py
sources/bioformats/setup.py
sources/deepzoom/setup.py
sources/dummy/setup.py
sources/gdal/setup.py
sources/mapnik/setup.py
sources/multi/setup.py
sources/nd2/setup.py
sources/ometiff/setup.py
sources/openjpeg/setup.py
sources/openslide/setup.py
sources/pil/setup.py
sources/test/setup.py
sources/tiff/setup.py
utilities/converter/setup.py
utilities/tasks/setup.py

Otherwise, you pretty much have to do `tox -r` after every change if you want to test the results.

Reduce the strictness of version checks in dev branches

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/girder_large_image_annotation/models/annotationelement.py
girder_annotation/girder_large_image_annotation/rest/annotation.py
girder_annotation/test_annotation/test_annotations_rest.py

This adds an option to the GET annotation/{id} endpoint and to the annotationelement.yieldElements method.  The annotationelement.getElements and annotation.load methods support passing the additional bbox=True argument as part of the region request.
The result that includes the _elementQuery record also has the bounding box for the specific query (it is of just the elements that are returned if they are paged or limited).
Closes #850.

Add an option to including bounding box information with elements.

---

CHANGELOG.md
sources/nd2/large_image_source_nd2/__init__.py

We are using the dask interface with nd2 to avoid loading all of a file into memory.  When we read anything other then an entire frame, the default is to copy the entire frame in memory and THEN apply whatever index and step is being used.  The nd2 library docs caution that if copy isn't done, there can be a segfault.  Instead, use our own lock, get the frame data, subset it with our index and step and THEN copy it; since this is in a singular lock, it won't have any greater risk that the nd2 library.  Since the copy only applies to the actual data we are using, much less memory is copied.
In a simple example with a file with large tiles, this saves close to 2 seconds per tile.

Change where nd2 data gets copied.

---

CHANGELOG.md
girder/girder_large_image/__init__.py
girder/girder_large_image/rest/__init__.py
girder/test_girder/girder_utilities.py
girder/test_girder/test_large_image.py

Support fetching yaml config files

---

girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js

This makes the interface more consistent, but still has the surprise that there is a threshold where the behavior changes.  We may want to revisit highlighting in large sets of annotations, in which case we need to adjust centroid annotations, too.
See https://github.com/DigitalSlideArchive/HistomicsUI/issues/45.

Honor the highlight size limit with centroid annotations.

---

girder_annotation/girder_large_image_annotation/rest/annotation.py

This needlessly loaded them into memory before discarding them.

Speed up remove all annotations from an item

---

sources/nd2/setup.py

Version 0.2.3 appears broken with at least one of our files.

Pin the nd2 library.

---

girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js

When the base image is panned, sometimes an update occurs before the reset features are updated.  This forces the update sooner.

Reduce the chance of blinking on annotation layers.

---

large_image/cache_util/base.py
large_image/cache_util/cache.py
large_image/cache_util/cachefactory.py
large_image/cache_util/memcache.py
large_image/config.py
large_image/exceptions.py

Abstracts the caching mechanism so that external projects can implement a cache interface and use entrypoints to make it available to large_image.
Generally, this is working for django-large-image with https://github.com/girder/django-large-image/pull/32
Todo:

Abstract caching and support entrypoints

---

girder_annotation/docs/annotations.rst
girder_annotation/girder_large_image_annotation/web_client/annotations/convertFeatures.js
setup.py

When scaleWithZoom is selected, make the radius in terms of the first tile layer's base pixel size.

When scaling heatmap annoations, use an appropriate value.

---

CHANGELOG.md
girder/girder_large_image/web_client/package.json
girder/girder_large_image/web_client/views/imageViewerWidget/geojs.js
girder/girder_large_image/web_client/webpack.helper.js

Prior to this, browsers often would cache a version of geojs and not load a new one, even if the client was otherwise loaded.

Use the girder client build time for cache control.

---

.circleci/make_wheels.sh
.circleci/release_pypi.sh
README.rst
docs/index.rst
docs/make_docs.sh
requirements-dev-core.txt
requirements-dev.txt
requirements-worker.txt
setup.py
sources/tiff/large_image_source_tiff/__init__.py
sources/tifffile/large_image_source_tifffile/__init__.py
sources/tifffile/large_image_source_tifffile/girder_source.py
sources/tifffile/setup.py
test/test_source_base.py

This better supports Leica SCN files than either the openslide or tiff sources.
TODO:
- When there is no S and C <= 3, should we auto-composite channels?  We have appropriate data in self._channelInfo.
- Currently, series and pages that aren't used for the image and are larger than a specified size aren't exposed in any manner (i.e., not as associated images).  Should we expose them in a reduced resolution version?  Or list those that aren't exposed in the internal metadata?

Add a tifffile tile source.

---

CHANGELOG.md
utilities/tasks/large_image_tasks/tasks.py

This improves local job support for converting uploaded multi-file images.

When converting girder images locally, prefer mount paths.

---

CHANGELOG.md
large_image/__init__.py
large_image/tilesource/__init__.py
test/test_source_base.py

```
import large_image, pprint
pprint.pprint(large_image.canReadList('TCGA-02-0010-01Z-00-DX4.07de2e55-a8fe-40ee-9e98-bcb78050b9f7.svs'))
```
results in
```
[('openslide', True),
('multi', False),
('openjpeg', False),
('tiff', True),
('deepzoom', False),
('nd2', False),
('ometiff', False),
('tifffile', True),
('vips', False),
('pil', False),
('bioformats', True),
('gdal', True),
('mapnik', True)]
```
showing the order and utility of each source.

Add canReadList function to show what sources could be used.

---

large_image/tilesource/utilities.py
test/test_source_base.py

Addresses #855.
This still needs documentation

Add local color definitions.

---

CHANGELOG.md
sources/tifffile/large_image_source_tifffile/__init__.py

Don't use very tiny images as separate frames.

Require a minimum size of secondary frames in tifffile sources.

---

girder/girder_large_image/__init__.py
girder/girder_large_image/constants.py
girder/girder_large_image/rest/__init__.py
girder/girder_large_image/web_client/templates/largeImageConfig.pug
girder/girder_large_image/web_client/views/configView.js
girder/test_girder/test_large_image.py
girder/test_girder/web_client_specs/largeImageSpec.js

This will be more fully documented in a subsequent PR.

Inheritable config files.

---

large_image/tilesource/__init__.py
large_image/tilesource/base.py
sources/gdal/large_image_source_gdal/__init__.py
sources/mapnik/large_image_source_mapnik/__init__.py

Work in progress to resolve #805 
(using CI to test since I can't get the test env going locally at the moment)

Add `geospatial` property

---

large_image/tilesource/utilities.py
test/test_source_base.py
test/test_source_gdal.py
test/test_source_tiff.py
utilities/converter/large_image_converter/__init__.py

When using `getThumbnail()` or `getTile()` in `ipython`/Jupyter, the `bytes` repr output can be overbearing and not all that useful as the image bytes can overtake the output with very long amounts of data.
These changes add a wrapper class to the `bytes` object for when we are returning PNG, JPEG, or TIFF image data (to give more user-friendly outputs in ipython and show an actual preview of the image in Jupyter
This is incredibly useful when trying to debug the graphical outputs of these methods.
```py
In [1]: import large_image
In [2]: src = large_image.open('co_elevation.tif', projection='EPSG:3857')
In [3]: thumb, mime = src.getThumbnail()
In [4]: thumb
Out[4]: b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x01\x01\x01\x01\x02\x01\x01\x …
```

Improve repr of image bytes

---

docs/tilesource_options.rst
girder/girder_large_image/rest/tiles.py
large_image/constants.py
large_image/tilesource/utilities.py
test/test_source_tiff.py

This closes #899.  We should create a new issue to abstract encoding options, since newly available encoding types will end up with default values until then.

Register the tile output formats from PIL.

---

CHANGELOG.md
sources/gdal/large_image_source_gdal/__init__.py

This affected sources with a projection that have an explicit alpha channel.
Fixes https://github.com/girder/django-large-image/issues/39

Fix alpha on some GDAL sources

---

large_image/cache_util/cache.py
large_image/tilesource/base.py
sources/gdal/large_image_source_gdal/__init__.py
sources/mapnik/large_image_source_mapnik/__init__.py
test/test_cache_source.py

Instead of reopening a tilesource when adding a style, copy the unstyled class and add the style information.
I've marked this as draft as I think it requires more tests to verify it does no harm.

Copy tilesource instances to add styles

---

CHANGELOG.md
large_image/tilesource/base.py
test/test_source_gdal.py

Handle nodata when passed as a string.
Fixes https://github.com/girder/large_image/issues/911.

Fix styling with nodata.

---

docs/girder_config_options.rst
girder/girder_large_image/web_client/templates/itemList.pug
girder/girder_large_image/web_client/views/itemList.js
test/test_files/.large_image_config.yaml

Add a defaultSort option for item lists.

---

CHANGELOG.md
sources/multi/large_image_source_multi/__init__.py
sources/test/large_image_source_test/__init__.py
test/test_files/multi_band.yml
test/test_files/multi_channels.yml
test/test_source_multi.py

This can help development of #498.
Specifically, upload the sample file `test/test_files/multi_band.yml` to a Girder instance to have a source with channels and bands.

Support a bands parameter for the test source

---

girder_annotation/girder_large_image_annotation/__init__.py
girder_annotation/girder_large_image_annotation/constants.py
girder_annotation/girder_large_image_annotation/rest/annotation.py
girder_annotation/girder_large_image_annotation/web_client/templates/annotationListWidget.pug
girder_annotation/girder_large_image_annotation/web_client/views/annotationListWidget.js
girder_annotation/girder_large_image_annotation/web_client/views/hierarchyWidget.js

Adds a new girder access flag which demarcates whether or not a user has permission to create annotations, allowing users to create annotations without having write access to a folder/item.  Also creates a new endpoint indicating whether or not the user has creation permissions (via write access or the flag) and makes current annotation creation procedures check for the access flag.

Add annotation creation access flag

---

CHANGELOG.md
sources/tiff/large_image_source_tiff/__init__.py
test/datastore.py
test/test_source_base.py
test/test_source_tiff.py

We had one test file with a "thumbnail" image that was tiled but at a different resolution than expected.  This was mistakenly used as a level of the image.

Better ignore tiff directories that aren't part of the pyramid.

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/models/annotationelement.py

These are subject to the mongo limit of 16Mb documents, but it can be useful to store large vectors of supplemental information in them.

Handle large user records in annotation elements.

---

CHANGELOG.md
large_image/tilesource/utilities.py
test/test_source_base.py

This will fall back to lower bit depths as needed and excludes some formats from listing at all.
Closes #950.

Harden which output formats are supported.

---

CHANGELOG.md
large_image/tilesource/base.py
sources/multi/large_image_source_multi/__init__.py
sources/tifffile/large_image_source_tifffile/__init__.py
test/test_source_multi.py

This also fixes a spurious `IndexI` entry in some tifffile sources.

Add a framesAsAxes parameter to the multisource.

---

CHANGELOG.md
sources/tiff/large_image_source_tiff/tiff_reader.py

The tiff tilesource will now read greyscale with alpha files.

Reduce a restriction on reading some tiff files.

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js

Overlay annotations at scales other than the base image could show eccentric tile layers.

Improve scaled overlays.

---

CHANGELOG.md
docs/tilesource_options.rst
large_image/tilesource/base.py
large_image/tilesource/stylefuncs.py
large_image/tilesource/utilities.py
test/test_source_base.py

Resolves #688.
This can be used, for instance, to get a mask from a superpixel image. For instance, suppose you want a mask for the superpixel with an index of 82, you'd use a style like:
`{"function":{"name":"large_image.tilesource.stylefuncs.maskPixelValues","context":true,"parameters":{"values":[82]}},"bands":[]}` (or, if you are using superpixels with boundaries, this would be `{"function":{"name":"large_image.tilesource.stylefuncs.maskPixelValues","context":true,"parameters":{"values":[164,165]}},"bands":[]}`). The resulting image (assuming you are returning a PNG), will be opaque black where this value is not present and transparent white where it is (or specify the `negative` and `positive` parameters to get different colors).
@naglepuff This should be useful in showing just the …

Use functions in styles.

---

sources/bioformats/setup.py

We had added scikit-image as a requirement to avoid a warning in PIMS, but the packages no longer pull that in, so this is no longer needed.

Remove an unneeded dependency.

---

CHANGELOG.md
girder/girder_large_image/__init__.py
girder/girder_large_image/constants.py
girder/girder_large_image/web_client/eventStream.js
girder/girder_large_image/web_client/main.js
girder/girder_large_image/web_client/templates/largeImageConfig.pug
girder/girder_large_image/web_client/views/configView.js
girder/test_girder/test_web_client.py

This is optional and can be changed in the plugin settings.

Add a polling fallback for when the server event stream is off

---

CHANGELOG.md
girder/girder_large_image/__init__.py
girder/girder_large_image/rest/__init__.py
girder/girder_large_image/web_client/main.js
girder/girder_large_image/web_client/package.json
girder/girder_large_image/web_client/stylesheets/itemViewCodemirror.styl
girder/girder_large_image/web_client/templates/itemViewCodemirror.pug
girder/girder_large_image/web_client/views/itemViewCodemirror.js
girder/test_girder/test_web_client.py
girder/test_girder/web_client_specs/otherFeatures.js

In the future, we might want to validate with a schema, too.

Show and edit yaml and json files using codemirror.

---

CHANGELOG.md
docs/girder_annotation_config_options.rst
girder_annotation/girder_large_image_annotation/rest/annotation.py
girder_annotation/girder_large_image_annotation/web_client/stylesheets/annotationListWidget.styl
girder_annotation/girder_large_image_annotation/web_client/templates/annotationListWidget.pug
girder_annotation/girder_large_image_annotation/web_client/views/annotationListWidget.js
girder_annotation/test_annotation/web_client_specs/annotationListSpec.js

This has a little preliminary work to add checkboxes to annotation lists, since that would make bulk modifications for some but not all annotations easier.

Add the ability to show annotation metadata in item annotation lists

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/handlers.py

download returns a forward on S3 assetstores.

Use open.read rather than download to access files in Girder.

---

girder_annotation/girder_large_image_annotation/web_client/views/annotationListWidget.js

Do not raise a login request when checking if the user can write annotations.

Do not raise an unneeded error.

---

large_image/tilesource/base.py
sources/multi/large_image_source_multi/__init__.py
test/test_source_ometiff.py

Also, add (axis)Set options for more precise control of multi sources.

Better control dtype on multi sources.

---

CHANGELOG.md
girder/girder_large_image/__init__.py
girder/girder_large_image/web_client/templates/itemViewCodemirror.pug
girder/girder_large_image/web_client/views/itemViewCodemirror.js

Set mime type for imported girder files

---

CHANGELOG.md
girder/girder_large_image/rest/large_image_resource.py
girder/girder_large_image/rest/tiles.py
girder_annotation/girder_large_image_annotation/rest/annotation.py

Without this, a token often needs user_auth access to do things where only read or read/write access is actually needed.

Add token scopes to girder endpoints.

---

CHANGELOG.md
README.rst
docs/index.rst
docs/make_docs.sh
girder/girder_large_image/rest/large_image_resource.py
requirements-dev-core.txt
requirements-dev.txt
requirements-worker.txt
setup.py
sources/dicom/large_image_source_dicom/__init__.py
sources/dicom/large_image_source_dicom/girder_source.py
sources/dicom/setup.py
sources/test/large_image_source_test/__init__.py
test/datastore.py
test/test_source_base.py

This uses wsidicom to read dicom files.  So far it has only been tested with files that were generated with the wsi2dcm docker from the 1.0.3 deb from https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter, which seems to have issues with some files.
This may be refactored to use a different base library, and internal details should be considered provisional.

Add a dicom source.

---

CHANGELOG.md
girder/girder_large_image/rest/large_image_resource.py
large_image/cache_util/__init__.py
sources/bioformats/large_image_source_bioformats/__init__.py
sources/nd2/large_image_source_nd2/__init__.py
sources/vips/large_image_source_vips/__init__.py

After opening some tile sources and then clearing cache and doing a gc.collect(), some file handles were still open (this can be checked via /proc/<pid>/fd).  This cures the test cases I've found _except_ for nd2 files that start to open and then fail.  I filed an issue with the nd2 reader about that.
The bioformats reader also has issues in this regard, which probably has something to do with the java library (not the python side of things).

Better release file handles

---

CHANGELOG.md
sources/multi/large_image_source_multi/__init__.py
sources/nd2/large_image_source_nd2/__init__.py

For nd2 files, this caches metadata computation.
For multi sources, this prefers a fast json parser if the file permits it.

Speed up loading or parsing some sources.

---

CHANGELOG.md
sources/vips/large_image_source_vips/__init__.py

When asking to output vips images as float32, they were being promoted to float64.

Better output new vips images as float32.

---

test/test_source_hdf5.py

The following variables can be adjusted for this test:
```
possible_axes = {
'x': [1, 10],
'y': [1, 10],
'c': [1, 100],
'z': [1, 100],
't': [1, 100],
'p': [1, 100],
'q': [1, 100],
's': [3, 3],
}
include_axes = {
'c': False,
'z': False,
't': False,
'p': False,
'q': False,
}
possible_data_ranges = [
[0, 1],
[0, 255],
[0, 65535],
[-1, 1]
]
max_tile_size = 100
tile_overlap_ratio = 0.5
```
More axes and higher numbers will take more computation time. The test succeeds if all extra axes (c, z, t, p, q) are disabled. Enabling any fourth axis after x, y, and s breaks the test because the image source is currently implemented with vips. The goal is to add implementation to the image source such that it can accept arbitrary axes and pass this test.

Write a test to generate n random tiles with m dimensions

---

test/test_source_base.py
test/test_source_hdf5.py

It seems to sometimes exhaust memory on CircleCI instances.

Clear the source cache on some tests to reduce memory use.

---

girder/girder_large_image/rest/__init__.py
girder/girder_large_image/web_client/stylesheets/itemList.styl
girder/girder_large_image/web_client/views/itemList.js
girder/test_girder/test_large_image.py
girder/test_girder/web_client_specs/imageViewerSpec.js

This will still list the folders.  All items within any of the child folders will be listed.  When a flat list of items is shown, selecting the "Check all" checkbox will only select items.

Add an option to flatten girder item lists.

---

CHANGELOG.md
girder/girder_large_image/web_client/templates/itemView.pug

When data was long, we needless checked its serialization length, which could be slow.

Speed up rendering Girder item page metadata in some instances

---

CHANGELOG.md
sources/multi/large_image_source_multi/__init__.py

When there was a background color, the axes were confused.

Fix an issue with non-square tiles in the multi source

---

CHANGELOG.md
docs/tilesource_options.rst
large_image/tilesource/base.py
test/test_source_openslide.py

This makes specifying ICC correction or not symmetric.  See the added docs.

Support a simple style for icc: true

---

docs/conf.py
docs/make_docs.sh
large_image/tilesource/utilities.py
tox.ini

The rtd theme's search was broken when Sphinx 6 was released in December 2022, requiring the addition of sphinxcontrib-jquery.
Also, fix a warning in the sphinx build.

Fix sphinx docs build.

---

large_image/tilesource/base.py

A simple addition to quickly preview a tile source in Jupyter:
| New | Classic |
|---|---|
| <img width="810" alt="Screen Shot 2023-02-14 at 9 40 26 PM" src="https://user-images.githubusercontent.com/22067021/218932515-a67e29f8-bd04-4211-a5f9-95e90bce9322.png"> |  <img width="857" alt="Screen Shot 2023-02-14 at 9 40 42 PM" src="https://user-images.githubusercontent.com/22067021/218932583-19dd6702-4aaf-4c1b-9f68-0865d4590a4d.png"> |
This is pretty standard for image-based libraries to create a user-friendly representation in Jupyter. See also https://github.com/python-pillow/Pillow/issues/1090
Note that this returns an `ImageBytes` object from #902

Add _repr_png_ for Jupyter

---

CHANGELOG.md
setup.py
sources/vips/setup.py

Fix how sources that don't work with older python verisons are referenced.

Fix how some sources are referenced in setup.py.

---

CHANGELOG.md
large_image/cache_util/cache.py
test/test_cache_source.py

This doesn't seem to be a problem in anything we are currently doing, but you can manually get a class instance that isn't distinct, so although this is listed as a bug fix, I don't think it has any external impact.

The cache could reuse a class inappropriately

---

CHANGELOG.md
large_image/cache_util/cache.py
large_image/tilesource/base.py
sources/vips/large_image_source_vips/__init__.py
test/test_pickle.py

This also supports pickling tiles from the tile iterator.
Closes #1069.

Support pickling sources.

---

CHANGELOG.md
sources/bioformats/large_image_source_bioformats/__init__.py
sources/vips/large_image_source_vips/__init__.py

Also, don't report a scale from vips if the values are the defaults.

Extract scale information from more bioformats files

---

CHANGELOG.md
requirements-dev.txt
requirements-test-core.txt
requirements-test.txt
sources/pil/large_image_source_pil/__init__.py
sources/pil/setup.py
test/test_source_base.py

Read some additional formats with the PIL source if extra modules are installed.

Support multi-frame PIL sources.

---

CHANGELOG.md
girder/girder_large_image/models/image_item.py
girder/test_girder/test_large_image.py
test/test_source_base.py

Some item functions are cached, like histograms, tile frames, and thumbnails.  These can be expensive.  Before, if a client asked for an expensive function and a second client asked for the same function before the first completed, it would compute it twice.  Now, the second call waits for the first to complete and then reads from the cache.

Reduce duplicate computation of expensive cached values.

---

girder/test_girder/web_client_specs/imageViewerSpec.js

We have transient failures on the imageViewerSpec test.  If this is purely a short-term occasional timeout, this change may help.

Try to harden one of the tests.

---

CHANGELOG.md
large_image/cache_util/memcache.py

As we expose the ability to restyle tile sources more easily, it is somehow easier to cause the python memcached client to lose connection.  This reconnects if possible.

Reconnect to memcached if the connection fails

---

large_image/tilesource/base.py
large_image/tilesource/utilities.py
sources/gdal/large_image_source_gdal/__init__.py
sources/mapnik/large_image_source_mapnik/__init__.py

Adds `_repr_json_` for metadata and style (as both are JSON serializable objects) to improve representation in Jupyter (see screenshot). Further, this adds `metadata` and `style` properties to `TileSource` to improve access and prevent a user from setting these properties improperly.
The `style` property is a start to what is mentioned in #1119

Improve access and repr of metadata and style

---

setup.py

This is a soft dependency and the only one that isn't readily available in the most minimal Python environments (pyodide). 
Removing psutil should make the following source modules installable in pyodide (from a quick glance at dependencies... need to verify these actually work though)
- large-image-source-deepzoom
- large-image-source-dicom
- large-image-source-openjpeg
- large-image-source-pil
- large-image-source-vips
- large-image-source-tifffile
It is well handled if psutil is missing:
https://github.com/girder/large_image/blob/f7e664ad406e70538a52af2901ed44bb798d7e0f/large_image/cache_util/cachefactory.py#L96-L99
and the only other place it is used is in `large-image-converter` (and the girder modules) which has it as a hard dependency: …

Remove psutil hard dependency

---

.git-blame-ignore-revs
girder/girder_large_image/web_client/package.json
girder/girder_large_image/web_client/stylesheets/fileList.styl
girder/girder_large_image/web_client/stylesheets/imageViewerSelectWidget.styl
girder/girder_large_image/web_client/stylesheets/itemList.styl
girder/girder_large_image/web_client/stylesheets/itemView.styl
girder_annotation/girder_large_image_annotation/web_client/package.json
girder_annotation/girder_large_image_annotation/web_client/stylesheets/annotationListWidget.styl
girder_annotation/girder_large_image_annotation/web_client/stylesheets/itemList.styl

This still depends on stylint, so it doesn't address any outdated package issues.
The main benefit is we can auto-format stylus files.

Use stylus-supremacy for linting and reformating stylus files

---

CHANGELOG.md
girder/girder_large_image/models/image_item.py
large_image/cache_util/cache.py
large_image/tilesource/base.py

If multiple threads are styling tiles, it was possible for the tile cache key to be erroneous due to the styler fetching the "unstyled" tile and a second thread fetching the tile cache reference based on the name of the unstyled class rather than the styled class.

Fix a bug with caching tiles and styling.

---

girder/girder_large_image/rest/__init__.py
girder/girder_large_image/web_client/views/itemList.js

Before, item lists that were configured using the .large_image_config.yaml file could be filtered based on substring searches.  This allows also specifying column names and negations. There is a tool tip explaining the options.

Allow more sophisticated filtering on item lists.

---

girder_annotation/girder_large_image_annotation/models/annotationelement.py

Some managed mongoDB providers limit index name lengths, and multi-column indexes' default names may exceed this.

Add manual index names where index names might get too long

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/rest/annotation.py
girder_annotation/test_annotation/test_annotations_rest.py

This also adds some better tests.

Avoid using $unionWith as it isn't supported some places

---

large_image/tilesource/geo.py
sources/rasterio/large_image_source_rasterio/__init__.py

Draft work to remove the `rasterio` source module's dependence on `pyproj`.
Considering how easy it is to install `pyproj` these days, I don't think this is totally necessary but it's probably best to have the rasterio source module use `rasterio` directly for everything rather than pulling an additional dependency.
There is still one remaining function `getPixelSizeInMeters()` that I wasn't immediately sure on how to reproduce with `rasterio`

Remove rasterio dep on pyproj

---

girder/girder_large_image/__init__.py
girder/girder_large_image/models/image_item.py
large_image/tilesource/base.py

Also log slow histograms.
Note that the logs will be somewhat more chatty at info level and very noisy at debug level.

Log more often when importing files or making large images.

---

large_image/tilesource/geo.py

Fixes issue if pyproj isn't installed
```
File ~/miniconda3/envs/venv/lib/python3.11/site-packages/large_image/tilesource/geo.py:230, in GDALBaseFileTileSource.getPixelSizeInMeters(self)
223 def getPixelSizeInMeters(self):
224     """
225     Get the approximate base pixel size in meters.  This is calculated as
226     the average scale of the four edges in the WGS84 ellipsoid.
227 
228     :returns: the pixel size in meters or None.
229     """
--> 230     bounds = self.getBounds(NeededInitPrefix + 'epsg:4326')
231     if not bounds:
232         return
NameError: name 'NeededInitPrefix' is not defined
```

Fix NeededInitPrefix namepsace errors

---

CHANGELOG.md
large_image/tilesource/__init__.py
test/datastore.py
test/test_source_base.py

This increases the priority of matching file extensions and mimetypes above non-matching values, even if the fallback is high priority.
This doesn't change the default source for any of our test files.

Change how extensions and fallback priorities interact

---

CHANGELOG.md
girder/girder_large_image/web_client/views/configView.js
girder/girder_large_image/web_client/views/itemList.js
girder_annotation/girder_large_image_annotation/web_client/views/annotationListWidget.js

We aim to use this file in more places and want to avoid duplicating the reader code.

Refactor reading the .large_image_config.yaml file

---

CHANGELOG.md
large_image/tilesource/__init__.py
large_image/tilesource/base.py
sources/dicom/large_image_source_dicom/__init__.py

When there are multiple files in the same directory, we check if they can be used together as different levels of the same dicom.  This was done by extension, but some dicoms have the name structure of `DCM_<number>` without extension.

Improve dicom multi level detection

---

CHANGELOG.md
girder/girder_large_image/models/image_item.py
sources/bioformats/large_image_source_bioformats/__init__.py
sources/dicom/large_image_source_dicom/__init__.py
sources/openjpeg/large_image_source_openjpeg/__init__.py
sources/openslide/large_image_source_openslide/__init__.py
sources/tiff/large_image_source_tiff/__init__.py
sources/tifffile/large_image_source_tifffile/__init__.py

This adds an unofficial value to some tile sources of _populatedLevels, which, if set, reports how many actual image levels are used by the source.  Not all sources can report this; some additional ones probably could.  This is primarily useful in determining why some files are slow.

Report actual populated image levels

---

CHANGELOG.md
docs/tilesource_options.rst
large_image/tilesource/base.py
large_image/tilesource/geo.py
test/test_source_openslide.py

This overrides the default style on geospatial sources, allowing getting the unstyled histogram or other data.

Allow specifying an empty style dict.

---

CHANGELOG.md
girder/girder_large_image/rest/tiles.py
girder/test_girder/test_tiles_rest.py
large_image/tilesource/base.py
test/test_source_tiff.py

For integer data types, using full bin counts can result in jagged looking results because some bins will have fewer or no discrete values than others.

Allow rounding histogram bin edges and reducing bin counts

---

CHANGELOG.md
sources/nd2/large_image_source_nd2/__init__.py

This also adapts to changes in the library that is used for reading such files.

Harden the nd2 source to allow it to read more files.

---

CHANGELOG.md
girder/girder_large_image/girder_tilesource.py
sources/ometiff/large_image_source_ometiff/__init__.py
sources/tifffile/large_image_source_tifffile/__init__.py

This also resolves some ambiguity between ometiff and tiff source priorities

Change how extensions and fallback priorities in Girder interact

---

CHANGELOG.md
girder/girder_large_image/web_client/views/imageViewerWidget/setFrameQuad.js
large_image/tilesource/utilities.py
test/test_source_base.py

For images with lots of frames, a large value preserves quick resolution, but browsers are glacial at decoding large images.  This attempts to adjust the balance.

Reduce the default max texture size for frame quads.

---

CHANGELOG.md
large_image/tilesource/base.py
sources/gdal/large_image_source_gdal/__init__.py
sources/rasterio/large_image_source_rasterio/__init__.py
sources/tiff/large_image_source_tiff/__init__.py
sources/tiff/large_image_source_tiff/tiff_reader.py
sources/tifffile/large_image_source_tifffile/__init__.py
test/test_source_base.py

This also fixes reporting dtype on some geospatial sources.
This is now reported in the metadata.

Add tile source bandCount attribute

---

docs/example_usage.rst

Updated example_usage.rst for typo

---

CHANGELOG.md
large_image/cache_util/cache.py
large_image/tilesource/base.py
sources/rasterio/large_image_source_rasterio/__init__.py

Just reference the unstyled instance directly.  This improves speed by reducing locking.

Simplify style locking.

---

girder/girder_large_image/web_client/vue/components/CompositeLayers.vue
girder/girder_large_image/web_client/vue/components/DualInput.vue
girder/girder_large_image/web_client/vue/components/FrameSelector.vue
girder/girder_large_image/web_client/vue/components/HistogramEditor.vue
girder/girder_large_image/web_client/vue/utils/colors.js

Resolves #1211 
Resolves #1217 
Resolves #1219

Channel colors & sliders

---

sources/rasterio/setup.py

rio-cog uses mercantile which uses pydantic.  It requires pydantic < 2.

Pin pydantic for rio-cog

---

CHANGELOG.md
large_image/cache_util/cache.py

PR #1224 changed how unstyled data was accessed to reduce locking.  As a side effect, if you asked for the dtype from a source with a default style before asking for tile data, the result could be inconsistent. This fixes that.

Improve how dtypes are reported from #1224

---

girder/girder_large_image/web_client/vue/components/CompositeLayers.vue
girder/girder_large_image/web_client/vue/components/FrameSelector.vue

Frame selection keyboard shortcuts

---

CHANGELOG.md
girder/girder_large_image/web_client/vue/components/CompositeLayers.vue

slider is too generic; other girder plugins which don't scope properly can do odd things to the slider class.

Rename a css class.

---

CHANGELOG.md
girder/girder_large_image/__init__.py
girder/girder_large_image/models/image_item.py
girder/girder_large_image/rest/tiles.py
girder/girder_large_image/web_client/views/fileList.js
girder_annotation/girder_large_image_annotation/web_client/views/annotationListWidget.js
utilities/tasks/large_image_tasks/tasks.py

This makes it easier to force convert images that exist as multiple file images.  Before, the reconversion would be sent to a worker; now it can optionally use a local job which can take advantage of local or fuse paths.
Additionally, there is less code duplication.

Harmonize the girder code paths for image conversion

---

girder/girder_large_image/__init__.py
girder/girder_large_image/rest/item_meta.py
girder/girder_large_image/web_client/vue/components/CompositeLayers.vue
girder/girder_large_image/web_client/vue/components/DualInput.vue
girder/girder_large_image/web_client/vue/components/FrameSelector.vue
girder/girder_large_image/web_client/vue/components/PresetsMenu.vue

This PR adds a widget for Image View Presets on the righthand side of the image controls. 
The user doe the following: 
1. select from existing presets to apply one
2. use the plus button to name and save the current state as a new preset
3. delete the selected preset 
Requesting @manthey to take a look, since this will probably need a few iterations.

Create, select, and delete image view presets

---

CHANGELOG.md
girder/girder_large_image/rest/tiles.py
girder/test_girder/test_tiles_rest.py

This also allows attaching data to large_image files.
The core of this work is
```
datafile = Upload().uploadFromFile(
io.BytesIO(data), size=len(data),
name='_largeImageThumbnail', parentType='item', parent=item,
user=user, mimeType=mimeType, attachParent=True)
datafile.update({
'isLargeImageThumbnail' if thumbnail is not False else 'isLargeImageData': True,
'thumbnailKey': key,
})
datafile = File().save(datafile)
```
where `data` is the binary data to store, `item` is the girder item, and `key` is the standardizes key for the thumbnail/data (e.g., `{"height":100,"width":160}`, where order and spacing matter).
The new endpoint replaces an existing thumbnail or adds if it doesn't exist.

Add an endpoint to make it easier to replace thumbnails

---

docs/girder_config_options.rst
girder/girder_large_image/web_client/views/imageViewerSelectWidget.js
girder/girder_large_image/web_client/vue/components/CompositeLayers.vue
girder/girder_large_image/web_client/vue/components/FrameSelector.vue
girder/girder_large_image/web_client/vue/components/PresetsMenu.vue

This PR allows a user to specify image view presets in their `.large_image_config.yaml` configuration file at the folder level. Presets specified in the configuration file will be added to the presets available for every image in that folder (as long as the preset is applicable to that image). 
We can write more complicated logic for determining whether a preset is applicable to an image, but for now, the `presetApplicable` function simply evaluates whether the preset's `mode` and `frame` values are available for the image.
This PR also adds a section to the documentation explaining how to add presets to the configuration file. This section includes some basic example presets.

Presets from Large Image Configuration file

---

CHANGELOG.md
sources/vips/large_image_source_vips/__init__.py

On python 3.11 it is noisy on our test suite (maybe on other versions, too).

Reduce pyvips log level.

---

CHANGELOG.md
sources/nd2/large_image_source_nd2/__init__.py
sources/tiff/large_image_source_tiff/__init__.py

We were still using them to verify the file; this reduces overhead and prevents the dask threadpool from blocking girder restarts.

Don't use dask threads when using nd2 to fetch tiles

---

CHANGELOG.md
large_image/tilesource/base.py

This skips a numpy alloc and copy

Reduce memory allocation during some region tiling operations

---

CHANGELOG.md
large_image/tilesource/base.py

Specifically, when we apply a style, in some instances the tile or region is converted from one dtype to a float in order to preserve some of the transform properties through the process.  We had been using `float`, which internally is `np.float64`.  But, `np.float32` gives sufficient accuracy for our styles.  With this change, `np.float32` is used unless the base datatype is `float64`, in which we do not reduce the precision.

Reduce memory allocation during some styling operations

---

CHANGELOG.md
docs/config_options.rst
girder_annotation/girder_large_image_annotation/handlers.py
large_image/config.py
test/test_files/sample.girder.cfg

This had previously been hardcoded.
This can be adjusted in the girder.cfg file.

Added a max_annotation_input_file_length setting

---

CHANGELOG.md
girder/girder_large_image/web_client/package.json
girder/girder_large_image/web_client/views/imageViewerWidget/geojs.js

This has less conflicts with some other newer packages.

Use a newer version of the hammerjs touch events library in Girder

---

CHANGELOG.md
girder/girder_large_image/models/image_item.py
girder/girder_large_image/rest/tiles.py
girder/test_girder/test_tiles_rest.py
utilities/tasks/large_image_tasks/tasks.py

For multi-frame files, precomputing histograms can speed up UI.  This extends the Girder item/{id}/tiles/histogram option with another option.  If `cache=report`, a list corresponding to all frames is returned showing which frames have a histogram with the remaining API call parameters computed and cached.  If `cache=schedule`, if there are any such frames that are not cached (and eligible to be cached), then a local job is created to do so.
Note that histograms that use a range value other than the default or `round` are not cached.

Allow scheduling histogram computation

---

CHANGELOG.md
large_image/tilesource/base.py
test/test_source_base.py

If the first band used a different frame than subsequent bands, and subsequent bands repeated a frame, the wrong frame could be used in a style.

Band order could matter in styles

---

CHANGELOG.md
docs/config_options.rst
girder/girder_large_image/girder_tilesource.py
girder/girder_large_image/models/image_item.py
large_image/cache_util/cache.py
large_image/config.py
large_image/tilesource/__init__.py
large_image/tilesource/base.py
sources/dicom/large_image_source_dicom/__init__.py
sources/nd2/large_image_source_nd2/__init__.py
test/test_cache_source.py

When opening a tile source, pass `noCache=True`.  In this mode, the tile source can directly have its style modified (e.g., `source.style = <new value>`).  This is also used when importing images into girder to avoid flushing the cache of tile sources that are in active use.
This closes #1294.
This closes #1145.
There is a config value `cache_sources`, that, if False, makes `noCache` functionally default to False.
This closes #1206.

Add an option to not cache sources.

---

CHANGELOG.md
girder/girder_large_image/web_client/views/imageViewerWidget/slideatlas.js

This was one of the primary causes of transient client test failures. We should check if anyone actually uses this, and, if not, remove it from the default viewer list.

Change the cdn used with the SlideAtlas viewer.

---

.circleci/config.yml
CHANGELOG.md
test.Dockerfile

pyenv doesn't need the patch version anymore; it will just use the latest.

Update the test python versions.

---

docs/girder_config_options.rst
girder/girder_large_image/web_client/vue/components/PresetsMenu.vue

Resolves #1239 by completing the last requirement for the feature, a way to specify default presets.
A user may specify a list of preset names in order of precedence. The first applicable preset in the defaults list will be applied automatically.

Preset defaults

---

sources/dicom/large_image_source_dicom/__init__.py
sources/dicom/large_image_source_dicom/assetstore/__init__.py
sources/dicom/large_image_source_dicom/assetstore/dicomweb_assetstore_adapter.py
sources/dicom/large_image_source_dicom/assetstore/rest.py
sources/dicom/large_image_source_dicom/dicom_tags.py
sources/dicom/large_image_source_dicom/girder_plugin.py
sources/dicom/large_image_source_dicom/girder_source.py
sources/dicom/large_image_source_dicom/web_client/constants.js
sources/dicom/large_image_source_dicom/web_client/main.js
sources/dicom/large_image_source_dicom/web_client/models/AssetstoreModel.js
sources/dicom/large_image_source_dicom/web_client/package.json
sources/dicom/large_image_source_dicom/web_client/routes.js
sources/dicom/large_image_source_dicom/web_client/templates/assetstoreImport.pug
sources/dicom/large_image_source_dicom/web_client/templates/dicomwebAssetstoreCreate.pug
sources/dicom/large_image_source_dicom/web_client/templates/dicomwebAssetstoreEditFields.pug
sources/dicom/large_image_source_dicom/web_client/templates/dicomwebAssetstoreImportButton.pug
sources/dicom/large_image_source_dicom/web_client/templates/dicomwebAssetstoreMixins.pug
sources/dicom/large_image_source_dicom/web_client/views/AssetstoreImportView.js
sources/dicom/large_image_source_dicom/web_client/views/AssetstoresView.js
sources/dicom/large_image_source_dicom/web_client/views/EditAssetstoreWidget.js
sources/dicom/large_image_source_dicom/web_client/views/NewAssetstoreWidget.js
sources/dicom/setup.py
sources/dicom/test_dicom/test_web_client.py
sources/dicom/test_dicom/web_client_specs/dicomWebSpec.js
test/test_source_dicomweb.py
tox.ini

This creates a new DICOMweb assetstore that is used to track resources on a DICOMweb server. The user provides the DICOMweb server URL and optionally QIDO and WADO prefixes (if the server requires them). The user is then able to import references to the objects on the DICOMweb server.
The files that are created via this assetstore are able to be viewed with the dicom tile source, which has been extended to handle files on a DICOMweb server.
A test was also added that utilizes the public DICOMweb server located [here](https://imagingdatacommons.github.io/slim/).
There is still more work to do in future PRs, including:
* Adding a search/filter capability
* Adding authentication for non-public servers
* Query and store metadata from the DICOMweb objects
Fixes: #1204

Add initial DICOMweb support

---

CHANGELOG.md
sources/openslide/large_image_source_openslide/__init__.py

Before, this fell back to using libtiff, but now it uses PIL.  This reduces library interaction dependencies.

Refactor fetching extra associated images from openslide

---

.circleci/config.yml
tox.ini

This makes our reported coverage look lower, but after some codecov change we no longer were including js coverage.

Fix uploading javascript coverage to codecov

---

CHANGELOG.md
sources/ometiff/large_image_source_ometiff/__init__.py
sources/tiff/large_image_source_tiff/__init__.py

There is much we are doing with libtiff that could be switch to the python dictionaries returned by tifftools.  Would this speed things up in common use cases?  It would make a fallback to PIL if libtiff is unavailable easier.  Some of this refactor will make that easier to test.

Minor refactor of the how we access the tiff reader class.

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js

This adds support to the geojs image viewer widget to handle more types of regions.

Support more region shapes.

---

CHANGELOG.md
docs/tilesource_options.rst
large_image/tilesource/base.py
test/test_source_tiff.py

This maintains the original dtype even when compositing frames

Style can specify a dtype of 'source'

---

girder/girder_large_image/web_client/vue/components/CompositeLayers.vue
girder/girder_large_image/web_client/vue/components/DualInput.vue
girder/girder_large_image/web_client/vue/components/FrameSelector.vue
girder/girder_large_image/web_client/vue/components/HistogramEditor.vue
girder/girder_large_image/web_client/vue/utils/colors.js

Max Merge option in Frame Selector

---

CHANGELOG.md
large_image/tilesource/utilities.py
sources/tifffile/large_image_source_tifffile/__init__.py

Better detect when the tifffile source thinks there are associated images.
Improve vips format conversion.

Improve tifffile associated image detection.

---

.circleci/make_wheels.sh
.circleci/release_pypi.sh
CHANGELOG.md
README.rst
docs/index.rst
docs/make_docs.sh
requirements-dev.txt
requirements-test-core.txt
requirements-test.txt
setup.py
sources/bioformats/large_image_source_bioformats/__init__.py
sources/zarr/large_image_source_zarr/__init__.py
sources/zarr/large_image_source_zarr/girder_source.py
sources/zarr/setup.py
test/datastore.py
test/test_source_base.py

This mostly reads omezarr (ome-ngff).
If you have a zarr directory, you can convert it to a single file via code like:
```
import zarr
zarrsrc = zarr.open(<input directory>)
zarrstore = zarr.storage.SQLiteStore(<output path>)
zarrdest = zarr.open(store=zarrstore, mode='w')
zarr.copy_all(zarrsrc, zarrdest)
```
The input directory should have a .zgroup file in it.  The output directory is a sqlite3 db file, so perhaps is suffix should be `.db` or `.zarr`.  This also works with zipped zarr directories.

Add a Zarr tile source.

---

sources/dicom/large_image_source_dicom/assetstore/rest.py
sources/dicom/large_image_source_dicom/web_client/models/AssetstoreModel.js
sources/dicom/large_image_source_dicom/web_client/templates/dicomwebAssetstoreImportButton.pug
sources/dicom/large_image_source_dicom/web_client/views/AssetstoreImportView.js
sources/dicom/test_dicom/web_client_specs/dicomWebSpec.js

These changes standardize parameter names in accordance with the girder /assetstore/ api

Standardize DICOMweb assetstore parameter names/style

---

sources/dicom/large_image_source_dicom/assetstore/rest.py
sources/dicom/test_dicom/web_client_specs/dicomWebSpec.js

On the master branch, if I try to import with no limit set, I get the following error:
```
Invalid value for integer parameter limit: .
```
We should remove the datatype restriction and set the default to `None`. That way, it will work properly.

Default to "None" for the limit

---

CHANGELOG.md
girder/girder_large_image/web_client/webpack.helper.js

This reduces data transfer when showing large images in girder.

Use minified geojs

---

CHANGELOG.md
docs/girder_config_options.rst
girder/girder_large_image/web_client/stylesheets/itemList.styl
girder/girder_large_image/web_client/templates/itemList.pug
test/test_files/.large_image_config.yaml

The item list view can switch to a grid mode.
This could use some better styling for the column titles, for the short grid items, and for individual column entries in the grid view.

Configurable item list grid view

---

CHANGELOG.md
large_image/cache_util/cache.py

Broaden where a try/except decides to remove an invalid item from the cache.  Before, when a bad style was passed, the cache could end up with entries for that bad style, cycling the cache more than necessary.

Improve cache key guard

---

sources/dicom/large_image_source_dicom/__init__.py

As of the latest `wsidicom` release (0.13.0), the new `__init__` method just takes a `DICOMwebClient` object. The old `__init__` method was moved to the class method `create_client()`. So we need to update the way we initialize it.
In #1349, we are adding authentication where we create the DICOMwebClient object ourselves, so go ahead and do that now to simplify that one.

Update WsiDicomWebClient init call

---

sources/dicom/large_image_source_dicom/web_client/routes.js
sources/dicom/large_image_source_dicom/web_client/views/AssetstoresView.js
sources/dicom/large_image_source_dicom/web_client/views/DICOMwebImportView.js
sources/dicom/large_image_source_dicom/web_client/views/EditAssetstoreWidget.js
sources/dicom/large_image_source_dicom/web_client/views/NewAssetstoreWidget.js

Changed ambiguous DICOMweb assetstore classes to include references to DICOMweb for clarity.

Rename DICOMweb's AssetstoreImportView for clarity

---

CHANGELOG.md
large_image/tilesource/base.py
sources/bioformats/large_image_source_bioformats/__init__.py
sources/dicom/large_image_source_dicom/__init__.py
sources/openjpeg/large_image_source_openjpeg/__init__.py
sources/openslide/large_image_source_openslide/__init__.py
sources/tiff/large_image_source_tiff/__init__.py
sources/tifffile/large_image_source_tifffile/__init__.py
sources/zarr/large_image_source_zarr/__init__.py
test/datastore.py

When a tile source is missing many levels of tiles, it can use too much memory to read the next available resolution and scale from that directly.  This does that scaling in stages, if necessary.

General handling of skipped levels

---

sources/dicom/large_image_source_dicom/__init__.py
sources/dicom/large_image_source_dicom/assetstore/__init__.py
sources/dicom/large_image_source_dicom/assetstore/dicomweb_assetstore_adapter.py
sources/dicom/large_image_source_dicom/assetstore/rest.py
sources/dicom/large_image_source_dicom/girder_source.py
sources/dicom/large_image_source_dicom/web_client/templates/dicomwebAssetstoreCreate.pug
sources/dicom/large_image_source_dicom/web_client/templates/dicomwebAssetstoreEditFields.pug
sources/dicom/large_image_source_dicom/web_client/templates/dicomwebAssetstoreMixins.pug
sources/dicom/large_image_source_dicom/web_client/views/AuthOptions.js
sources/dicom/large_image_source_dicom/web_client/views/EditAssetstoreWidget.js
sources/dicom/large_image_source_dicom/web_client/views/NewAssetstoreWidget.js
sources/dicom/test_dicom/web_client_specs/dicomWebSpec.js

When the user is creating a DICOMweb assetstore, if they select the "token" authentication type, an input box will appear where the user must enter the token.
This token is saved in MongoDB, and is used for making all requests for this DICOMweb assetstore. That includes requests for importing the data (which may only be done by an admin), and requests for viewing the data (which may be done by anyone with access to the folder).
If an admin wishes to restrict users from viewing DICOMweb assets that were imported using this token, the admin must restrict access to the imported items via girder's folder access controls.
Fixes: #1313
Depends on: imi-bigpicture/wsidicom#117

Add token authentication option for DICOMweb

---

girder/girder_large_image/web_client/vue/components/CompositeLayers.vue
girder/girder_large_image/web_client/vue/components/FrameSelector.vue
girder/girder_large_image/web_client/vue/utils/colors.js

A user found that two channels called "DAPI" and "DAPI 1" are both assigned the same color. This is because they both match the following regex: `'^DAPI.*$'`. Only the first match should receive the mapped color for that regex.
This PR adds a check to the `getChannelColor` function that the color does not already exist in a list of used colors.

Frame Selector component: ensure that no color can be assigned twice

---

girder/girder_large_image/web_client/vue/components/PresetsMenu.vue

Resolves #1394.
There are two ways a band object can express autoRanging:
1. {min: 'min:0.002', max: 'max:0.002'}
2. {autoRange: 0.2}
After #1306, the `currentStyle` passed to `PresetsMenu` will always be in the first format. This PR converts those bands to the second format before saving the preset, since we document the preset specification with `autoRange`.

Frame Selector component: Auto-Range format for saving presets

---

sources/dicom/large_image_source_dicom/__init__.py
sources/dicom/large_image_source_dicom/assetstore/dicomweb_assetstore_adapter.py
sources/dicom/large_image_source_dicom/dicom_metadata.py
sources/dicom/large_image_source_dicom/dicomweb_utils.py
sources/dicom/large_image_source_dicom/girder_source.py
test/test_source_dicomweb.py

When DICOMweb series are imported, several metadata entries from each series are now extracted and set on the item metadata.
We are extracting most of the metadata that is displayed in the SLIM viewer: https://imagingdatacommons.github.io/slim/
Most of the metadata entries are available as series-level metadata items. However, some of the metadata entries are only available on the instances themselves (in particular, the "Specimen" information, which is nested several dataset layers deep).
The SLIM viewer sets most of its metadata by locating the first WSI Volume dataset, and using that (it appears that the metadata for WSI volume datasets in a series are almost completely identical to other WSI volume datasets in the series). We are also using that approach here.
We are using a slightly …

Read and set several metadata items, if available

---

sources/dicom/large_image_source_dicom/__init__.py
sources/dicom/setup.py
sources/dicom/test_dicom/test_web_client.py
test/test_source_dicomweb.py

wsidicom now determines the transfer syntax automatically, as of version 0.14.0, so we don't need to do this anymore.
wsidicom also supports more transfer syntaxes as well, so the list of transfer syntaxes we had are not complete now either. Just remove this logic and let wsidicom take care of it.
wsidicom now has optional dependencies: imagecodecs and pylibjpeg-rle. If we install those optional dependencies, it adds support for several more transfer syntaxes. Those are found [here](https://github.com/imi-bigpicture/wsidicom#limitations).
Fixes: #1308

Remove logic for determining transfer syntax

---

CHANGELOG.md
large_image/tilesource/tiledict.py
large_image/tilesource/utilities.py
sources/dicom/large_image_source_dicom/dicom_metadata.py
sources/multi/large_image_source_multi/__init__.py

Skip a decode step if possible; use simplejpeg for decoding when available and appropriate.

Speed up tile output.

---

sources/dicom/test_dicom/test_web_client.py
test/test_source_dicomweb.py

The server we were using for testing is down.
@psavery I'm disabling these for now so I can merge some other PRs.  We can reenable it when it is back or we change the tests.

Skip dicom web tests for now.

---

CHANGELOG.md
large_image/tilesource/base.py
large_image/tilesource/tiledict.py

Reduce the chance of multiple image decodes.
When asking for numpy arrays on a tile iterator, the tiles could be fetched as formats other than a numpy array.  This meant that the conversion to a numpy array was not cached; this change makes it so that the conversion is cached.

Speed up some tile iteration

---

CHANGELOG.md
sources/gdal/large_image_source_gdal/__init__.py

This shouldn't be in the core metadata; it has been moved to the internal metadata.

Shift where netcdf information is reported.

---

sources/gdal/large_image_source_gdal/__init__.py
sources/rasterio/large_image_source_rasterio/__init__.py

This PR prevents the occurrence of `ValueError: Out of range float values are not JSON compliant` when using GDAL or rasterio sources.

Remove NaN values from band information for JSON serializability

---

CHANGELOG.md
sources/ometiff/large_image_source_ometiff/__init__.py
sources/tiff/large_image_source_tiff/__init__.py
sources/tiff/large_image_source_tiff/tiff_reader.py

Specifically, if we want a numpy array, reading a jpeg encoded tile as the raw image bytes and then decoding it with simplejpeg or PIL is slower than having libtiff decode it.  If, however, we want to serve a jpeg, it is quicker to never decode it, so this code path remains the same.

Optimizing when reading arrays rather than images from tiff files

---

.circleci/config.yml
.circleci/dcm4chee/docker-compose.env
.circleci/dcm4chee/docker-compose.yml
.circleci/dcm4chee/upload_example_data.py
sources/dicom/test_dicom/test_web_client.py
sources/dicom/test_dicom/web_client_specs/dicomWebSpec.js
test/test_source_dicomweb.py
tox.ini

In CircleCI, this PR spins up a local DCM4CHEE server and uploads example DICOM files to it. This server is then used for the DICOMweb tests.
~~This is almost working. The DICOMweb tests are still skipped, and I need to get the `DICOMWEB_TEST_URL` environment variable to propagate to the pytests...~~
~~The `DICOMWEB_TEST_URL` is now being passed via tox's `passenv`. However, I still need to access the environment variable in the JavaScript test. I tried to do so via `process.env`, but it is apparently not there...~~
We made the JavaScript spec file into a simple template and inserted the `DICOMWEB_TEST_URL` into it before running it.
This is ready!

Add DCM4CHEE server for DICOMweb tests in CircleCI

---

.circleci/config.yml

This increase parallelism and keeps tests further from CI memory limits.

Use the large resource class in circleci

---

.circleci/config.yml
.pre-commit-config.yaml
requirements-test-core.txt
test/datastore.py
test/lisource_compare.py
tox.ini

This opens all of the test files and one remote url, testing how each opens with each tile source.  This is mainly used for comparative analysis, though it should never have failures.

Compare sources on test files.

---

.circleci/config.yml
.circleci/dcm4chee/upload_example_data.py
CHANGELOG.md
large_image/config.py
large_image/exceptions.py
large_image/tilesource/__init__.py
large_image/tilesource/base.py
sources/dicom/large_image_source_dicom/__init__.py
sources/dicom/test_dicom/test_web_client.py
tox.ini

We need to drop support for older pythons for this to be useful.
After running `tox -e monkeytype-py311`, you can then list which modules have type data via `build/tox/monkeytype-py311/bin/monkeytype list-modules` and apply the type annotations to a specific modules with `build/tox/monkeytype-py311/bin/monkeytype apply <module>`.
Check types using `tox -e type`.
The next steps are to turn on a few more mypy warnings, then start adding types to more of the source files.

Start adding types using monkeytype.

---

sources/dicom/large_image_source_dicom/assetstore/dicomweb_assetstore_adapter.py
sources/dicom/large_image_source_dicom/girder_source.py
sources/dicom/test_dicom/web_client_specs/dicomWebSpec.js

Each girder item represents a series. Previously, each item would contain a single file with the same name.
Now, each instance (DICOM file) within a series is represented by separate girder files within the item.
This PR includes download support, so individual DICOM files can be downloaded, or all DICOM files in a series can be downloaded together by downloading the girder item.
Range requests for the DICOM files are attempted if requested. However, the DICOMweb standard doesn't guarantee that they will be supported, and none of the DICOMweb servers we have tried have supported range requests for DICOM files.
To do:
Fixes: #1309

Add support for downloading DICOMweb files

---

.circleci/config.yml
.circleci/dcm4chee/auth-docker-compose.yml
.circleci/dcm4chee/create_keycloak_token.py
.circleci/dcm4chee/docker-compose.env
.circleci/dcm4chee/docker-compose.yml
.circleci/dcm4chee/update_access_token_lifespan.py
.circleci/dcm4chee/upload_example_data.py
sources/dicom/test_dicom/test_web_client.py
sources/dicom/test_dicom/web_client_specs/dicomWebSpec.js
test/test_source_dicomweb.py
tox.ini

This adds an additional docker-compose yaml, `auth-docker-compose.yml`, which spins up a dcm4chee server that requires authentication via keycloak. This authenticated server is now being used for the CircleCI testing.
This PR also adds a couple of scripts to work with this server, including an `update_access_token_lifespan.py` script (with the default access token lifespan of 10 minutes, the token would expire before it would be tested in the CI), and a `create_keycloak_token.py` script, which is used to create the access token that we provide to the assetstore.
Since we may want to perform local testing without authentication, the non-authenticated dcm4chee docker-compose is still there. The testing code checks for a `DICOMWEB_TEST_TOKEN` environment variable, where it expects to find a …

Add authentication to DICOMweb testing

---

sources/dicom/large_image_source_dicom/assetstore/dicomweb_assetstore_adapter.py
sources/dicom/test_dicom/web_client_specs/dicomWebSpec.js

When a range request is made or a fuse mount is attempted, we compute the size of the DICOM file. Currently, the only reliable way that we know to do this is by streaming the whole file and counting the bytes read.
After the file size is computed, it is stored in `file['size']` so it does not need to be computed again. Then, the range requests can be successfully made, complete with accurate `Content-Length` and `Content-Range` headers.

Add support for DICOMweb range requests

---

CHANGELOG.md
sources/multi/large_image_source_multi/__init__.py

One of the checks was disabled.

Fix an issue in PR #1447.

---

CHANGELOG.md
large_image/tilesource/utilities.py
sources/multi/large_image_source_multi/__init__.py

Fix an issue with compositing sources in the multi source caused by alpha range.  We composite tiles using pre-multiplied alpha values. When we have 8 bit images and apply an affine transform, we do this in float precision so that compositing does not lose precision prematurely. The function fullAlphaValue is used to determine the range of the alpha values we expect; for uint8 this is 255, for float it is 1.  Since the values have been cast to float but NOT scaled, this ends up with the wrong values.  Functionally, this was multiplying incomplete tiles by 255 and then taking the low 8 bits of the resultant integer cast, which looked like nonsense.

Fix compositing multi source with alpha

---

CHANGELOG.md
sources/openslide/large_image_source_openslide/__init__.py

Occasionally the openslide library fails to read from a tiff directory.  This adds a reconnect and retry loop to make it more robust.

Retry read_region if openslide reports an error

---

CHANGELOG.md
README.rst
utilities/converter/setup.py

Make GDAL an optional dependency for the converter

---

girder/girder_large_image/web_client/vue/components/CompositeLayers.vue
girder/girder_large_image/web_client/vue/components/FrameSelector.vue
girder/girder_large_image/web_client/vue/components/HistogramEditor.vue

Resolves #1458. 
After viewing the histograms in channel compositing mode, those histogram components still exist after switching to band compositing mode. The instances for the channel compositing table are invisible, but still send requests with a `framedelta` every time the `currentFrame` changes. 
This PR prevents sending histogram requests while the parent compositing table of the histogram component is not active.
One additional change enables band compositing on images with greater than 4 bands without assigned names; default names are assigned.

Fix histogram request bug in band compositing mode

---

test/test_source_dicomweb.py

It appears that somewhere upstream, the exact text changed when a 401 "Unauthorized" error is printed.
Rather than expecting the text to stay the same, let's just check for "401" in the string instead...

Simplify check for 401 error message in test

---

sources/dicom/large_image_source_dicom/assetstore/dicomweb_assetstore_adapter.py
sources/dicom/large_image_source_dicom/assetstore/rest.py
sources/dicom/large_image_source_dicom/dicomweb_utils.py
sources/dicom/large_image_source_dicom/web_client/templates/assetstoreImport.pug
sources/dicom/test_dicom/web_client_specs/dicomWebSpec.js

The NCI's [Imaging Data Commons](https://datacommons.cancer.gov/repository/imaging-data-commons) is a big repository (>38k studies) for cancer research. For the DICOMweb server, it uses Google's Cloud Healthcare API behind a proxy. This DICOMweb server sometimes behaves differently than the dcm4chee server we have been testing with.
This PR fixes a couple of issues we encountered. One of which is that we cannot use the `SOPClassUID` as a search filter (even though the [DICOMweb standard](https://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_10.6.html) indicates that it should be supported when searching for instances). We can perform manual filtering instead, however.
This PR also adds a default limit to the import page (which is required for importing from IDC), and a …

Add support for Imaging Data Commons

---

CHANGELOG.md
large_image/cache_util/cache.py
large_image/config.py
large_image/tilesource/tiledict.py
sources/tiff/large_image_source_tiff/tiff_reader.py

In one test, this reduces tiling time by about 8% when running a tile iterator on a tile that is slightly smaller than the native size (224 square rather than 240 square).  Of the time reduction, some of the speed is based on non-format specific gains and some specifically on the tiff tile source; roughly 3% is the non-format specific, and 5% is tiff specific.
Note that these gains become less significant as tile size goes up.

Speed up some retiling

---

CHANGELOG.md
sources/openslide/large_image_source_openslide/__init__.py

Add a guard when reading incorrect associated images

---

CHANGELOG.md
sources/multi/large_image_source_multi/__init__.py
test/test_source_multi.py

This relaxes the schema requirements to allow specifying values for alternate named axes (e.g., 'v: 5').

Allow alternate name axes in the multi source schema

---

CHANGELOG.md
large_image/tilesource/__init__.py
large_image/tilesource/base.py
sources/vips/large_image_source_vips/__init__.py
sources/zarr/large_image_source_zarr/__init__.py
test/test_source_vips.py

This makes it so `large_image.new()` will pick our preferred sink (zarr over vips, since it is more capable).

Prioritize tile sinks

---

.pre-commit-config.yaml
CHANGELOG.md
pyproject.toml
sources/bioformats/large_image_source_bioformats/__init__.py
tox.ini

When bioformats tries to open a zip file, it opens the file once per internal file.  If it fails to find a file that can be opened within the zip, it throws an error and leaves all of the file handles open.  By dividing the reader into more steps, we can ask to open an empty file, which somehow releases the file handles.  This happens with non-zip files, though it is less problematic.

Reduce bioformats keeping file handles open

---

sources/zarr/setup.py

The large-image-converter is needed when writing zarr sinks to tiff.

Add an extras require to the zarr source for conversion

---

examples/algorithm_progression.py

When multiprocessing, restart workers to keep memory usage down.

In algorithm example, specify max tasks per worker

---

CHANGELOG.md
sources/multi/large_image_source_multi/__init__.py
sources/tifffile/large_image_source_tifffile/__init__.py

For small tifffile arrays, use them directly rather than with zarr access.
Note which source was used to open a file in the multisource source so if it needs to be reopened, we can do so more efficiently.

Speed up some tifffile and multi source access cases

---

test.Dockerfile

This has to remove the default ubuntu user to be compatible with how other tools consume the test docker image.

Upgrade base ubuntu used for the test.Dockerfile.

---

sources/multi/large_image_source_multi/__init__.py

Made sure that `_addSourceToTile`'s `sourceTile` is being cast to the proper dtype for the tilesource. Previously all `sourceTile`s defaulted to `float32` which caused certain issues with compositing (and contributed to the bug below).
Removed `self.dtype` references from `_mergeTiles` in lieu of the appropriate types recovered from the `sourceTile` changes. Using `self.dtype` here was causing issues for edge cases with alpha compositing. In `TileSource.dtype`, the `_dtype` value is set to `'check'` temporarily to let the code sample a tile with `getRegion` (which typically needs a temp value for metadata checks); however, with `MultiFileTileSource`, the `dtype` was needed for `getRegion` sampling in a meaningful capacity (here with the `fullAlphaValue` calls) so a `dtype = 'check'` …

Fix multisource dtype bugs

---

CHANGELOG.md
girder/girder_large_image/rest/large_image_resource.py

When running a job via the PUT large_image/thumbnails endpoint, run it as an independent thread so other local asynchronous jobs are not delayed.

Thumbnail generation jobs are less blocking

---

CHANGELOG.md
examples/algorithm_progression.py
girder/girder_large_image/rest/large_image_resource.py
girder_annotation/girder_large_image_annotation/models/annotationelement.py
large_image/cache_util/cachefactory.py
large_image/config.py
large_image/tilesource/base.py
large_image/tilesource/utilities.py
sources/openjpeg/large_image_source_openjpeg/__init__.py
utilities/converter/large_image_converter/__init__.py

Use cgroup information if proc has it available.

Better detect available memory in containers.

---

sources/zarr/large_image_source_zarr/__init__.py

There isn't anything actionable until zarr 3 and zarr-sqlitestore are released.

Suppress a zarr warning.

---

CHANGELOG.md
sources/multi/large_image_source_multi/__init__.py
test/test_files/multi_test_source_style.yml
test/test_source_multi.py
tox.ini

This allows better control over how files with styled sources are rendered.

Add the ability to specify the dtype of a multi-source file.

---

CHANGELOG.md
sources/openslide/large_image_source_openslide/__init__.py

Handle bounds on openslide sources to handle sparse sources

---

.circleci/config.yml
CHANGELOG.md
tox.ini

This should speed up python 3.12 tests with coverage.  See https://github.com/nedbat/coveragepy/pull/1747

Switch to using COVERAGE_CORE=sysmon

---

CHANGELOG.md
girder/girder_large_image/__init__.py
girder/girder_large_image/girder_tilesource.py
sources/bioformats/large_image_source_bioformats/__init__.py
sources/openslide/large_image_source_openslide/__init__.py

Some file formats (mrxs, vsi) include folders of files and a root file. These need to be processed after all files are present, not when just the root file is present.  This change checks for a named file within the folder and, if present and not a large image, checks if the parent item exists and is not a large image.

Better handle images that are composed of a folder and an item.

---

CHANGELOG.md
utilities/converter/large_image_converter/__init__.py

Prevent using vips input in image conversion if vips parses the image as a different size than large_image

Fix when vips is preferred to read images in conversion

---

girder/girder_large_image/web_client/package.json

Adding extra white space into html can change the meaning; don't required that in vue components.

Turn off a linting rule that changes code

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/rest/annotation.py
girder_annotation/girder_large_image_annotation/utils/__init__.py

This adds two endpoints to list and get plottable data associated with an item.  It searches for plottable data in (a) folder metadata, (b) item metadata, (c) annotation attributes, (d) annotation element bounding boxes and user properties.  It can scan adjacent items for additional plottable data and restrict to specific annotations.  For adjacent items, annotations are matched by more recent matching name.
This needs better documentation and tests.
Eventually, we want to also ingest plottable data from csv/excel/dataframe files that are adjacent to the item.
This should be considered provisional for the moment; even if merged it is likely to change before settling on a final form.

Get all plottable data

---

CHANGELOG.md
girder/girder_large_image/__init__.py
girder/girder_large_image/girder_tilesource.py
utilities/tasks/large_image_tasks/tasks.py

This improves the ability to read multi-image file formats where the reader doesn't know about girder's item-as-folder resource paths. Specifically, formats like vsi that are imported from S3 mounts will now be properly accessible with this change.

Use flat mount paths where possible.

---

girder/girder_large_image/rest/__init__.py
girder/girder_large_image/rest/large_image_resource.py
girder/test_girder/test_large_image.py

This adds an endpoint that creates large images for an entire folder, as mentioned [here](https://github.com/girder/large_image/issues/1139). It iterates through the folder's items, skips over items with a large image already and creates a large image for the items without one. It has several options, one that recurses child folders, a second that creates a job for each large image item, and another that makes the jobs local.
This does not yet retry creating large images for items with an unfinished large image, but seemed to be a good start.

Create new large images for each item in a folder

---

CHANGELOG.md
sources/gdal/large_image_source_gdal/__init__.py
sources/multi/large_image_source_multi/__init__.py
sources/openjpeg/large_image_source_openjpeg/__init__.py
sources/rasterio/large_image_source_rasterio/__init__.py
sources/tifffile/large_image_source_tifffile/__init__.py
sources/zarr/large_image_source_zarr/__init__.py

If using large_image as a python library to open a single file, this speed up initial time to reading the image.  For deployments like girder, this has no benefit.

Have many sources use lazy imports

---

sources/zarr/large_image_source_zarr/__init__.py
test/test_pickle.py
test/test_sink.py

In addition to the zarr sink being compatible with multithreading, this PR makes the zarr sink compatible with multiprocessing. This is accomplished by the following:
-  splitting the `addLock` into `threadLock` and `processLock` (each a different class)
-  changing how a zarr sink is initialized from a path; now made more predictable by using `os.tempdir` as the root rather than a generated `tempdir.TemporaryDirectory()` and opened with "append" mode via zarr
- removing the clause to set `self.unpickleable = True`
- adding a pytest to check the behavior of both multithreading and multiprocessing cases
With this addition, there continues to be the caveat that the size of the whole image must be known before any multiprocessing or multithreading can work. The image size cannot be changed …

Zarr Sink Multiprocessing

---

CHANGELOG.md
large_image/tilesource/geo.py
sources/gdal/large_image_source_gdal/__init__.py
sources/gdal/setup.py
sources/mapnik/large_image_source_mapnik/__init__.py

Specifically, this expects a modern version of pyproj for the geospatial packages.

Clean up old code by requiring somewhat new packages

---

CHANGELOG.md
large_image/tilesource/__init__.py

This has the benefit that if no geospatial sources are being used, even if they are available in the system, the check can be skipped.

Allow checking for geospatial sources to use a specific source list

---

sources/zarr/large_image_source_zarr/__init__.py

The future warnings are just noise until there are new packages available

Better filter out zarr warnings

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/utils/__init__.py
girder_annotation/test_annotation/test_annotations.py

Add some basic plottable access tests.

Make the plottable data class thread safe.

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/models/annotation.py

Use aggregation pipelines rather than plain queries.

Speed up checks for old annotations.

---

CHANGELOG.md
girder/girder_large_image/models/image_item.py

They aren't rendered correctly.  Apparently pulling in a 303 redirect on a texture image doesn't work as expected.

Don't redirect tile frame images via 303

---

large_image/tilesource/jupyter.py
test/test_jupyter.py

This PR modifies the IPyLeaflet `Map` class in `large_image/tilesource/jupyter.py` to add a frame slider above the map component for multiframe images.
https://github.com/user-attachments/assets/7ed70e2a-ec83-4870-85d1-75858167cad2

Add frame slider to IPyLeaflet widget

---

.circleci/config.yml
docs/girder_config_options.rst
tox.ini

@annehaley It occurred to me that we should test the links that the documentation generates to ensure that they go to actual destinations.  I added a test as part of building the docs with tox.

Use linkchecker to verify all docs links

---

girder/girder_large_image/rest/large_image_resource.py

This adds two more options from #1139 to the PUT large_image/folder/{id}/tiles endpoint, and allows the createJobs filter to accept three states. The first flag allows cancelling unfinished large image jobs related to items in the folder, so the large image can then be removed and a new one created. The second gives the option to remove and redo existing large images in the folder. The three states createJobs now accepts can either never use a job, use one only if needed, or force one for every large image.

Add options to cancel jobs, redo existing large images, and not force jobs

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/models/annotationelement.py
large_image/tilesource/utilities.py

When ingesting annotation elements, we use insert_many in batches split across a thread pool.  There is some work (such as computing bounding boxes) that parallelizes decently.  The actual mongo insert_many call _does_ parallelize, but is slower than using a lock to prevent concurrency.
The specific problem is that mongo assigns new ids to the new element documents using the bson package's ObjectID class.  This class generates a new random number as part of the id whenever it is called from a different thread pid.  The bulk of the insert time ends up being generating random numbers rather than anything else.  By having a lock, this will only trigger the pid-change code once per batch.
One test showed a large annotation insert time dropping from 395 seconds to 140 seconds, and the cpu …

Add a lock to avoid mongo excessively computing random numbers

---

girder_annotation/test_annotation/web_client_specs/annotationListSpec.js

It is no longer compatible with the phantomjs test runner.  We can reenable this test once girder upgrades to a modern test harness.

Disable client tests with openseadragon.

---

CHANGELOG.md
sources/tifffile/large_image_source_tifffile/__init__.py
sources/zarr/large_image_source_zarr/__init__.py

Fixes #1606.
On some systems, numpy defaults to 32 bit integers.  When np.prod produces should produce a value greater than `2^31 - 1`, it overflows and produces a value that isn't accurate.  Since `math.prod` was added in Python 3.8, we can just switch to `math.prod` and let python take care of arbitrary sized integers regardless of its environment.

Use math.prod in preference to np.prod

---

.pre-commit-config.yaml
test/test_notebooks.py

@annehaley This makes sure that the zarr notebook parses but doesn't execute it.
I'm not sure why it kills the kernel.  In trying to run it on Circle, I managed to make it not use much memory, but the jupyter kernel still died.  There didn't appear to be undue load, either.  For now, let's just disable running the notebook during CI.
I also set the pre-commit hook to not use codespell on notebooks because it fails on the base64-encoded output blocks.

Don't execute the zarr notebook

---

.pre-commit-config.yaml
tox.ini

Pin maison so yamlfix will still work.  See
https://github.com/lyz-code/yamlfix/issues/286 for details.  The pinned packages should be unpinned when that issues is addressed.

Yamlfix doesn't work with a recent package

---

README.rst

Because we use the README as part of the built docs, we added references into it.  These won't deploy, as the description uploaded to pypi.org can't use them directly.

Fix the README.rst so we can deploy.

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/utils/__init__.py

This also does correspondence between bounding boxes and annotation elements.
It is slower than desired for reading data via pandas and doing that correspondence.

Improve scanning data file for plottable data

---

CHANGELOG.md
large_image/config.py

When a workflow opens a lot of tile sources and uses each one once, caching is often wasteful.  This adds a utility function `large_image.config.minimizeCaching()` for these cases.

Add a utility function to minimize caching

---

CHANGELOG.md
utilities/converter/large_image_converter/__init__.py

Slightly shift how concurrency is divided between sources and tiles.

Improve logging during pooled concurrency in the image converter

---

CHANGELOG.md
large_image/tilesource/base.py
sources/bioformats/large_image_source_bioformats/__init__.py
sources/gdal/large_image_source_gdal/__init__.py
sources/mapnik/large_image_source_mapnik/__init__.py
sources/nd2/large_image_source_nd2/__init__.py
sources/openjpeg/large_image_source_openjpeg/__init__.py
sources/pil/large_image_source_pil/__init__.py
sources/rasterio/large_image_source_rasterio/__init__.py
sources/tiff/large_image_source_tiff/tiff_reader.py
sources/tifffile/large_image_source_tifffile/__init__.py
sources/vips/large_image_source_vips/__init__.py
test/lisource_compare.py

This was tested by running lisource_compare.py on most of the GDAL repository's autotest files.  If a source threw a traceback rather than returning that it could not read a source, it was modified to handle the condition better.
Specifically, command like `find ../gdal/autotest/{gcore,gdrivers} -type f -not -name '*.py' -not -name '*.txt' -exec python test/lisource_compare.py --all --projection= --projection=EPSG:3857 {} \+` was run, though some test files were excluded.
There are some interesting test cases that are just astonishingly slow.  For instance, some test files are conceptually single layers that are 2e9 pixels across; we currently synthesize lower levels when getting things like thumbnails in some sources (such as tiff).  We could be smarter there -- if the synthesized layer …

Harden some of the sources when trying to read bad files

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/rest/annotation.py
girder_annotation/girder_large_image_annotation/utils/__init__.py
girder_annotation/setup.py
girder_annotation/test_annotation/test_annotations.py
girder_annotation/test_annotation/test_annotations_rest.py
requirements-dev.txt
sources/multi/large_image_source_multi/__init__.py
test/test_source_multi.py

We need a bigger border or some areas are zero.  Also, fix corner computation.

Fix scaling small images in the multi source with bicubic smoothing

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/utils/__init__.py

This applied to plottable data.  When bounding boxes correlate annotation elements with data files or folder or item lists, adjacent items could miss this correlation.

Fix correlating annotation bounding boxes on adjacent items

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/utils/__init__.py

This ensures that if the bounding box is correlated from data files, folders, or item metadata, the annotation id and name is also correlated with the augmented data for the annotation element.

Extend correlating annotation element bounding boxes

---

tox.ini

Expose an option to make it easier to rerun tests without rebuilding girder

Add more options for how tox runs tests

---

sources/multi/large_image_source_multi/__init__.py
test/test_source_multi.py

Resolves #1638 
This feels hacky overriding the paths but it seems to work

Support dict with MultiFileTileSource

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/utils/__init__.py
girder_annotation/setup.py

Use a simple quad-set lookup to avoid walking all rows.
Use calamine rather than openpyxl for reading xlsx files.
Don't read needless data files.
Don't read headless columns from data files.
Change column sort order to show multi-value columns sooner.

Speed up correlating data files with annotations.

---

.gitignore
docs/conf.py
docs/format_examples_datastore.py
docs/formats.rst
docs/generate_format_table.py
docs/make_docs.sh
tox.ini

Generate a docs table for file format examples

---

CHANGELOG.md
large_image/tilesource/base.py
large_image/tilesource/tileiterator.py
sources/bioformats/large_image_source_bioformats/__init__.py
sources/openjpeg/large_image_source_openjpeg/__init__.py
sources/openslide/large_image_source_openslide/__init__.py
sources/tiff/large_image_source_tiff/__init__.py
sources/tifffile/large_image_source_tifffile/__init__.py
sources/zarr/large_image_source_zarr/__init__.py
test/test_source_base.py

When an image is missing multiple layers, if enough are missing, we don't need to always read the whole image.  Also, if the image is not uint8, we can more efficiently composite the lower resolution tiles.

Better handle images without enough tile layers

---

CHANGELOG.md
large_image/tilesource/base.py
sources/tiff/large_image_source_tiff/__init__.py

Before, when an empty level existed and we wanted a styled tile, we generated styled subtiles and composited them.  This had some quirks between what the tiff reader did and all other readers.  It has now been harmonized.

Fix styling images with empty tile layers

---

CHANGELOG.md
girder/girder_large_image/web_client/templates/itemList.pug
girder/girder_large_image/web_client/views/configView.js
girder/girder_large_image/web_client/views/itemList.js

With the addition of #1649, we always use the large_image itemList rather than modifying the base girder item list.  We no longer need the code that did that modification.
Don't display column titles on an empty list.
Make check boxes easier to click.
Allow long strings to break more efficiently.

Remove no longer used code; adjust item list slightly.

---

CHANGELOG.md
girder/girder_large_image/web_client/views/itemList.js

When loading long pages with sorts, sometimes the initial page number shown in the bottom pagination bar was wrong.  This fixes that issue.

Reduce updates when showing item lists; add a waiting spinner

---

docs/format_examples_datastore.py

Some source links for the format example files have been moved or broken. I have uploaded those files to DKC and this PR replaces the download links for those files.

Update download links for format examples

---

CHANGELOG.md
girder/girder_large_image/web_client/views/itemList.js

With the item list table, this is expected.
This is being done in the HistomicsUI, plugin, but really needs to be here since we now default to the table item lists.

Use paginated item lists.

---

CHANGELOG.md
docs/conf.py
docs/girder_config_options.rst
girder/girder_large_image/rest/__init__.py
girder/girder_large_image/web_client/templates/itemList.pug
girder/girder_large_image/web_client/views/itemList.js

This can also add counts based on grouping.

Add options to group within item lists

---

CHANGELOG.md
docs/girder_config_options.rst
girder/girder_large_image/web_client/templates/itemList.pug
girder/girder_large_image/web_client/views/itemList.js

This adds grouping, navigation changes, and the ability to route to named item lists.  Folder lists can be hidden when recursion is applied.  Grouping can add counts.

Add additional item list options

---

CHANGELOG.md
large_image/tilesource/base.py
sources/pil/large_image_source_pil/__init__.py

These issues were not caught in testing because some of our dependencies force numpy < 2.

Fix some issues with possible numpy 2.x overflows

---

sources/dicom/setup.py

The latest version supports pydicom >= 3, but only on python 3.10+.

Relax pinning for wsidicom

---

.circleci/config.yml
CHANGELOG.md
girder/setup.py
girder_annotation/setup.py
setup.py
slim.Dockerfile
sources/bioformats/setup.py
sources/deepzoom/setup.py
sources/dicom/setup.py
sources/dummy/setup.py
sources/gdal/setup.py
sources/mapnik/setup.py
sources/multi/setup.py
sources/nd2/setup.py
sources/ometiff/setup.py
sources/openjpeg/setup.py
sources/openslide/setup.py
sources/pil/setup.py
sources/rasterio/setup.py
sources/test/setup.py
sources/tiff/setup.py
sources/tifffile/setup.py
sources/vips/setup.py
sources/zarr/setup.py
test.Dockerfile
tox.ini
utilities/converter/setup.py
utilities/tasks/setup.py

Currently this is very slow because some binary wheels are missing for 3.13 (numcodecs being notable) and they need to be compiled before testing begins.  Additionally, currently wsidicom requires numpy<2, partly because dicomweb-client isn't numpy 2.x compatible (yet).  Since numpy < 2 doesn't have wheels for 3.13, this is part of the slowness. To avoid having CI timeout, this increases tox verbosity.
A few optional packages don't have 3.13 support (scikit-learn, pillow-jxl-plugin, rawpy), so those are not included in install_requires options.

Test on Python 3.13

---

CHANGELOG.md
girder/girder_large_image/web_client/views/itemList.js

`self` was used rather than `this` in some javascript code.

Some checks for repeated values in the item lists were wrong

---

sources/zarr/large_image_source_zarr/__init__.py
test/test_sink.py

Resolves #1678. This PR adds a new pytest (using a function similar to what is provided on the issue) and fixes the resize behavior in `addTile` to prohibit shrinking.

Zarr Sink Subprocess

---

CHANGELOG.md
girder/girder_large_image/rest/__init__.py
girder/girder_large_image/web_client/templates/itemList.pug
girder/girder_large_image/web_client/views/itemList.js

This doesn't yet support custom icons or folder level buttons.

Add and support app buttons

---

CHANGELOG.md
girder/girder_large_image/rest/__init__.py

Compute permissions sooner.  Ensure sort order of results.

Speed up recursive item lists

---

docs/getting_started.rst
docs/notebooks/zarr_sink_example.ipynb
examples/algorithm_progression.py
girder/girder_large_image/web_client/vue/components/FrameSelector.vue
large_image/tilesource/base.py
sources/zarr/large_image_source_zarr/__init__.py
test/test_sink.py

Resolves #1325. This PR adds frame values to the Zarr sink, which allows a user to specify true values for each index of a frame axis. This can be done with `addTile` or by setting `frameValues` directly. Additionally, the user may set a dictionary of `frameUnits` to describe the units used by each frame axis and/or a list of `frameAxes` to assert an ordering to the frame axes. 
For example:
```
import large_image_source_zarr
import numpy as np
sink = large_image_source_zarr.new()
sink.frameAxes = ['z', 't', 'm']
sink.frameUnits = dict(z='cm', t='ms', m='mm')
for z, z_value in enumerate([2, 4, 6, 8]):
for t, t_value in enumerate([10.0, 20.0, 30.0]):
t_value += 0.01 * z
for m, m_value in enumerate(['r', 'g', 'b']):
random_tile = np.random.random((300, 400, 3))
sink.addTile(
random_tile,
0, …
```

Zarr Sink Frame Values

---

CHANGELOG.md
girder/girder_large_image/web_client/views/imageViewerWidget/geojs.js
girder/test_girder/web_client_specs/imageViewerSpec.js
girder_annotation/test_annotation/web_client_specs/annotationListSpec.js
girder_annotation/test_annotation/web_client_specs/geojsSpec.js

This checks if geojs is already in memory and doesn't replace it with itself

Reduce loading geojs when switching views in Girder

---

test/test_sink.py

CI sometimes fails on this test.

Mark a subprocess test as singular

---

CHANGELOG.md
sources/zarr/large_image_source_zarr/__init__.py
test/test_sink.py

It can use arbitrarily large amounts of memory.  If we want to populate these values, we need to collect the data as we call addTile or use the tile iterator to collect it.

Don't compute channel window in zarr sinks

---

CHANGELOG.md
setup.py
sources/openslide/setup.py

Openslide is now publishing binary wheels, but as a package called openslide-bin.  Require these for appropriate platform machine/system combinations.  This allows openslide to be added to the list of commonly supported sources.

Use openslide published binaries

---

large_image/config.py

psutil can return none for the number of logical cpus

Modify a function to keep the type checker happy

---

CHANGELOG.md
large_image/exceptions.py
large_image/tilesource/utilities.py
sources/tiff/large_image_source_tiff/__init__.py
sources/tifffile/large_image_source_tifffile/__init__.py
test/datastore.py
test/test_source_base.py
tox.ini

The tiff files have some subifds without any strips or tiles and erroneously do not declare that they have float pixel data.

Handle indica labs variant tiff.

---

CHANGELOG.md
sources/gdal/large_image_source_gdal/__init__.py

gdalwarp and gdal_translate can be used to transform images in pixel space.  If such an image has no projection specified and cannot be interpreted as latitude and longitude, assume it is not geospatial.

Better detect files with geotransform data that aren't geospatial

---

CHANGELOG.md
girder/girder_large_image/__init__.py

If a user has permission to view an annotation but not the item, a 403 was percolated to the UI

Fix an issue searching for annotation metadata

---

CHANGELOG.md
large_image/tilesource/base.py
large_image/tilesource/geo.py
large_image/tilesource/tiledict.py
test/lisource_compare.py

If scaling non uint8 tiles in numpy format, possibly use scikit-image rather than converting to an 8-bit pil image for the process.
Add some missing type hints.

Better scale float-valued tiles

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/rest/annotation.py
girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js

If an overlay annotation was requested and then dismissed before obtaining data about it, a javascript error would be raised.  This didn't cause an issue, but should be cleaned up properly.

Guard against switching on and off overlay layers quickly

---

CHANGELOG.md
large_image/tilesource/utilities.py
sources/multi/large_image_source_multi/__init__.py

This adjust how compositing is done on styled images.
Also, improve documentation of multi-source schema

Adjusting the expected full alpha value on some float tiles

---

CHANGELOG.md
sources/multi/large_image_source_multi/__init__.py

When using the multisource to composite multiple images with alpha channels, use nearest neighbor for upper tiles.  This avoids edge effects from bicubic interpolation

Adjust multisource multi layer compositing.

---

sources/multi/setup.py
sources/pil/setup.py

scikit-image has been released for Python 3.13, so all packages we have even as optional dependencies are available.

Unpin a package

---

CHANGELOG.md
sources/nd2/large_image_source_nd2/__init__.py

Specifically, the dask module probably duplicates the ND2File object and the deletes the object without explicitly closing it.

Suppress a warning about nd2 files that we can't do anything about

---

CHANGELOG.md
large_image/cache_util/cache.py

If a python version with numpy >= 2.x wrote a tile to the cache, and then a python version with numpy < 2.x tried to read the tile from the cache, the failure was a ModuleNotFoundError rather than the errors we were checking for.  This now counts as a cache miss rather than a failure.

Harden the tile cache between python versions and numpy versions

---

sources/zarr/large_image_source_zarr/__init__.py

Also, write the metadata after fundamental changes so that anything that reopens the file after that point will see those changes.

When reopening a zarr sink, validate it

---

CHANGELOG.md
setup.py

They may require other libraries that aren't present.

Don't include cache libraries in [common]

---

CHANGELOG.md
large_image/tilesource/geo.py

When automatically constructing a vsicurl url to allow gdal to read from https or s3 sources, set empty_dir=yes to avoid probing for sidecar files.  Prior to GDAL PR 11469, this seem to be the case with just list_dir=no, but it isn't clear from the GDAL documentation why that works.  Be explicit (open a viscurl path directly to change the behavior).

Specify empty_dir=yes when constructing vsicurl parameters

---

CHANGELOG.md
large_image/tilesource/base.py

There was a case where a tile with >u2 data and int histogram ranges caused numpy 2.x to segfault.  Using float histogram ranges avoids this

Cast histogram ranges to floats

---

CHANGELOG.md
sources/tiff/large_image_source_tiff/tiff_reader.py

Use the libtiff code path for jpeg, not the jp2k fall-back code path

Update how some associated images are read in tiff files

---

CHANGELOG.md
sources/gdal/large_image_source_gdal/__init__.py
sources/vips/large_image_source_vips/__init__.py

We weren't clearing the gdal block cache, and weren't clearing the vips cache completely.  Further, the vips operation cache can't be set to zero or it has the potential to cause a future memory error.
GDAL also has a dataset pool (also a proxy pool), which I don't think this clears.

When clearing all caches, better clear vips and gdal caches

---

CHANGELOG.md
sources/zarr/setup.py

We expect to be able to read zarr stored in the SQLiteStore format, and zarr hasn't released a zarr-3 compatible package for this yet.

Pin zarr < 3

---

CHANGELOG.md
large_image/tilesource/geo.py
sources/bioformats/large_image_source_bioformats/__init__.py
sources/gdal/large_image_source_gdal/__init__.py
sources/mapnik/large_image_source_mapnik/__init__.py
sources/pil/large_image_source_pil/__init__.py
sources/rasterio/large_image_source_rasterio/__init__.py
test/lisource_compare.py

The goal is that no source will crash on any of GDAL's test data set, no matter how ill-formed

Harden reading a variety of test files

---

CHANGELOG.md
sources/openslide/large_image_source_openslide/__init__.py
sources/tifffile/large_image_source_tifffile/__init__.py
test/datastore.py
test/test_source_base.py

It explicitly only reads the focal plane at 0 and skips the others silently.
Improve the tifffile source reporting of ndpi internal metadata.

Don't read multiplane ndpi files with openslide

---

CHANGELOG.md
large_image/tilesource/jupyter.py

This fixes the issue on map coordinates.  Layers appear to still be inverted.  Note that this will break map bounds in ipyleaflet < 0.19.

ipyleaflet 0.19 fixes an issue with inverting bounds coordinates

---

CHANGELOG.md
large_image/config.py

@annehaley This should remove the need to add `nocache=True` to let the frame selector work in notebooks.
@banesullivan This should make your work easier, too.

Default to not caching sources in notebooks

---

CHANGELOG.md
girder_annotation/setup.py
large_image/tilesource/base.py
large_image/tilesource/stylefuncs.py
large_image/tilesource/tiledict.py
large_image/tilesource/utilities.py

numba now supports python 3.13, which means all optional dependencies can now be installed for Python 3.13.
With this change, CI is running with numpy 2.1.x rather than numpy 2.0.x, which changes what mypy detects as type issues.  Some types are more properly detected, while others are missed, so there are a variety of changes to make mypy happy.

Allow umap-learn for graphing in girder annotations in python 3.13

---

CHANGELOG.md
girder_annotation/setup.py
large_image/tilesource/base.py
large_image/tilesource/stylefuncs.py
large_image/tilesource/tiledict.py
large_image/tilesource/utilities.py
setup.py

Brings in changes from #1780 to fix the type checking problems and removes the numpy pin.

Unpin numpy in girder 5

---

CHANGELOG.md
docs/tilesource_options.rst
large_image/tilesource/base.py
test/lisource_compare.py

The speed up is achieved by have a special case for palettes that have two entries with the first entry 0 and for conditions where no mask is required.
Slightly speed up source comparison

Speed up style composition.

---

.circleci/config.yml
.circleci/release_pypi.sh
girder/MANIFEST.in
girder_annotation/MANIFEST.in

Ship Girder plugin packages with built client packages.
This makes it easier for dependent plugins to use `large_image` Girder plugins.

Build plugin client code on release

---

large_image/constants.py
sources/bioformats/large_image_source_bioformats/__init__.py
sources/gdal/large_image_source_gdal/__init__.py
sources/pil/large_image_source_pil/__init__.py
sources/rasterio/large_image_source_rasterio/__init__.py

Based on reading the gdal and omero test data sets, list extensions for a few sources that were not listed by the originating libraries.

List a few more known extensions for different sources

---

CHANGELOG.md
girder/girder_large_image/web_client/views/imageViewerSelectWidget.js
large_image/widgets/CompositeLayers.vue
large_image/widgets/HistogramEditor.vue

Tweak a few css values to make it easier to integrate in other libraries

Fix multiple histogram queries in Girder frame selector

---

CHANGELOG.md
large_image/tilesource/utilities.py
test/datastore.py
tox.ini
utilities/converter/large_image_converter/__init__.py

If a source image was not uint8 or uint16 we used the full range of the datatype for some of the conversion, but, to maximize compatibility, we always output either uint8 or uint16 pixels.  In a sample image that was stored in int32 but only had pixels with values 0, 1, 2, this resulted it scaling the output by (val * 2 ** -16) + 2 ** 15, but in that resulted in all output pixels having the value of 32768.
Now, we check the range of all frames of an image first, and try to intelligently pick a datatype and scaling based on the actual range of the data.  This will still be wrong in some instances, but should at least result in visible images.

Be more specific in casting when converting images via vips

---

CHANGELOG.md
large_image/tilesource/tiledict.py
test/test_source_base.py

Specifically, the height reported for a unloaded tile that had been scaled was reporting the width instead.

Fix an issue with lazy tiles that have non power of two scaling

---

CHANGELOG.md
sources/zarr/large_image_source_zarr/__init__.py

np.empty actually allocates memory, zarr.empty does not.

Use zarr.empty not np.empty when creating large zarr sinks

---

CHANGELOG.md
sources/zarr/large_image_source_zarr/__init__.py
test/test_sink.py

In a check if we were handling the x, y, or s axes, we did the comparison `if axis in 'xys'`, but this succeeds for `xy` (and would have also succeeded for ys and xys).  Use a proper set comparison rather than an implicit set comparison.

Fix zarr sink adding an xy axis

---

large_image/widgets/HistogramEditor.vue

When using the Histogram Editor within the Frame Selector component, this PR keeps the min and max input boxes visible even when autoRange is enabled (though they are disabled in that case). The min and max inputs show the real values when specifying range with a distribution percentage.
Resolves #1030.

Histogram AutoRange True Values

---

sources/zarr/large_image_source_zarr/__init__.py
test/test_sink.py

This PR fixes the following reported behavior of the Zarr Sink:
```
>>> import large_image, numpy as np
>>> sink = large_image.new()
>>> sink.addTile(np.random.random((256, 256)), 0, 0, q=1)
>>> sink.metadata['IndexRange']
{'IndexQ': 2}
>>> sink.addTile(np.random.random((256, 256)), 0, 0, r=1)
>>> sink.metadata['IndexRange']
{'IndexR': 2}
>>> # What happened to Q?
```

Fix Zarr Sink adding multiple frame axes

---

CHANGELOG.md
sources/bioformats/large_image_source_bioformats/__init__.py

One of our test files fails when reading it with bioformats at the low tile levels but succeeds at the higher resolutions.  Do a test while opening such files so that they are read more consistently.

Test reading from lower tile levels in bioformats

---

CHANGELOG.md
sources/openslide/large_image_source_openslide/__init__.py

openslide can return RGBA tiles with transparent areas and report a background color.  Apply the background color without changing transparency.
Resolves #1814 .

Apply background color information from openslide sources

---

CHANGELOG.md
setup.py

Require a minimum version of Pillow to avoid a CVE

---

CHANGELOG.md
sources/dicom/large_image_source_dicom/girder_source.py

Use a mongo aggregation to reduce database requests.

Speed up finding adjacent DICOM files in girder

---

large_image/tilesource/jupyter.py
test/test_jupyter.py

This PR adds widgets to the `ipyleaflet` image viewer in Jupyter notebooks. The user may draw (and remove) rectangles on the image. Clicking on the rectangle shows a popup with information about the selected region. This PR also adds a fullscreen view button to the options along the side of the viewer. The following screenshots are captured in fullscreen mode.
Geospatial example:
Non-geospatial example:

Ipyleaflet Region Indicator

---

docs/generate_format_table.py

This PR adds a table to the "Image Formats" page of the documentation. This table shows extensions and mimetypes for each tilesource. The resulting documentation page can be viewed here: https://output.circle-artifacts.com/output/job/a09981e2-a5f6-4872-865b-e447681b9331/artifacts/0/build/docs/formats.html

Reformat docs extensions list as a table

---

test.Dockerfile

This cleans up some unused files and skips installing an unneeded extra copy of python.

Make the test docker slightly smaller

---

sources/dicom/large_image_source_dicom/web_client/views/DICOMwebImportView.js

We can only set the assetstoreImportViewMap if the main Girder application exists.

Guard the assetstoreImportViewMap update

---

girder/girder_large_image/rest/__init__.py
girder/girder_large_image/rest/tiles.py
girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/girder_large_image_annotation/rest/annotation.py

For those that shouldn't be running as a local job, ensure that they emit data in a timely fashion.

Better handle long rest requests in Girder 5

---

CHANGELOG.md
sources/bioformats/large_image_source_bioformats/__init__.py
sources/pil/large_image_source_pil/__init__.py
sources/vips/large_image_source_vips/__init__.py

If you called setConfig before loading sources, the sources' additional config values (such as ignored names) could overwrite the explicit settings.  This could happen in the girder context when getting config values from a girder config file.

Fix an order of operations issue with config values

---

large_image/tilesource/base.py
sources/gdal/large_image_source_gdal/__init__.py
sources/rasterio/large_image_source_rasterio/__init__.py
test/source_geo_base.py
test/test_source_gdal.py
test/test_source_tiff.py

When calling `getRegion`, if encoding is "TILED", then the user may also specify an output path for the tiled image. Example:
```
region, _ = ts.getRegion(
output=dict(maxWidth=1024, maxHeight=1024, path='./path/to/region.tif'),
encoding='TILED'
)
```
Resolves #682

Allow specifying output path for `getRegion`

---

docs/notebooks/frame_viewer_example.ipynb
large_image/config.py
large_image/tilesource/jupyter.py
large_image/widgets/CompositeLayers.vue
large_image/widgets/components.py
test/test_jupyter.py

Resolves #1883 
- 500 errors from the tile server were raised due to `'Cannot set the style of a cached source'`
- Updated `_in_notebook` to expect Colab's shell name
- Added an exception to warn the user that caching is enabled prior to displaying the interactive viewer
- Child components of Frame Selector did not render because ipyvue's `register_component_from_file` doesn't work in Colab context
- Refactored to register child components from strings read from files
- Use `tiff` source instead of `tifffile` source
- Add `ipyvue` installation

Fix Frame Selector component in Colab Notebooks

---

CHANGELOG.md
girder/girder_large_image/models/image_item.py
girder/girder_large_image/rest/large_image_resource.py
girder/test_girder/test_large_image.py
girder/test_girder/test_tiles_rest.py

This allows file writes to happen in the background, return the results more quickly.

Upload cached thumbnails and images in threads to parallelize

---

sources/zarr/large_image_source_zarr/__init__.py
test/test_sink.py

This PR allows users to set projection and GCPs on an image written with the zarr sink. Example below. This PR will complete the last remaining item in #1002.
```
sink = large_image_source_zarr.new()
sink.addTile(np.random.random((256, 256, 3)) * 10, x=0, y=0)
sink.projection = 'epsg:4326'
sink.gcps = [(-77.050, 38.888, 0, 0), (-77.049, 38.889, 256, 256)]
sink.write('example.tiff')
```

Zarr sink: Set projection and GCPs

---

CHANGELOG.md
sources/bioformats/large_image_source_bioformats/__init__.py

Attaching and detaching from the jvm needs to be locked, but not the actual tile reads

Change where locking occurs with bioformats

---

CHANGELOG.md
sources/bioformats/large_image_source_bioformats/__init__.py

Bioformats is less thread safe than desired.  Put back some of the locking.  This is still marginally faster that before the locking changes, but doesn't benefit from multiprocessing.

Put back some of the locking in bioformats

---

tox.ini

Updates flake8 to exclude commonly used virtual environments

Exclude commonly used virtual envs

---

CHANGELOG.md
utilities/converter/large_image_converter/__init__.py

When we convert an image via vips, we collect tiled regions into strips and then strips into a file image.  This is done because vips won't handle more than some number of actions in its action list, but can handle a tree of actions (each tile add being an action).  However, vips appears to read most of the strips into memory as it goes in this memory model.  If we save each strip as a vips temp file, we have more disk access, but avoid the memory spike.

vips could use too much memory during image conversion

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/girder_large_image_annotation/rest/annotation.py
girder_annotation/test_annotation/test_annotations.py
girder_annotation/test_annotation/test_annotations_rest.py

This modifies an existing annotation via a list of patch instructions.  Each entry is an operation that contains "op", "path", and possibly "value".  "op" can be any of "replace", "add", or "remove".  "path" is either a root property (e.g., "name"), or "elements/id:{element id}".  Any path to a dictionary or list can be extended via .../(key or index) components.

PATCH annotation/{id} endpoint

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/models/annotationelement.py

We were only checking the first "few" elements to see if they were large enough that we had to store them as files rather than in the database, and we were not checking the size of holes in polygons.  As such, an annotation element with a huge number of holes, or one with many small polygons followed by a huge polygon could fail to be placed in the database.  Further, insert errors of this sort were not being percolated up to the logs, making debug difficult.

Improve handling of large annotation elements

---

CHANGELOG.md
sources/openslide/large_image_source_openslide/__init__.py
sources/tiff/large_image_source_tiff/__init__.py

The tiff source should always be preferred for a file with a tiff extension

Change some source priorities for tiff

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/web_client/collections/ElementCollection.js
girder_annotation/girder_large_image_annotation/web_client/models/AnnotationModel.js

This greatly reduces serialization time and web traffic.

In many instances, save annotation element via a PATCH call

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/web_client/models/AnnotationModel.js

When zoomed in with a power of two of the max zoom and showing annotations, make sure all of the annotation in view are fully loaded. Before, this was still subject to detail limits, which meant that it was possible to fail to resolve some annotations regardless of zoom level.

Show all annotations when zoomed in

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/web_client/models/AnnotationModel.js
girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js

This
- tracks updating centroids when elements change if appropriate
- will not page new elements if it is currently saving elements
- removes the highlight size limit
- fixes a potential issue with showing both a centroid and an element

Handle editing paged annotations.

---

docs/getting_started.rst
large_image/tilesource/base.py
test/test_source_base.py

This PR adds `getGeospatialRegion` as a function on the `TileSource` base class and adds an example to the documentation.
Example usage:
```
import large_image
source = large_image.open('sample.tiff')
source.getGeospatialRegion(
'epsg:3857', 
[
(-8578909.8696,4704125.8132, 0, 0),
(-8571075.0742,4710164.3385, source.sizeX, source.sizeY),
],
'epsg:4326', 
{
'left': -77.015104,
'top': 38.887642,
'right': -77.005877,
'bottom': 38.892235,
},
frame=0,
format='numpy',
)
```

`getGeospatialRegion` Function

---

CHANGELOG.md
setup.py
sources/pil/setup.py

It doesn't have binary wheels for some platforms and python versions

Move the pillow-jpls module out of common install extras.

---

.pre-commit-config.yaml
CHANGELOG.md
girder/girder_large_image/girder_tilesource.py
girder/girder_large_image/models/image_item.py
pyproject.toml
sources/openslide/large_image_source_openslide/girder_source.py
utilities/tasks/large_image_tasks/tasks.py

When opening images that are uploaded or otherwise not imported from a filesystem assetstore, we use the fuse mount to read the images.  If we think the image is composed of adjacent files, we were using the flat mount point, where individual items in girder each appear as single files.  But, when the image item has multiple files that are part of the image, this does not work.  The detection is that if the format might have adjacent files and we are reading an unconverted file, and the item has multiple files with the same mimetype as the main file, then we prefer the non-flat mount.
This has the potential to fail; someone could upload multiple files and have the same mimetype even though the image is spread across multiple items.  But, without it, merged dicoms, for instance, may not …

Better handle images with adjacent files in the same girder item

---

CHANGELOG.md
sources/openslide/large_image_source_openslide/__init__.py
test/test_source_openslide.py

Peculiarly, openslide has a "downsample" factor which isn't the power of 2 one would expect.  This is computed based on the actual dimensions of levels, but since higher-resolution levels are not fully populated at the right and bottom, this ends up with not the actual downsampling, but some slightly higher number (e.g., 16.0018 rather than 16).  Internally, when asking for a region for anything other than the maximum resolution lever, the openslide library is passed coordinates in what _seems_ to be base image coordinates, but is actually inflated by the ratio of their downsample value and the actual downsample value (e.g., 16.0018 / 16). We multiple our values by this ratio so when openslide misapplies its downsampling we get the region we actually want.
Prior to this commit, we were …

Fix openslide reads at lower levels

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/rest/annotation.py

We query via element.girderId, but DocumentDB 5.0 doesn't support multi-key indices, so this is glacially slow.  Just skip this query and accept reduced functionality.
Resolves #1948.

Do not check if items are used as annotation elements in DocumentDB

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/rest/annotation.py

This was caused by comparing a string to an ObjectId

Sometimes the annotation PATCH endpoint would report a duplicate ID

---

sources/zarr/large_image_source_zarr/__init__.py

This PR fixes the following bug I encountered:
```
File "large_image/sources/zarr/large_image_source_zarr/__init__.py", line 1448, in write
convert(str(attrs_path), path, overwrite=overwriteAllowed, **params)
TypeError: large_image_converter.convert() got multiple values for keyword argument 'overwrite'
```
To reproduce:
```
import large_image_source_zarr
import numpy as np
sink = large_image_source_zarr.new()
sink.addTile(
np.random.randint(0, 255, size=(255, 255, 1)), x=0, y=0
)
sink.write('test.tif', overwrite=True)
```

Zarr Write: Prevent multiple values for the `overwrite` kwarg

---

CHANGELOG.md
large_image/widgets/HistogramEditor.vue

We could try to get the range values before they had been created

Eliminate a javascript exception in the histogram viewer

---

test/lisource_compare.py

When running with different styles or projections, a properties dictionary was not being properly reset

If you ran the source compare test tool, test order could matter

---

CHANGELOG.md
sources/gdal/large_image_source_gdal/girder_source.py
sources/rasterio/large_image_source_rasterio/girder_source.py

In Girder, this allows path-relative adjacent files (such as from vrt files) to be found properly

Specify that gdal and rasterio sources could be multifile

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/girder_large_image_annotation/models/annotationelement.py
girder_annotation/girder_large_image_annotation/web_client/models/AnnotationModel.js

Much of the time is just getting data back from mongo.  On a ~1/3 million annotation test, before these changes it took ~4.19s to ~3.69s (12% improvement).  If we stop sorting the results, this improves further to ~3.50s (total 16% improvement).  Here, we've stopped sorting unless it could matter.
As a further (future) improvement, we could precompute or cache the response so the response would effectively be serving a static file.
Some experiments which were not effective:
- Switching to precomputing the data in a mongo aggregation to avoid some work in python.  This was slower no matter what I tried.
- Using a covering index where all values used were in the index (huge and not helpful)
- Changing the struct.pack in the rest response to try to use tobytes or numpy serialization.  This …

Speed up annotation centroid queries

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/models/annotation.py
girder_annotation/girder_large_image_annotation/models/annotationelement.py
girder_annotation/girder_large_image_annotation/rest/annotation.py
girder_annotation/girder_large_image_annotation/web_client/models/AnnotationModel.js

This makes a number of improvements to loading large annotations.  This has been tested with a set that is around 1/3 million polygons.
- When saving annotations, we now store the number of elements and "details" count on the annotation document and percolate this through so that a client gets this information (if available) with the base annotation (without its elements).  This allows a client to know a priori whether it will need to page elements and fetch centroids.
- When loading an annotation with element and details count, if we know the element will need to be paged, we skip the first partial load and go straight to loading the centroids.  Once the centroids are loaded we load the view-specific elements as usual.
- When panning (or loading in general), we were fetching the …

Improve large annotation load and display speed

---

CHANGELOG.md
girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js
large_image/tilesource/base.py

Add a guard to avoid a javascript except if annotations are not loaded enough

Don't try to change annotation visibility if it isn't loaded
