- .travis.yml
- plugin.cmake
- plugin_tests/exampleSpec.js
- plugin_tests/example_test.py
@brianhelba Here is the boilerplate testing setup you asked for.  A few notes:
* The travis config might not work.  I can't test it until travis integration is turned on.
* All but one of the style tests currently fail.  You may want to adjust the style configs (to for example, add global variables), but I wanted to wait on the ESLint PR before worrying about it.
* The client test doesn't work because the plugin source files aren't loaded into the test html.  I haven't dealt with client side plugin tests, so I'm not sure what is wrong with it.
> Setup testing infrastructure

- plugin_tests/tiles_test.py
- server/models/__init__.py
- server/models/base.py
- server/models/image_item.py
- server/rest.py
- server/tilesource/base.py
- web_client/js/imageViewerWidget/openlayers.js
This should allow all important operations to be called internally from Python, as well as via the HTTP API.
> Abstract complex logic into a new Model

- .travis.yml
- plugin_tests/tiles_test.py
- server/models/image_item.py
- server/rest.py
- server/tilesource/base.py
@brianhelba This is done except for tests.  I've pushed it now in case you need it right away.  I will have tests soon.
> Add GET image/{id}/tiles/thumbnail endpoint.

- server/models/annotation.py
- server/rest/annotation.py
Make sure the creatorId is indexed.
> Allow find annotation filtered by user id

- docs/annotations.md
- server/models/annotationelement.py
- server/rest/annotation.py
Added an endpoint to return the official schema.
> Add some documentation about annotations.

- plugin.cmake
- scripts/tile_benchmark/benchmark.py
- scripts/tile_benchmark/plot_time.py
- scripts/tile_benchmark/requirements.txt
- scripts/tile_benchmark/source.txt
Generates basic histogram and box and whiskers plot indicating time to get tiles from girder tile server
> Benchmarking

- server/base.py
data.process events are async, so adjust how they are handled, as they may occur after the job finishes.
> data.process events are async, so adjust how they are handled

- plugin_tests/sources_test.py
- server/tilesource/base.py
> Allow getRegion to return different formats.

- server/rest/large_image.py
- server/tilesource/base.py
- server/tilesource/svs.py
> If the thumbnail job fails to create a thumbnail, indicate it in the logs and keep going.

- server/tilesource/base.py
When a tile is returned by the tile iterator, don't load the actual image until it is needed.
> Lazily load images from the tile iterator.

- plugin_tests/sources_test.py
- server/tilesource/base.py
Refactored lazy tile loading so that it is lazy even when the target format is not PIL or the source image type.
> Add tests for lazy tile loading.

- package.json
- web_client/js/imageViewerWidget/geojs.js
This simplifies some of the javascript, too.
> Update to the version 0.10.5 of geojs.

- plugin_tests/girderless_test.py
- server/cache_util/cache.py
> Fix requiring girder as a dependency.

- examples/average_color.py
- examples/sumsquare_color.py
- plugin_tests/examples_test.py
- plugin_tests/sources_test.py
- server/tilesource/base.py
Copy from version 1.7 to the version 2 master.
> Add options to retile an image.

- server/cache_util/memcache.py
- server/tilesource/base.py
> Make sure tile width and height are integers.

- server/cache_util/cachefactory.py
- server/cache_util/memcache.py
If not, fall back gracefully.  This also fixes a memcached version mismatch.
> Check if memcached is available.

- plugin.cmake
- plugin_tests/client/annotationSpec.js
- web_client/annotations/convert.js
- web_client/annotations/defaults/index.js
- web_client/annotations/defaults/rectangle.js
- web_client/annotations/index.js
Along with #159, this closes #158.
> Set default style on rectangle annotations

- plugin_tests/annotations_test.py
- server/models/annotation.py
- server/models/annotationelement.py
- server/rest/annotation.py
- server/rest/tiles.py
- web_client/models/AnnotationModel.js
- web_client/views/imageViewerWidget/geojs.js
Annotation elements can be restricted by location, details, size, or the standard paging controls.
> Allow querying annotations by region.

- web_client/views/imageViewerWidget/geojs.js
This fixes regression from #180 where drawing a region in HistomicsTK raises an error.  This will allow us to add `{fetch: false}` [here](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/web_client/views/body/ImageView.js#L320) to prevent attempting to fetch temporary annotations from the server.  I can add tests on top of #186, if I try to do so here, it will just create conflicts.
> Make fetching drawn annotations optional

- plugin.json
- plugin_tests/client/geojsAnnotationSpec.js
- plugin_tests/client/geojsSpec.js
- web_client/annotations/geojs/types/index.js
- web_client/annotations/geojs/types/line.js
- web_client/views/imageViewerWidget/geojs.js
Depends on #185 for geojs's mock vgl renderer.
> Add testing for drawing annotations

- .travis.yml
- server/tilesource/tiff_reader.py
@zachmullen Comments added as per your request in PR #190.
> Add some comments about what arg types is doing.

- plugin_tests/annotations_test.py
- server/rest/annotation.py
This will be used to implement https://github.com/DigitalSlideArchive/HistomicsTK/issues/351.
> Add an endpont to search for annotated images

- plugin_tests/large_image_test.py
Testing fails until this is fixed.  A number of other PRs have this change so that they can pass testing.
The `jobs.cancel` is event is consumed by the remote worker plugin, so we can't rely on it here.  Since we only use it in testing, it is easier to change the tests than to change the order that events are processed in Girder.
> Update tests to handle changes in job cancellation.

- server/rest/tiles.py
This allows images to be shown in the swagger ui.
> Specify produces on swagger end points that return images.

- .travis.yml
- plugin.json
- plugin_tests/client/geojsAnnotationSpec.js
- web_client/annotations/geojs/types/line.js
- web_client/views/imageViewerWidget/geojs.js
This handles line annotations that are closed.
> Upgrade to geojs 0.12.3 and improve line annotations.

- .travis.yml
- requirements.txt
Also, test against libtiff 4.0.8.
> Use python libtiff 0.4.1.

- plugin_tests/annotations_test.py
- server/rest/annotation.py
This endpoint will require : 
- `annotationId` : the ID of the annotation that has to be copied
- `itemDest`: the item to which will be copied the annotation
> Add new endpoint to copy an annotation from an item

- plugin_tests/annotations_test.py
- plugin_tests/cached_tiles_test.py
- plugin_tests/common.py
- plugin_tests/large_image_test.py
- plugin_tests/sources_test.py
- plugin_tests/tiles_test.py
- server/base.py
- server/models/annotation.py
- server/models/image_item.py
- server/rest/annotation.py
- server/rest/large_image.py
- server/rest/tiles.py
- server/tilesource/base.py
- server/tilesource/pil.py
Also, use the canonical exception import locations.
This PR shouldn't change the functional code in any way.
> Change to the new model singleton reference semantics.

- plugin_tests/client/imageViewerSpec.js
- web_client/models/AnnotationModel.js
- web_client/views/fileList.js
- web_client/views/imageViewerSelectWidget.js
- web_client/views/imageViewerWidget/geojs.js
- web_client/views/imageViewerWidget/leaflet.js
- web_client/views/imageViewerWidget/openlayers.js
- web_client/views/imageViewerWidget/openseadragon.js
- web_client/views/imageViewerWidget/slideatlas.js
- web_client/views/itemList.js
This commit fixes issues that will be (but are not yet) present in our linting once https://github.com/girder/girder/pull/2550 is merged.
> Fix new linting errors detected in eslint 4.13

- server/tilesource/pil.py
This better parses PIL modes to handle more 16 bit files.
> Better handle PIL 16 bit modes.

- plugin_tests/source_mapnik_test.py
- server/tilesource/mapniksource.py
This adds band information into the metadata.
> Get more band information for mapnik gdal sources.

- server/models/annotation.py
This issue was caused by a bug in PR #280.
> Annotation elements were being added to the annotation, too.

- .travis.yml
- plugin_tests/cached_tiles_test.py
> Change how celery version is specified.

- server/tilesource/base.py
Some information was only in the _tileIterator docstring.
> Update tile iterator docstring.

- server/tilesource/base.py
- server/tilesource/mapniksource.py
- server/tilesource/pil.py
- server/tilesource/svs.py
- server/tilesource/test.py
- server/tilesource/tiff.py
This mainly improves the mapnik tilesource to describe what options style and projection support.
> Improve tilesource class documentation.

- large_image/__init__.py
This fixes an import issue in non-editable mode (in non-Girder mode).
> Improve installation.

- plugin.json
This version has several performance improvements for large numbers of lines and polygons.
> Update to a geojs 0.19.0.

- plugin_tests/tiles_test.py
- server/rest/tiles.py
This defaults to a tile size of 256 with no overlap.  It will only serve jpeg or png tiles.  Setting the tile size and overlap may not work for some readers, as those values have to be passed via query parameters.
> Add two endpoints to act as a deepzoom server.

- server/tilesource/mapniksource.py
Backport changes from the Girder 3 branch to provide thread safety for GDAL datasets in the Mapnik tilesource
> Acquire lock when accessing GDAL dataset

- girder_annotation/girder_large_image_annotation/web_client/collections/AnnotationCollection.js
This is simpler than implementing paged fetches.
> Increase the annotation page limit.

- girder_annotation/girder_large_image_annotation/web_client/stylesheets/itemList.styl
- girder_annotation/girder_large_image_annotation/web_client/views/index.js
- girder_annotation/girder_large_image_annotation/web_client/views/itemList.js
> add annotation badge to large image preview

- web_client/stylesheets/itemListAnnot.styl
- web_client/views/index.js
- web_client/views/itemListAnnot.js
> Add annotation count badge.

- girder_annotation/test_annotation/web_client_specs/annotationListSpec.js
In local testing, this failed frequently before the change and hasn't since the change.
> Modify the annotationListSpec test to make it more robust.

- girder_annotation/docs/annotations.md
This failed to get moved to the Girder 3 branch.
> Re-add annotations.md.

- girder/setup.py
- girder/test_girder/web_client_specs/largeImageSpec.js
- girder_annotation/setup.py
- girder_annotation/test_annotation/web_client_specs/geojsSpec.js
> Don't generate test packages.

- setup.py
> Pin glymur.

- docs/make_docs.sh
- large_image/constants.py
- large_image/tilesource/base.py
- requirements-dev.txt
- tox.ini
This better preserves numpy data types.
Also, improve building docs.
> Improve how styled tile sources are handled.

- large_image/tilesource/base.py
- sources/nd2/large_image_source_nd2/__init__.py
- sources/ometiff/large_image_source_ometiff/__init__.py
- sources/openjpeg/large_image_source_openjpeg/__init__.py
- sources/tiff/large_image_source_tiff/__init__.py
- sources/tiff/large_image_source_tiff/tiff_reader.py
This reduces code duplication.
> Refactor how frame information is added to metadata.

- setup.py
There was a security warning for version < 7.1.
> Upgrade minimum version of Pillow.

- large_image/cache_util/cache.py
> Revert the workaround for a bug in cheroot.

- sources/openslide/large_image_source_openslide/__init__.py
This just separates out a value from another field.
> Show aperio version in internal metadata.

- CHANGELOG.md
- girder/girder_large_image/rest/tiles.py
- sources/ometiff/large_image_source_ometiff/__init__.py
- tox.ini
The rest endpoints didn't pass through non-boolean resample options.
Improve OME tiff preferred level calculation for OME tiffs with subifds.
> Expose more resample options for region and histogram.

- .circleci/config.yml
- .travis.yml
- Dockerfile
- girder/setup.py
- girder_annotation/setup.py
- requirements-dev.txt
- setup.py
- sources/bioformats/setup.py
- sources/dummy/setup.py
- sources/gdal/setup.py
- sources/mapnik/setup.py
- sources/nd2/setup.py
- sources/ometiff/setup.py
- sources/openjpeg/setup.py
- sources/openslide/setup.py
- sources/pil/setup.py
- sources/test/setup.py
- sources/tiff/setup.py
- tasks/setup.py
- tox.ini
There are at end-of-life.
Closes #499.
> Drop support for Python 2.7 and 3.5.

- .circleci/config.yml
- .travis.yml
- test/test_examples.py
- tox.ini
The docker executors are limited in memory making some tests fail.  The machine executors get twice as much memory and don't have this issue.
> Switch to the machine executor on circle-ci.

- README.rst
- tox.ini
Switch README badge to Circle-CI.
> Remove some remnants of travis.

- girder/test_girder/test_tiles_rest.py
Occasionally, clean up of the PNG conversion test would fail due to some timing issues.  This reduces the potential for the problem to occur.
> Harden tests.

- requirements-dev.txt
- test/test_converter.py
- utilities/converter/large_image_converter/__init__.py
- utilities/converter/large_image_converter/__main__.py
- utilities/converter/setup.py
This includes error metrics and compression efficiency.
> Add an option to compute additional statistics.

- large_image/tilesource/base.py
- sources/nd2/large_image_source_nd2/__init__.py
- sources/ometiff/large_image_source_ometiff/__init__.py
- sources/openslide/large_image_source_openslide/__init__.py
The _xyzInRange function can test frame limits as well.
> Move more repeated code into the base class

- sources/bioformats/large_image_source_bioformats/__init__.py
- sources/tiff/large_image_source_tiff/__init__.py
- sources/tiff/large_image_source_tiff/tiff_reader.py
- test/test_cached_tiles.py
- test/test_converter.py
- test/test_source_tiff.py
- utilities/converter/large_image_converter/__init__.py
- utilities/converter/large_image_converter/__main__.py
This uses tifftools to parse some files.
> Convert to and read multiframe files.

- test/utils/README.rst
- test/utils/compression_test.py
- test/utils/compression_test_summary.py
These might not be maintained, in which case they'll be deleted rather than updated.
> Add some utility scripts that have been useful in testing.

- girder/girder_large_image/web_client/views/imageViewerWidget/geojs.js
Add a utility function to get the current frame and tile url.
> Send events when frames change.

- tox.ini
- utilities/converter/large_image_converter/__init__.py
- utilities/converter/large_image_converter/__main__.py
When using large_image as the source, parallelize tile reads.
> Parallelize tile reads in some conversions

- utilities/converter/large_image_converter/__init__.py
Release memory somewhat sooner in task pools.  Tweak log levels and number of processes.
> Add more documentation.

- utilities/converter/large_image_converter/__init__.py
Before, reading tiles was parallelized, then converting the composited vips image was separately parallelized.  vips ends up keeping a file handle open per tile until the image is closed.  For slow conversion processes (such as jp2k or webp), this could result in the majority of the frames being ready to process all waiting on the first few frames to be written, with a file handle open per tile per frame.  This changes the size of the tiles to reduce the count and parallelizes at the frame level rather than separately at the tile and the save level (tiles are still read in parallel).
Note that for systems with a huge number of processors, we could still have or super large images, we could still exhaust the file handles.  Probably the real solution to this would be to dynamically pick a …
> Reduce open files in conversion.

- Dockerfile
Update versions pip in all installed versions of python.
> In the test dockerfile, update all versions.

- girder/girder_large_image/models/image_item.py
- girder/girder_large_image/rest/tiles.py
- girder/test_girder/test_tiles_rest.py
- utilities/tasks/large_image_tasks/tasks.py
This can run either as a local job or a remote job.  The rationale is that for images that have multiple files, we do not have a reliable mechanism for accessing all of the files in the remote job.
> Add a conversion endpoint.

- Dockerfile
This fixes an issue on circle-ci.
> Add ssh to the test docker image.

- sources/ometiff/large_image_source_ometiff/__init__.py
Ultimately it would be better to refactor this to handle the specification properly, but this adds support for some additional samples we have seen.
> Handle more OME Tiff variations.

- girder/girder_large_image/rest/tiles.py
- large_image/tilesource/base.py
Don't recompute data if two adjacent channels are identical.
> More style compositing optimizations.

- girder/girder_large_image/web_client/package.json
- girder/girder_large_image/web_client/views/imageViewerWidget/slideatlas.js
- girder_annotation/girder_large_image_annotation/models/annotation.py
Update the slide atlas viewer to the latest annotation tools.
> migrated slideatlas viewer to girder3, (+annotation user field)

- setup.py
See https://github.com/python-pillow/Pillow/issues/5586
> Avoid a bad version of Pillow.

- CHANGELOG.md
- girder/girder_large_image/models/image_item.py
- girder/girder_large_image/rest/tiles.py
- girder/test_girder/test_tiles_rest.py
- large_image/tilesource/base.py
- sources/gdal/large_image_source_gdal/__init__.py
- sources/mapnik/large_image_source_mapnik/__init__.py
- test/test_source_pil.py
This also adds a GET item/{id}/tiles/bands endpoint.
Closes #618.
> Add getBandInformation for all tile sources

- girder/girder_large_image/models/image_item.py
- girder/girder_large_image/rest/tiles.py
- girder/test_girder/test_tiles_rest.py
- large_image/tilesource/base.py
- large_image/tilesource/utilities.py
- test/test_source_tiff.py
Add a tilesource utility function and endpoint to render regions from multiple frames as a single tiled image.
> Tile frames

- tox.ini
See https://github.com/scikit-image/scikit-image/issues/5528
> Pin pooch until scikit-image is fixed

- CHANGELOG.md
- sources/gdal/large_image_source_gdal/__init__.py
Closes https://github.com/ResonantGeoData/ResonantGeoData/issues/526
> Fix using GDAL to subset a non-geospatial image.

- CHANGELOG.md
- sources/gdal/large_image_source_gdal/__init__.py
- sources/openjpeg/large_image_source_openjpeg/__init__.py
A missing file doesn't raise an error.
> Handle a change in the Glymur library.

- README.rst
- docs/source/index.rst
To address https://github.com/girder/large_image/issues/692#issuecomment-980505571
> Update README and include in docs

- .circleci/release_pypi.sh
I think this is all that's needed for #703 
I will need a release after this for https://github.com/conda-forge/staged-recipes/pull/17167 to proceed
> Copy LICENSE files when building

- docs/_build
- docs/make_docs.sh
It can cause issues in some deployments.
> Don't store a symlink in git.

- README.rst
Wait until https://github.com/conda-forge/staged-recipes/pull/17167 before merging
Closes #691 
This also lists the non-girder pip installation first as most folks won't be using girder
> Update installation instructions for conda

- setup.py
See
https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies
Closes #723.  See the discussion there.
> Use a different format for specifying extras based on platform.

- large_image/cache_util/__init__.py
- large_image/cache_util/cachefactory.py
- sources/tiff/large_image_source_tiff/tiff_reader.py
- test/test_cache.py
- tox.ini
Reduce some warnings in pytest.
> Simplify cache code.

- CHANGELOG.md
- large_image/tilesource/__init__.py
- large_image/tilesource/base.py
- sources/bioformats/setup.py
- sources/deepzoom/setup.py
- sources/dummy/setup.py
- sources/gdal/setup.py
- sources/mapnik/setup.py
- sources/nd2/setup.py
- sources/ometiff/setup.py
- sources/openjpeg/setup.py
- sources/openslide/setup.py
- sources/pil/setup.py
- sources/test/setup.py
- sources/tiff/setup.py
- test/test_source_base.py
> Expand user directory for FileTileSource paths.

- girder_annotation/setup.py
- sources/bioformats/setup.py
- sources/deepzoom/setup.py
- sources/dummy/setup.py
- sources/gdal/setup.py
- sources/mapnik/setup.py
- sources/nd2/setup.py
- sources/ometiff/setup.py
- sources/openjpeg/setup.py
- sources/openslide/setup.py
- sources/pil/setup.py
- sources/test/setup.py
- sources/tiff/setup.py
> Unpin large-image within subpackages.

- CHANGELOG.md
- docs/tilesource_options.rst
- large_image/tilesource/base.py
- test/test_source_gdal.py
> Support discrete palettes for all tile sources.

- girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js
Closes #757 
This PR makes the following changes:
- In `imageViewerWidget/geojs.js::drawAnnotation`, the check for existing layers for overlay elements has been moved from the `if (present) {...}` check to the `restRequest` callback. Previously, if two calls were made to `drawAnnotation` at roughly the same time for the same annotation, they would both create a new layer for the image overlay. 
- In `imageVierwerWidget/geojs.js::removeAnnotation`, check for any number of layers with the overlay element ID. This is protection in case the image viewer is in a state where more than one layer exists for a single image overlay annotation element. Previously only the first layer found would be deleted.
To test the situation where this issue may occur, I've been setting up a development …
> Make overlay annotations safe in async situations

- docs/annotations.rst
- docs/make_docs.sh
- girder_annotation/docs/annotations.rst
This appends the full schema to the docs.
> Improve the published docs for annotation schema.

- large_image/tilesource/base.py
- sources/multi/large_image_source_multi/__init__.py
- sources/multi/large_image_source_multi/girder_source.py
> Improve schema.

- sources/multi/large_image_source_multi/__init__.py
- test/test_files/multi_test_source.yml
- test/test_source_multi.py
This adds support for passing a json or yaml string to the source instead of a file name.
> Better support for a variety of sources.

- girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js
- girder_annotation/test_annotation/web_client_specs/geojsSpec.js
Similar to how annotation feature elements, hook up overlay elements to mouse events.
> Add mouse events to overlay layers

- .circleci/config.yml
The circleci/mongo images are deprecated.
> Use a different mongo image on circleci.

- large_image/exceptions.py
- large_image/tilesource/base.py
- sources/pil/large_image_source_pil/__init__.py
> Add TileSourceXYZRangeError

- girder/setup.py
- girder_annotation/setup.py
- setup.py
- sources/bioformats/setup.py
- sources/deepzoom/setup.py
- sources/dummy/setup.py
- sources/gdal/setup.py
- sources/mapnik/setup.py
- sources/multi/setup.py
- sources/nd2/setup.py
- sources/ometiff/setup.py
- sources/openjpeg/setup.py
- sources/openslide/setup.py
- sources/pil/setup.py
- sources/test/setup.py
- sources/tiff/setup.py
- sources/vips/setup.py
- utilities/converter/setup.py
- utilities/tasks/setup.py
> Set minimum versions in large-image extras

- .github/workflows/docker.yml
- slim.Dockerfile
Publishes Jupyter docker images as well
> Add Jupyter docker images

- tox.ini
See https://github.com/sphinx-doc/sphinx/issues/10705
> Sphinx 5.1.0 ahs a bug that causes the docs not to build.

- docs/girder_annotation_config_options.rst
- docs/girder_config_options.rst
- docs/index.rst
- girder/girder_large_image/rest/__init__.py
- girder/girder_large_image/web_client/stylesheets/itemList.styl
- girder/girder_large_image/web_client/templates/itemList.pug
- girder/girder_large_image/web_client/templates/largeImageConfig.pug
- girder/girder_large_image/web_client/views/itemList.js
- girder/test_girder/web_client_specs/imageViewerSpec.js
- girder_annotation/girder_large_image_annotation/web_client/views/itemList.js
- test/test_files/.large_image_config.yaml
- tox.ini
Add multi column sorts for item and folder.
See the docs for information.
> Show metadata in item lists

- large_image/tilesource/base.py
- sources/openjpeg/large_image_source_openjpeg/__init__.py
- sources/tiff/large_image_source_tiff/__init__.py
- sources/tiff/large_image_source_tiff/tiff_reader.py
- sources/tifffile/large_image_source_tifffile/__init__.py
Reduce external library logging.
> Improve some error messages.

- CHANGELOG.md
- girder/girder_large_image/web_client/stylesheets/itemList.styl
- girder/girder_large_image/web_client/templates/itemList.pug
- girder/girder_large_image/web_client/views/itemList.js
This should add additional features later:
- A default sort from the config file
- Sort stored in the route so that navigating away and coming back will   restore the sort.
> Make some columns sortable.

- girder/girder_large_image/web_client/stylesheets/itemList.styl
- girder/girder_large_image/web_client/templates/itemList.pug
- girder/test_girder/web_client_specs/imageViewerSpec.js
Strictly, this is only true if there are any columns besides the controls.
> Always have item lists have links to the items.

- girder/girder_large_image/web_client/views/itemList.js
This concludes https://github.com/girder/large_image/pull/925.
> Include sorting in routing for persistent urls

- sources/test/large_image_source_test/__init__.py
- test/test_files/multi_band.yml
- test/test_source_multi.py
This makes it easier to see when multiple bands are composited.
> Make the test source banded images fancier.

- CHANGELOG.md
- girder/girder_large_image/__init__.py
This makes it easier to view yaml and other files after uploading them.
> Improve mimetypes on upload

- CHANGELOG.md
- girder/girder_large_image/web_client/views/itemList.js
Before, this didn't always react well with other plugins.
> Harden adding images to the item list.

- CHANGELOG.md
- girder_annotation/girder_large_image_annotation/web_client/models/AnnotationModel.js
- girder_annotation/test_annotation/web_client_specs/annotationSpec.js
> Fix overcaching annotations.

- girder_annotation/girder_large_image_annotation/models/annotation.py
- sources/mapnik/large_image_source_mapnik/__init__.py
- sources/nd2/large_image_source_nd2/__init__.py
- sources/vips/large_image_source_vips/__init__.py
- utilities/converter/large_image_converter/__init__.py
#996 introduced this formatting. These are the changes produced by that command.
> Run tox -e format

- girder/girder_large_image/web_client/views/itemList.js
- girder_annotation/girder_large_image_annotation/web_client/views/itemList.js
This skips some needless updates.
> Render item lists faster.

- CHANGELOG.md
- docs/tilesource_options.rst
- girder/girder_large_image/models/image_item.py
- large_image/tilesource/base.py
- sources/bioformats/large_image_source_bioformats/__init__.py
- sources/openjpeg/large_image_source_openjpeg/__init__.py
- sources/openslide/large_image_source_openslide/__init__.py
- sources/pil/large_image_source_pil/__init__.py
- sources/tiff/large_image_source_tiff/__init__.py
- sources/tifffile/large_image_source_tifffile/__init__.py
- test/test_converter.py
- test/test_source_base.py
- test/test_source_openslide.py
This is done on tiff and openslide tiff-based sources.
Closes #856.
> Apply ICC profiles.

- girder/setup.py
- girder_annotation/setup.py
- setup.py
- sources/bioformats/setup.py
- sources/deepzoom/setup.py
- sources/dicom/setup.py
- sources/dummy/setup.py
- sources/gdal/setup.py
- sources/mapnik/setup.py
- sources/multi/setup.py
- sources/nd2/setup.py
- sources/ometiff/setup.py
- sources/openjpeg/setup.py
- sources/openslide/setup.py
- sources/pil/setup.py
- sources/test/setup.py
- sources/tiff/setup.py
- sources/tifffile/setup.py
- sources/vips/setup.py
- utilities/converter/setup.py
- utilities/tasks/setup.py
This makes modern pip happier.
> Use a different fallback version for use_scm_version

- CHANGELOG.md
- sources/bioformats/large_image_source_bioformats/__init__.py
Better find reduced resolution layers.
> Speed up some images handled with bioformats.

- requirements-test-core.txt
- requirements-test.txt
- sources/tifffile/setup.py
- test/test_converter.py
- test/test_source_base.py
- utilities/converter/setup.py
Now that scikit-image has released wheels for 3.11, test with them.
> Update some testing with Python 3.11

- .circleci/config.yml
The codecov python client was deleted.
> Switch how codecov reporting is done

- CHANGELOG.md
- large_image/tilesource/base.py
- test/test_source_gdal.py
- test/test_source_mapnik.py
- test/test_source_openslide.py
This is in addition to the channel values that were being returned.
> getPixel method and endpoint now returns rawer values

- CHANGELOG.md
- girder/girder_large_image/web_client/templates/itemList.pug
- girder/girder_large_image/web_client/views/itemList.js
This could be smarter to not duplicate values
> Add filters to metadata columns

- docs/girder_config_options.rst
- girder/girder_large_image/__init__.py
- girder/girder_large_image/models/image_item.py
- girder/girder_large_image/rest/__init__.py
- girder/girder_large_image/rest/tiles.py
- girder/girder_large_image/web_client/templates/itemView.pug
- girder/girder_large_image/web_client/views/imageViewerWidget/geojs.js
- girder/test_girder/test_tiles_rest.py
- large_image/tilesource/base.py
- large_image/tilesource/utilities.py
- setup.py
- sources/deepzoom/large_image_source_deepzoom/__init__.py
- sources/deepzoom/large_image_source_deepzoom/girder_source.py
- sources/multi/large_image_source_multi/__init__.py
- sources/rasterio/large_image_source_rasterio/__init__.py
- sources/tiff/large_image_source_tiff/tiff_reader.py
- sources/vips/large_image_source_vips/__init__.py
- sources/vips/large_image_source_vips/girder_source.py
- utilities/converter/large_image_converter/__init__.py
> Minor code cleanup as recommended by pyupgrade.

- CHANGELOG.md
- girder_annotation/girder_large_image_annotation/rest/annotation.py
We are trying to keep performance and broad compatibility.
> Another refactor of the which-folders-have-annotations pipeline

- test/test_files/README.md
Adding a file to add notes about test files
Contents so far only include a first pass at why `rgba_geotiff.tiff` is unique
> add data file readme

- girder/girder_large_image/web_client/vue/components/FrameSelector.vue
This ensure it maintains reactivity and updates for just the current mode, including clearing for non-compositing modes.
Resolves #1225.
Sets default band names more appropriately when there are other than 3 bands.
> Fix updating the hidden style field for the frame selector

- girder/girder_large_image/web_client/vue/components/CompositeLayers.vue
- girder/girder_large_image/web_client/vue/components/FrameSelector.vue
[921c3f4](https://github.com/girder/large_image/pull/1230/commits/921c3f4dd93ac65c10e189dfb78c6b22f733e682) resolves #1154 
[e96fc8d](https://github.com/girder/large_image/pull/1230/commits/e96fc8d312a0e952fb7f26209475a0b6db4b849f) resolves #1120
> Frame selector widget various fixes

- test.Dockerfile
> Switch to Ubuntu 22.04 as a base for the test docker.

- CHANGELOG.md
- girder/girder_large_image/web_client/templates/itemList.pug
> Fix filter button on item lists

- CHANGELOG.md
- large_image/tilesource/tiledict.py
This sometimes affected histograms
> Harden internal retiling

- girder/girder_large_image/web_client/vue/components/FrameSelector.vue
- girder/girder_large_image/web_client/vue/utils/colors.js
[746b0e8](https://github.com/girder/large_image/pull/1300/commits/746b0e8cf35266200a4c145b2ec41d968e0c021a) resolves #1287.
[a649a88](https://github.com/girder/large_image/pull/1300/commits/a649a88d5b2b0121fa3a49237dc3c01f684fb574) resolves #1295 .
> Band Behavior

- test/test_cache.py
Otherwise, they could react with other tests.
> Mark memcached tests as singular.

- tox.ini
This also has the coverage artifacts on the circleci jobs.
> Report coverage context

- sources/dicom/test_dicom/web_client_specs/dicomWebSpec.js
This performs the import and verifies that a specific large image item was imported.
Fixes: #1311
> Expand DICOMweb client test to include import

- .pre-commit-config.yaml
- CHANGELOG.md
- large_image/tilesource/utilities.py
- test/test_source_mapnik.py
- tox.ini
- utilities/converter/large_image_converter/__init__.py
Fix a few typos in docs and comments.
> Unpin a package in the tox format env

- docs/girder_config_options.rst
Add information about image size.
> Update itemList docs

- sources/dicom/large_image_source_dicom/web_client/templates/assetstoreImport.pug
This is actually limiting the number of series that are imported, not the number of studies.
If we want to limit the number of studies instead, we might need to change a couple of things on the server...
> Fix the limit to say "Series" instead of "Studies"

- girder_annotation/girder_large_image_annotation/__init__.py
- girder_annotation/girder_large_image_annotation/models/annotation.py
- large_image/tilesource/base.py
- utilities/tasks/large_image_tasks/tasks.py
This only occurred after a recent update to the bugbear package.
> Fix a bugbear B026 linting error.

- CHANGELOG.md
- large_image/tilesource/base.py
- large_image/tilesource/tiledict.py
- large_image/tilesource/utilities.py
- sources/tiff/large_image_source_tiff/tiff_reader.py
- test/source_geo_base.py
- test/test_source_base.py
Also improve getting small regions.  In the optimum conditions, this has a net speed increate of around 4.5%.
> Speed up reading tiff tiles slightly

- CHANGELOG.md
- large_image/tilesource/base.py
- large_image/tilesource/tileiterator.py
- sources/gdal/large_image_source_gdal/__init__.py
- sources/rasterio/large_image_source_rasterio/__init__.py
> Make the tile iterator a class.

- CHANGELOG.md
- sources/multi/large_image_source_multi/__init__.py
The multi source could return non uniform band depths.
> Uniform band depth on multi source with non uniform sources

- CHANGELOG.md
- examples/algorithm_progression.py
- test/test_examples.py
Prepare the algorithm progression example to work with different sinks.
> Test the algorithm progression example.

- .pre-commit-config.yaml
- CHANGELOG.md
- examples/algorithm_progression.py
- girder/girder_large_image/web_client/views/imageViewerWidget/geojs.js
- large_image/tilesource/utilities.py
- test/test_sink.py
Also adjust the algorithm progression example.
> Use more tile-frame textures in high frame count images

- CHANGELOG.md
- docs/example_usage.rst
- sources/zarr/large_image_source_zarr/__init__.py
> Update docs based on adding the zarr sink.

- test/lisource_compare.py
> Better format long axes names in the lisource_compare

- examples/algorithm_progression.py
Allow lossy output; speed up generating tiffs from the multi-file sinks; add scale option.
Adjust vips concurrency based on number of workers.  Adjust tile cache size based on the number of process workers.
> Add more options to the algorithm progression example

- CHANGELOG.md
- large_image/tilesource/base.py
Before, it always went through PIL.  Now, for nearest neighbor it stays in numpy
> Improve uint16 image scaling

- test.Dockerfile
This breaks some use cases.  Revert it until that is resolved.
> Revert docker image change.

- CHANGELOG.md
- girder_annotation/girder_large_image_annotation/models/annotationelement.py
- girder_annotation/girder_large_image_annotation/rest/annotation.py
- girder_annotation/girder_large_image_annotation/web_client/models/AnnotationModel.js
- girder_annotation/test_annotation/web_client_specs/annotationSpec.js
- girder_annotation/test_annotation/web_client_specs/geojsSpec.js
Allow specifying a minimum number of annotations elements when maxDetails is used.
> Allow specifying a minimum number of annotations elements.

- CHANGELOG.md
- docs/config_options.rst
- large_image/config.py
- large_image/tilesource/__init__.py
- test/lisource_compare.py
> Disallow certain names from being read by any but specific sources

- CHANGELOG.md
- large_image/tilesource/base.py
- requirements-dev.txt
- requirements-test-core.txt
- requirements-test.txt
- setup.py
- sources/pil/setup.py
- sources/tiff/large_image_source_tiff/tiff_reader.py
- sources/tiff/setup.py
Log slow missing tile construction.
> Speed up decoding jp2k tiff with an optional library.

- sources/zarr/large_image_source_zarr/__init__.py
- test/test_sink.py
> Zarr Sink Channel Metadata Fix

- CHANGELOG.md
- girder/girder_large_image/__init__.py
- girder/girder_large_image/web_client/views/itemViewCodemirror.js
- tox.ini
See https://www.rfc-editor.org/rfc/rfc9512.html
> Use the new official yaml mime-type of application/yaml

- CHANGELOG.md
- sources/multi/large_image_source_multi/__init__.py
Non unity alpha values were not being applied properly.
> Fix a compositing error in transformed multi source images

- CHANGELOG.md
- girder_annotation/girder_large_image_annotation/rest/annotation.py
- girder_annotation/girder_large_image_annotation/utils/__init__.py
- girder_annotation/test_annotation/test_annotations_rest.py
- test.Dockerfile
Refactor the internals of plottable data to make it clearer and easier to reason about.  Change some of the default column keys.
> Better handle plottable metadata across a whole folder

- docs/index.rst
- docs/plottable.rst
- girder/girder_large_image/rest/large_image_resource.py
- girder_annotation/docs/plottable.rst
@annehaley Once CI passes, I'll merge this as is, as it would be handy to point an external user to _any_ documentation, and something is better than nothing.  Changes as follow-on PRs are welcome.
> Document plottable features

- docs/development.rst
- requirements-dev-osx.txt
- tox.ini
@jeffbaumes This is based on our working with OSX.  It shouldn't conflict with the documentation changes in #1597.
> Better document setting up development environments.

- girder_annotation/girder_large_image_annotation/rest/annotation.py
- girder_annotation/girder_large_image_annotation/utils/__init__.py
Don't read adjacent items' annotations if they don't contribute to the collected data.
> Improve plottable data collection.

- CHANGELOG.md
- sources/multi/large_image_source_multi/__init__.py
- test/test_files/multi_test_source_scaling.yml
- test/test_source_multi.py
This also adds the ability to scale pixel values from different sources to better harmonize different dtypes.
> Better handle mixed dtype sources in the multi source

- CHANGELOG.md
- sources/multi/large_image_source_multi/__init__.py
- test/test_source_multi.py
PR #1627 fixed one problem and introduced another.  This fixes it.
> Fix scaling small images in the multi source

- CHANGELOG.md
- sources/gdal/large_image_source_gdal/__init__.py
- test/test_source_gdal.py
Fixes an issue discussed in #1639
> Fix an issue when asking not to resample a GDAL tile iterator

- CHANGELOG.md
- sources/pil/large_image_source_pil/__init__.py
Treat palette mode as able to also be RGB or RGBA
> The PIL source reads more multi-frame images

- CHANGELOG.md
- sources/openjpeg/large_image_source_openjpeg/__init__.py
This matches the extensions we added to the docs
> Add an extension and mimetype to the listed openjpeg handlers

- CHANGELOG.md
- examples/algorithm_progression.py
The command line documentation was misleading.
> Changed the parsing of the open parameter in the algorithm progression

- girder/girder_large_image/web_client/templates/itemList.pug
Remove if statements that conditionally add image columns. Since views are now configurable, it makes sense for the chosen columns, including image columns, to be stable.
> Always show all columns

- test.Dockerfile
Strip libraries; don't include python static libraries
> Reduce the size of the test docker image.

- CHANGELOG.md
- girder/girder_large_image/__init__.py
- sources/gdal/large_image_source_gdal/__init__.py
- test.Dockerfile
Among other changes, it includes the fix for [Fix an issue searching for annotation metadata](https://github.com/girder/large_image/commit/6b135be07b43aff56eb209906e7150ba9a61ba59)
> Merge from master into edit-views-ui

- girder_annotation/girder_large_image_annotation/web_client/views/hierarchyWidget.js
Fix to work with new style menu. Depends on the tiny fix to the class name in https://github.com/girder/girder/pull/3593
> Add a check for adding the menu item to the new-style menu

- CHANGELOG.md
- sources/bioformats/large_image_source_bioformats/__init__.py
> Read magnification values from DICOM when reading them via bioformats

- large_image/cache_util/cachefactory.py
This is to match expectations of the latest version of mypy
> Update a type annotation

- examples/algorithm_progression.py
This writes a single value at the maximum axes locations before fanning out to multiple processes.
> Improve the algorithm progression example with zarr multiprocess

- CHANGELOG.md
- docs/notebooks/large_image_examples.ipynb
- large_image/tilesource/jupyter.py
This simplifies using the local tile server in Jupyter.
> Automatically set the JUPYTER_PROXY value

- large_image/tilesource/base.py
- large_image/tilesource/jupyter.py
- large_image/widgets/FrameSelector.vue
Refactor accessing the unstyled source to make the code clearer.
Cast a few vue component assignments.
> Get unstyled histograms for the jupyter component.

- .circleci/config.yml
- tox.ini
This asks java to reserve less memory
> Reduce memory in CI

- CHANGELOG.md
- sources/dicom/large_image_source_dicom/__init__.py
- tox.ini
This speeds up checking multiple dicom files in the same folder.
> Memoize a check for DICOM series UID

- sources/zarr/large_image_source_zarr/__init__.py
- test/test_sink.py
> Add `minWidth` and `minHeight` to Zarr Sink

- large_image/tilesource/base.py
- large_image/widgets/FrameSelector.vue
- test/test_sink.py
> Reformat metadata for non-uniform axis values

- sources/zarr/large_image_source_zarr/__init__.py
- test/test_sink.py
> Zarr Sink: Allow X and Y to have length 1

- CHANGELOG.md
- large_image/tilesource/geo.py
- test/source_geo_base.py
> Fix a scale error in geospatial native magnification

- sources/zarr/large_image_source_zarr/__init__.py
- test/test_sink.py
> Zarr Sink: Fix downsampled level generation for single-band images

- large_image/tilesource/jupyter.py
> Fix layout height in Google Colab

- .circleci/release_pypi.sh
- .pre-commit-config.yaml
- docs/notebooks/large_image_examples.ipynb
- girder/setup.py
- girder_annotation/setup.py
- setup.py
- sources/bioformats/setup.py
- sources/deepzoom/setup.py
- sources/dicom/setup.py
- sources/dummy/setup.py
- sources/gdal/setup.py
- sources/mapnik/setup.py
- sources/multi/setup.py
- sources/nd2/setup.py
- sources/ometiff/setup.py
- sources/openjpeg/setup.py
- sources/openslide/setup.py
- sources/pil/setup.py
- sources/rasterio/setup.py
- sources/test/setup.py
- sources/tiff/setup.py
- sources/tifffile/setup.py
- sources/vips/setup.py
- sources/zarr/setup.py
- utilities/converter/setup.py
- utilities/tasks/setup.py
Improve quoting in the release script.  Remove deprecated license expressions.  Update pre-commit versions
> Clean up a variety of minor issues

- large_image/widgets/FrameSelector.vue
> Debounce frame update in FrameSelector

- girder/girder_large_image/__init__.py
> Remove explicit cache busting as girder now handles it

- CHANGELOG.md
- girder_annotation/girder_large_image_annotation/web_client/templates/annotationListWidget.pug
We were always showing the created time
> Fix listing updated time in customized annotation lists

- CHANGELOG.md
- sources/tiff/large_image_source_tiff/__init__.py
svs can end up with a tiff mimetype
> Tweak a few source priorities

- CHANGELOG.md
- girder/girder_large_image/models/image_item.py
- girder/girder_large_image/rest/__init__.py
- girder_annotation/girder_large_image_annotation/rest/annotation.py
- girder_annotation/test_annotation/test_annotations_rest.py
Workaround $lookup restrictions.  Add a feature flag for testing this code path.  Rename some internals for clarity.
> Improve DocumentDB support

- sources/dicom/large_image_source_dicom/girder_source.py
When noCache=True, skip searching for adjacent files in the folder. This avoids creating hundreds of S3 adapters per file during import.
> Skip adjacent DICOM file search during import to improve performance
